### ISSUE TITLE
Allow multiple vagrant boxes to be built from a single KIWI xml file

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#1001]
## Problem description

Now that KIWI can also built Virtualbox vagrant boxes, it would be nice if it could do so from a single `config.xml`. Currently, that is not possible: if two `<type image="vmx">` sections are present, then only the last one is considered and having multiple `<vagrantconfig>` entries is forbidden by the XML schema.

## Desired behavior

It would be nice if something like this was possible:
``` xml
<type image="vmx" filesystem="ext4" format="vagrant" boottimeout="0" bootloader="grub2">
       <vagrantconfig provider="libvirt" virtualsize="42"/>
       <vagrantconfig provider="virtualbox" virtualsize="42" virtualbox_guest_additions_present="true"/>
       <size unit="G">42</size>
</type>
```

Furthermore it would be nice if  at least for virtualbox, one could specify additional packages to be installed. This would be useful to include the guest additions, but not having to include or remove these for building libvirt boxes.

## OS and Software information
+ KIWI version: git master
+ Operating system: openSUSE Tumbleweed
+ OBS version: build.opensuse.org

**Comment by schaefi** [comment]
You can do that. See the _multibuild feature of obs

Here is an example project: 

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86/test-image-centos

All you need is:

* A profiled XML description, see example from above
* A _multibuild file in your obs project

**Comment by dcermak** [comment]
Does that work locally (= without OBS/osc) too?

**Comment by schaefi** [comment]
Sure. If you have an XML with profiles you can go like a pipeline

1. kiwi --profile A system build ... --target.dir A
2. kiwi --profile B system build ... --allow-existing-root --target-dir B
3. kiwi --profile C system build ... --allow-existing-root --target-dir C

people usually write a small script to run the builds

**Comment by dcermak** [comment]
Ah ok. I couldn't find the profiles in the documentation, are they somewhere?
