### ISSUE TITLE
Make KIWI python package installable for non root users

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#1022]
## Problem description

KIWI can't be installed from `pip` without being root due too the C tools installation and its makefile trying to install/clean in locations that are outside of the user space or the virtual environment (.e.g it fails trying to clean `/usr/bin/dcounter`). The installation fails when the python script is calling `make tools install`.

## Expected behaviour

KIWI module can be installed in a python virtual environment without requiring root permissions during the installation.

## Steps to reproduce the behaviour

As a regular user run:

```bash
mkdir ~/tmp
cd ~/tmp
python3 -m venv virtualenv
pip install kiwi
```

**Comment by aplanas** [comment]
I would like that too, but executing it still required `root`. What can be the use case then?

**Comment by davidcassany** [comment]
> I would like that too, but executing it still required root. What can be the use case then?

The most obvious use case I see is for development purposes, imagine you are developing a tool that makes use of the KIWI API. Even if the tool needs to run as root it is nice to have the capability of easily build a virtual environment without having to run root commands. In fact, we do that to set the development environment for KIWI, if you check the contribution [docs](https://opensource.suse.com/kiwi/development.html#fork-the-upstream-kiwi-repository) you'll see that setting virtual environment for KIWI does not require root-permissions. I would expect the same procedure to set a virtual environment that makes use of KIWI API.

Also not everything that KIWI offers in the API requires root privileges, you might want to use the KIWI API for something as simple as parsing the `config.xml` file.
