### ISSUE TITLE
rpm-excludedocs is only enabled for zypper

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#1026]
## Problem description

I have glanced over the source code and it looks like the setting `<rpm-excludedocs>` in `<preferences>` only works for zypper. However dnf also supports this via the command line flag `--nodocs`.

Since this has been present in dnf since version 2.2 (see: [bzrh#1379628](https://bugzilla.redhat.com/show_bug.cgi?id=1379628)), I think it is safe to enable this for dnf too.

## Steps to reproduce the behavior

``` xml
<preferences>
  <packagemaneger>dnf</packagemanager>
  <rpm-excludedocs>true<rpm-excludedocs>
</preferences>
```

The setting `rpm-excludedocs` makes no difference.

## OS and Software information
+ KIWI version: git master
+ Operating system: n/a
+ OBS version: n/a

**Comment by Conan-Kudo** [comment]
This is supposed to be working? (cc: @dmach @j-mracek)

https://github.com/SUSE/kiwi/blob/282e6b7823eeca619952f08e4f781f4643889799/kiwi/repository/dnf.py#L293-L296

**Comment by j-mracek** [comment]
@Conan-Kudo I also believe that it should work.

**Comment by dcermak** [comment]
Oh, ok, so I was wrong and this works for dnf too? Then this issue can be closed.

**Comment by davidcassany** [comment]
@dcermak exclude docs, despite the name, is also taken into consideration for apt package manager. No docs are installed by DNF, APT and ZYPPER if this option is set.

I am closing this issue as I see no evidence of a wrong behavior here.
