### ISSUE TITLE
Cleanup supported repository types list

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#1029]
## Problem description

When looking through the available repository types in the RNG schema, I was wondering which of these are actually still relevant:

- apt-deb
- apt-rpm
- deb-dir
- mirrors
- red-carpet
- rpm-dir
- rpm-md
- slack-site
- up2date-mirrors
- urpmi
- yast2

Maybe we should clean them up?

## OS and Software information
+ KIWI version: git master
+ Operating system: not applicable
+ OBS version: not applicable

**Comment by schaefi** [comment]
yes good idea. I think mirrors, red-carpet, slack-site, up2date-mirrors and urpmi can be safeley deleted from the schema
