### ISSUE TITLE
Drop support for Python2

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#1036]
## Problem description

Python2 is announced to be unmaintained from Jan 2020. KIWI supports Python 2.7 and it should not support any python version that is not maintained upstream. Because of that KIWI should drop python2 support **before** the upstream dead line. 

Dropping python2 support 6 months in advance should be enough to enable an smooth transition, meaning that by June 2019 KIWI should drop python2.7 support.

**Comment by Conan-Kudo** [comment]
I will stop shipping python2-kiwi when Fedora 28 goes EOL (Fedora 29+ gets builds with Python 2).

Red Hat Enterprise Linux 7 doesn't have Python 2, though Python 3.6 is available from Fedora EPEL for RHEL/CentOS 7. There is [a request to add a full Python 3 stack to the base distribution](https://bugzilla.redhat.com/show_bug.cgi?id=1639030), but who knows if it'll be done. Is there enough in EPEL for building and using kiwi on Python 3?

**Comment by schaefi** [comment]
Here is the list of modules we need from python3

* python3-PyYAML
* python3-docopt
* python3-lxml
* python3-requests
* python3-setuptools
* python3-xattr

Please note for py2 py3 compatibility kiwi uses the six module. So if we drop py2 this also includes changes in the code for modules loaded through six

**Comment by schaefi** [comment]
the six and futures module will then no longer be needed which is good

**Comment by Conan-Kudo** [comment]
So EPEL7 is missing the following:
> * python36-lxml
> * python36-xattr

The rest exists in EPEL 7 right now.

**Comment by dcermak** [comment]
> So EPEL7 is missing the following:
> 
> > * python36-lxml
> > * python36-xattr
> 
> The rest exists in EPEL 7 right now.

Getting these into EPEL 7 should be doable in half a year, shouldn't it?

**Comment by Conan-Kudo** [comment]
@dcermak Someone could start working on it now, even. :smirk:

**Comment by Conan-Kudo** [comment]
@dcermak Basically, someone has to package `python3-lxml` and `python3-pyxattr` for EPEL7. Once those are done, it'd be easy to build my Fedora package for EPEL7.

**Comment by Conan-Kudo** [comment]
It's planned that (Python 2 is leaving this world in Fedora 32](https://fedoraproject.org/wiki/Changes/RetirePython2).

**Comment by Conan-Kudo** [comment]
It's planned that [Python 2 is leaving this world in Fedora 32](https://fedoraproject.org/wiki/Changes/RetirePython2).

**Comment by mmohring** [comment]
Also, KIWI uses createrepo which I think also needs python2.

**Comment by Conan-Kudo** [comment]
I've dropped Python 2 builds of kiwi in Fedora: https://src.fedoraproject.org/rpms/kiwi/c/38bafa8897b13b657cae8296150ac22ff45be4a7

**Comment by dcermak** [comment]
> Dropping python2 support 6 months in advance should be enough to enable an smooth transition, meaning that by June 2019 KIWI should drop python2.7 support.

So now?

**Comment by Conan-Kudo** [comment]
I'm good with dropping it now, if @dcermak wants to get `python3-pyxattr` packaged in EPEL7. :)

**Comment by schaefi** [comment]
> Also, KIWI uses createrepo which I think also needs python2.

nope only the legacy(perl kiwi) had a module that required createrepo. The python based kiwi
doesn't have any createrepo requirement

**Comment by schaefi** [comment]
> So now?

yes I think it should become a priority now

**Comment by schaefi** [comment]
I have created a branch and started to work on this. As result of the py2 drop there is also an opportunity for us to move the unit tests to pytest supported features that did not exist on py2. I will open another issue for this part because that would be a bigger refactoring of the test

**Comment by schaefi** [comment]
For details checkout:

* https://github.com/SUSE/kiwi/commit/72c82407edca319e157f164d6df8a62bf45cdecd

**Comment by dcermak** [comment]
I've pushed cabad327ff261bbdff768d871127b862015c35ba to your branch @schaefi, feel free to squash it into your commit.

**Comment by schaefi** [comment]
@dcermak thanks. On behalf of your change I update that test to use the mock of open as explained in #1128 and get rid of @patch_open completely. Let's address any further unit test adaptions once we merged the branch with the focus on dropping py2.

Thanks
