### ISSUE TITLE
KIWI creates an empty package list if rpm not installed in image

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#1037]
If rpm is not installed in the image (possible if only `bootstrap` packages are installed), the created `.packages` and `.verified` files are empty. This is due to:

```
[  122s] [ INFO    ]: 09:10:44 | Export rpm packages metadata
[  122s] [ DEBUG   ]: 09:10:44 | EXEC: [chroot /usr/src/packages/KIWI-docker/build/image-root rpm -E %_dbpath]
[  122s] [ DEBUG   ]: 09:10:44 | EXEC: Failed with stderr: chroot: failed to run command â€˜rpmâ€™: No such file or directory
```

As the bootstrap phase uses the database in the imageroot though, ignoring this failure should result in a working output.

**Comment by schaefi** [comment]
yes should be fixed too, thanks

**Comment by Vogtinator** [comment]
Could you change it so that a failure of `rpm -E %_dbpath` is treated like `rpm` wasn't installed?
busybox installs a `/usr/bin/rpm` as well, but it only supports installing packages and not querying.

**Comment by schaefi** [comment]
Would it help if we check against ```/usr/bin/rpmdb``` instead of the rpm binary to identify that the rpm we expect here really exists ?

**Comment by schaefi** [comment]
I doubt busybox will overlay the rpmdb binary as well ? or let's say I hope it doesn't do that

**Comment by Vogtinator** [comment]
> Would it help if we check against /usr/bin/rpmdb instead of the rpm binary to identify that the rpm we expect here really exists ?

Yup, that should work - busybox implements the `rpm` tool as "archiver" only, so no rpmdb.

**Comment by schaefi** [comment]
ok, thanks then let's change this. I'll come up with a followup request soon
