### ISSUE TITLE
/etc/hosts file is not restored when appliance images are created

### ISSUE THREAD

**Issue by novasbc** [SUSE/kiwi#104]
## Problem description
Kiwi8 appliance lack /etc/hosts (and a few other files perhaps).
## Actual behaviour
/etc/hosts is left as /etc/hosts.rpmnew when centos package "setup" is installed.
## Steps to reproduce the behaviour
Create appliance (perhaps CentOS is the only install that exhibits the behavior), observe that /etc/hosts is non-existent, with /etc/hosts.rpmnew present.

Kiwi7 logs showed logic that moved /etc/hosts.rpmnew back into /etc/hosts.

**Comment by schaefi** [comment]
yep pull request open for review, thanks
