### ISSUE TITLE
.kconfig using bash syntax with non-bash /bin/sh

### ISSUE THREAD

**Issue by thkukuk** [SUSE/kiwi#1050]
## Problem description
.kconfig uses bash syntax, but is used with /bin/sh, which is no bash

## Expected behaviour
use only standard shell syntax

## Steps to reproduce the behaviour
Build one of the busybox container images with current kiwi, e.g.
https://build.opensuse.org/package/show/home:kukuk:container/tumbleweed-busybox-image

## OS and Software information
+ KIWI version: 9.17.35
+ Operating system: openSUSE Tumbleweed
+ OBS version: Current

**Comment by schaefi** [comment]
I think you are pointing to the result of

```
shellcheck -s sh kiwi/config/functions.sh
```

It's correct the helper methods there are written to be sourced by bash and clean to shellcheck regarding that shell. To move the code to be sh compliant would be a pretty big change as you can see from the above output.

The helper methods from .kconfig are optional and provided for users to support them writing the config.sh and/or images.sh image scripts. Using the method pool is not mandatory and if I look at:

* https://build.opensuse.org/package/view_file/home:kukuk:container/tumbleweed-busybox-image/config.sh?expand=1

I see that you already disabled using it. This would also have been my recommendation if your shell is busybox.

The majority of our users use the standard shell and have it as part of the image. For the case to create something tiny I think the approach to avoid the kiwi provided helpers is the better solution compared to moving the helpers to be busybox sh compliant and take the risk of breaking many many other people's images.

Thoughts ?

**Comment by thkukuk** [comment]
On Wed, Apr 10, Marcus Schäfer  wrote:

> The majority of our users use the standard shell and have it as part of the
> image. For the case to create something tiny I think the approach to avoid the
> kiwi provided helpers is the better solution compared to moving the helpers to
> be busybox sh compliant and take the risk of breaking many many other people's
> images.
> 
> Thoughts ?

I haven't looked at .kconfig, what is in or if there is something usefull
for building containers.
Currently I don't need it, but I wanted to make aware of it.

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & MicroOS
SUSE Linux GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Mary Higgins, Sri Rasiah, HRB 21284 (AG Nuernberg)

**Comment by schaefi** [comment]
That's just helper methods in the following areas:

* systemd: Methods to enable/disable services, can all be done directly with systemctl
* file handling: Methods to rm/move files, can all be done with the core tools itself
* strip locales, man pages, info files, kernel modules: Can all be done with the core tools itself
* some legacy methods used in custom kiwi initrd descriptions (e.g netboot as used by Rudi in obs)

So I think there is no method that helps you in your area and I'd like to avoid regressions especially on Rudi's side who is with netboot still on the legacy code base.
