### ISSUE TITLE
busybox rpm and derived containers

### ISSUE THREAD

**Issue by thkukuk** [SUSE/kiwi#1051]
## Problem description
busybox base containers don't have a full rpm, only the limited busybox rpm. If you build derived containers, kiwi is trying to call rpm -qa inside the container to gather some data, which fails.

[   66s] creating base package information
[   68s] rpm: invalid option -- 'a'
[   68s] BusyBox v1.30.1 () multi-call binary.

## Expected behaviour
Use the "external" rpm like in all other places, too.
## Steps to reproduce the behaviour
https://build.opensuse.org/package/live_build_log/home:kukuk:container/kubic-metallb-speaker-image/container/x86_64

## OS and Software information
+ KIWI version: 9.17.35
+ Operating system: tumbleweed
+ OBS version:

**Comment by schaefi** [comment]
Yes @davidcassany is already working on that part. The open but still on review pull request is here: https://github.com/SUSE/kiwi/pull/1047

**Comment by davidcassany** [comment]
In fact this has no relation with #1047. I have further reviewed it and this is an issue of the KIWI recipe that OBS uses. See openSUSE/obs-build@ab523b2d this is what calls `chroot <image-root> rpm ...` This code is new to me I was not aware of this post process that takes place for container builds.

Adding @mlschroe  to the discussion. Couldn't it be done just using the `*.packages` file that kiwi is providing? looks like we are duplicating procedures here.

Also another question , which are the side effects of this issue I don't see OBS reporting any error beyond some log messages.

**Comment by mlschroe** [comment]
This is the package list from the base container, so it is different from .packages.

You'll just have some errors in the log file but the build is done anyway. OBS currently doesn't use the generated package list. (It'll probably use it in the future to find out which packages are new and which ones inherited from the base container.)

And yes, I'd prefer if kiwi would generate a package list of the packages in the base container for me ;)

**Comment by davidcassany** [comment]
@mlschroe I see thanks for the clarifications

> And yes, I'd prefer if kiwi would generate a package list of the packages in the base container for me ;)

Wouldn't i just be easier to also pull the `*.packages` file that kiwi generated from the base image and run a diff? I have no idea of how OBS is resolving and pulling the base container but looks like it should be easy to also import the `*.packages` file since it already imports the image tarball and they are located together with the same normalized names.

**Comment by mlschroe** [comment]
Unfortunately I don't have the .packages file in the :full tree, just the container tar.

**Comment by davidcassany** [comment]
Ok, gonna close this issue since there isn't anything to fix on KIWI side for now. @mlschroe about how KIWI can be of any help to get base container data or any other data OBS might require just feel free to reach us, I'd be glad to discuss how to facilitate things.
