### ISSUE TITLE
Kiwi refuses to build valid image as "grub*efi" not explicitly listed

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#1053]
openSUSE-Tumbleweed-Kubic does not pull in any grub packages explicitly, it depends on patterns doing so. This leads to this fatal error though:

```
[   68s] [ ERROR   ]: 12:08:11 | KiwiRuntimeError: 
[   68s] 
[   68s] Firmware set to efi or uefi but not grub*efi* package is
[   68s] part of the image build.
```

**Comment by davidcassany** [comment]
This has been already fixed here https://github.com/SUSE/kiwi/pull/1049 a couple of days ago. We are thinking of deleting checks based on package names because of this sort of issues.

**Comment by Vogtinator** [comment]
Ok - can you submit to openSUSE:Factory ASAP (= now)? It currently breaks building a new snapshot.

**Comment by Vogtinator** [comment]
Judging by the current diff to factory it doesn't look like it's a viable candidate for skipping staging, what would be necessary here - so I'll just add some workarounds where necessary. It didn't break too much, fortunately.
