### ISSUE TITLE
Are baseStripRPM and suseRemovePackagesMarkedForDeletion needed?

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#1054]
## Problem description

KIWI supports the two functions `baseStripRPM` and `suseRemovePackagesMarkedForDeletion`, which both delete packages from the `<packages type="delete">` section. Are they still required? This is currently being done by `SystemPrepare.pinch_system`, making both functions redundant (especially as they only support RPM and not other package managers).

## OS and Software information
+ KIWI version: git master
+ Operating system: 
+ OBS version:

**Comment by schaefi** [comment]
yes those needs to be kept for legacy and compatibility reasons. There is still the netboot code which is in active use by the OBS team for their worker images.

I plan to delete the oemboot code as soon as SLE12-SP4 is released and the 6month transition period from SP3 to SP4 is over.

@davidcassany Can you remember any other reason why we kept boot/oemboot descriptions still alive ?

Thanks

**Comment by davidcassany** [comment]
@schaefi about oemboot as far as I remember the main blocker in order to switch from oemboot to dracut is the extensive use of hooks and tweaks some users are doing. Everything should be possible using dracut initrds, but obviously the switch not straight forward.

**Comment by dcermak** [comment]
A small update on this: the function `baseStripRPM` is not even present in KIWI anymore, it got converted into a NOP in a4a114a1fbdc445c477a924b1342515f890244ab (that was in 2016) and was later deleted.

**Comment by schaefi** [comment]
Thanks David, yes that was the reason why we still kept it.

@dcermak the rpm deletion process was fully covered by kiwi itself and that's the reason why the helper method does nothing. I agree we can, and should, also delete the obsolete suseRemovePackagesMarkedForDeletion method. I'll prepare a PR for that
