### ISSUE TITLE
Remove dependency on genisoimage

### ISSUE THREAD

**Issue by plater** [SUSE/kiwi#106]
## Steps to reproduce the behaviour

**Comment by plater** [comment]
Somehow kiwi has an entwined dependency on a package that is dead in the water and it results in this package being installed by default in every new openSUSE installation regardless of whether kiwi is installed.

**Comment by schaefi** [comment]
I'm sorry I can't see where kiwi depends on cdrkit-cdrtools-compat, looked up package/python3-kiwi-spec-template and did not find a requires. Could you provide more details ?

Thanks

**Comment by plater** [comment]
I want to replace the two lines in the openSUSE package : 
BuildRequires:  cdrkit-cdrtools-compat
BuildRequires:  genisoimage
with BuildRequires:  cdrtools to remove the dependency on the wodim package.
This will enable me to replace the dependency on wodim from patterns-openSUSE with cdrtools and stop wodim from being installed by default on new systems.

**Comment by plater** [comment]
I've had a chance to look at python3-kiwi-spec-template, genisoimage was made as a drop in replacement for mkisofs but has been unmaintained for years. What I need to know is if it is still replaceable. I don't want to break Kiwi.

**Comment by schaefi** [comment]
ok, so the never ending story about this topic. It seemed to be so easy but it isn't. For the kiwi v7 version which you referred to with ```Requires: cdrkit-cdrtools-compat``` see the following thread where we already tried to get rid of it:

* https://github.com/openSUSE/kiwi/pull/509

I can't tell you the exact reasons but it has something to do with the fact that the kiwi v7 version supports old (sle11) and new (up to SLE12, Leap42) distributions. I'm pretty sure people realized that changing the working version will cause some problems down the decade of distributions we support with kiwi v7. Therefore my recommendation; don't touch it :)

The next generation of kiwi (kiwi v8) which should be the reference for issues reported here, supports distributions from SLE12, Leap42 or newer. Therefore I don't had to care for anything older and that made the requirements a little bit easier. However, I choose ```Requires: genisoimage```
for the following reason:

```
commit 47e83f7dcfbe36cde3df3132a723dc5e425fedb2
Author: Marcus Schäfer <ms@suse.com>
Date:   Tue Apr 19 10:09:20 2016 +0200

    Added genisoimage requirement to kiwi spec file
    
    On SLE12 we only have genisoimage, on Leap and Tumbleweed we
    have both genisoimage and mkisofs. For the moment both toolkits
    produces working iso images with kiwi, thus I chose the save
    default with genisoimage
```

Changing this to mkisofs will most probably break it for sle12

In the end my suggestions are:

* keep v7 code base untouched

* if there is a good reason to require mkisofs, e.g unmaintained code we need to change the
  v8 spec template to require genisoimage for sle12 and mkisofs for anything newer or we
  bring mkisofs to sle12 which I would consider the best solution if genisoimage is considered
  unmaintained. We also can think of deleting the requirement for any iso creation tool from the
  spec file and just expect a supported one to be installed. The code could raise an exception
  with an appropriate error message, maybe the best solution

* change filesystem/isofs.py to be able to cope with both genisoimage and mkisofs, prefer mkisofs

As you can see this tool split only creates problems ;)

**Comment by schaefi** [comment]
I'm open for any good solution which at best covers all distributions. Feedback welcome

**Comment by plater** [comment]
Ok I'm lead to understand that Kiwi 7 will function equally with genisoimage and mkisofs which means I can conditionally require mkisofs in the openSUSE spec file?
cdrkit-cdrtools-compat aka wodim really is dead in the water, even ubuntu has switched to cdrtools.
debian has lots of open bugs https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=cdrkit

**Comment by schaefi** [comment]
yes v7 looks up for either genisoimage or mkisofs, it would be nice to have that in v8 too

**Comment by plater** [comment]
If it Requires: /usr/bin/mkisofs it's provided by both cdrkit-cdrtools-compat and mkisofs. That's what I use when removing hard requirements on wodim (the containing package) so as long as Kiwi works with mkisofs then that's what I'll do to the package. It won't hurt sles and will enable me to remove the hard requirement for wodim from patterns-openSUSE.
btw I once had an all out battle with Schilly on the openSUSE mailing list about his attitude but his product works well.

**Comment by plater** [comment]
I'm not sure if 7.03.84 is fixed, I buildrequired mkisofs instead of /usr/bin/mkisofs and the build failed the tests looking for genisoimage.
