### ISSUE TITLE
Not providing a user element with a password results in a usermod or openssl error

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#1061]
## Problem description

The following completely legal (but obviously wrong) user configuration:
``` xml
    <users>
        <user home="/root" name="root" />
    </users>
```
is accepted by KIWI, but results in a `usermod` error:
```
[   54s] [ DEBUG   ]: 21:46:17 | EXEC: Failed with stderr: usermod: no options
[   54s] Usage: usermod [options] LOGIN
[   54s]
[   54s] Options:
```

Adding `pwdformat="plain"` into the `user` element results in an erroneous `openssl` invocation.

## Expected behavior

KIWI should reject the above XML snippet. I would expect the attribute `password` to be mandatory.

## Steps to reproduce the behavior

1. Take a working KIWI image description
2. Delete the `password="foo"` entry from a arbitrary `user` element
3. Build the image

## OS and Software information
+ KIWI version: 9.17.37
+ Operating system: openSUSE Tumbleweed
+ OBS version: build.opensuse.org

**Comment by schaefi** [comment]
Hmm, yes wondering why that issue never came up earlier

**Comment by dcermak** [comment]
> Hmm, yes wondering why that issue never came up earlier

Probably no one thought it would be a good idea to create a user account without a password :wink:
