### ISSUE TITLE
Use grub instead of isolinux for non EFI ISO boot

### ISSUE THREAD

**Issue by ggardet** [SUSE/kiwi#1092]
## Problem description
Trying to build an ISO with `image="iso"` for aarch64 fails with the following error:
```
[ 1275s] [ INFO    ]: 13:46:58 | Setting up isolinux bootloader configuration
[ 1275s] [ ERROR   ]: 13:46:58 | KiwiBootLoaderIsoLinuxPlatformError: host architecture aarch64 not supported for isolinux setup
```

## Expected behaviour
We should be able to build ISO for non-x86.
`isolinux` is not available for non-x86, so we should be able to use `grub2` instead.

## Steps to reproduce the behaviour
Build an image for non-x86 (e.g. aarch64)

## OS and Software information
+ KIWI version: 
+ Operating system: 
+ OBS version:

**Comment by Conan-Kudo** [comment]
At this time, kiwi does not support using grub2 exclusively for ISO boot (that is, not using syslinux/isolinux at all). That currently restricts us to x86 architectures.

**Comment by ggardet** [comment]
@Conan-Kudo, if people who know well kiwi could guide me, I can try to have grub2 support for ISO on non-x86.

**Comment by schaefi** [comment]
I'm working on this in my spare time and plan to continue the work during hackweek. There is a branch open for some time here: poc_use_grub_image_as_isolinux_loader

That one implements the needed steps as I thought it should work. However I had some trouble and then run out of time to continue. Feel free to take a look at the branch and hack around it :)

My plan is to get rid of the syslinux requirement in kiwi and to be able to build iso images for all archs that supports grub or an interface to grub like on s390

Let's use this report as the history for changes in this regard

Thanks

**Comment by schaefi** [comment]
I got it working :)

**Comment by schaefi** [comment]
I'll finish this at suse hack week

**Comment by glaubitz** [comment]
@schaefi We could work on this together during hackweek as I could help with the tests on non-x86 targets.

**Comment by ggardet** [comment]
@schaefi I tried your patches for aarch64, but I get the following error:
```
[  991s] [ INFO    ]: 09:48:39 | Setting up EFI grub bootloader configuration
[  992s] [ INFO    ]: 09:48:39 | Creating grub2 bootloader images
[  992s] [ DEBUG   ]: 09:48:39 | EXEC: [mkdir -p /usr/src/packages/KIWI-iso/live-media.za26o0i6//EFI/BOOT]
[  992s] [ INFO    ]: 09:48:39 | --> Creating identifier file 0xdfcdb9c5
[  992s] [ DEBUG   ]: 09:48:39 | EXEC: [mkdir -p /usr/src/packages/KIWI-iso/live-media.za26o0i6/boot/grub2]
[  992s] [ DEBUG   ]: 09:48:39 | EXEC: [mkdir -p /usr/src/packages/KIWI-iso/live-media.za26o0i6/boot/aarch64/loader/grub2/fonts]
[  992s] [ DEBUG   ]: 09:48:39 | EXEC: [cp /usr/src/packages/KIWI-iso/build/image-root/usr/share/grub2/unicode.pf2 /usr/src/packages/KIWI-iso/live-media.za26o0i6/boot/aarch64/loader/grub2/fonts/unicode.pf2]
[  992s] [ DEBUG   ]: 09:48:39 | EXEC: [mkdir -p /usr/src/packages/KIWI-iso/live-media.za26o0i6/boot/grub2/themes]
[  992s] [ DEBUG   ]: 09:48:39 | EXEC: [rsync -z -a /usr/src/packages/KIWI-iso/build/image-root/usr/share/grub2/themes/openSUSE /usr/src/packages/KIWI-iso/live-media.za26o0i6/boot/grub2/themes]
[  992s] [ DEBUG   ]: 09:48:39 | EXEC: [rsync -z -a --exclude /*.module /usr/src/packages/KIWI-iso/build/image-root/usr/share/grub2/arm64-efi/ /usr/src/packages/KIWI-iso/live-media.za26o0i6/boot/grub2/arm64-efi]
[  992s] [ WARNING ]: 09:48:40 | --> Running fallback setup for shim secure boot efi image
[  992s] [ ERROR   ]: 09:48:40 | KiwiBootLoaderGrubSecureBootError: Microsoft signed shim loader not found
```

For your information, there is no shim on aarch64 and secureboot on aarch64 is as simple as adding `--suse-signed-grub` to `grub2-mkinstall` command, since today: https://build.opensuse.org/request/show/707954

**Comment by Conan-Kudo** [comment]
On Fedora, there is a shim for AArch64, so this codepath needs to exist for that.

**Comment by ggardet** [comment]
> On Fedora, there is a shim for AArch64, so this codepath needs to exist for that.

What for? There is (and will be) no single trusted CA for ARM, as it is for x86_64.
BTW, people want to get rid of shim on x86_64 too. ;)

Anyway, the best way would be to add an option to use, or not, shim on uefi.

**Comment by Conan-Kudo** [comment]
@ggardet Nobody likes shim, but directly signing grub2 is way worse. If you directly sign grub2, literally no one can modify it if they want to. That's the reason why we have shim in the first place.

**Comment by ggardet** [comment]
> @ggardet Nobody likes shim, but directly signing grub2 is way worse. If you directly sign grub2, literally no one can modify it if they want to. That's the reason why we have shim in the first place.

But IIUC, you need one entity (currently Microsoft) who sign a shim and validate third party keys, used for grub, kernel, etc. If nobody wants to take the place of MS, you have no gain to use a shim since you need to manually add the key to your UEFI database.

**Comment by Conan-Kudo** [comment]
@ggardet Microsoft offers a key for AArch64 for the Microsoft WoA laptops, from what I understand.

**Comment by schaefi** [comment]
Hi, thanks for testing this. Yes the shim path was currently not touched. This environment is unfortunately not really standardized. What we do in kiwi is this:

a) A collection of search paths for a $MS signed shim are searched
b) A tool called shim-install is searched, if not found a fallback code that is assumed to be "generic" runs.
    This part is not nice because shim-install is a suse invention and nobody brought this upstream. The 
    fallback code is tested to work on Fedora. I have no idea if it would work for others too
c) An exception is raised if no pre-signed module was found

So in your case you run into c) because no pre-signed module was found. Either because there is no such one on the arch you are testing or you forgot to add the <package name="shim"/> in your XML description.

Given we discuss how to handle the case that no pre-signed module from a trusted party exists and that we decide to run a self-sign would be an option for me if we run into c)

For this case you suggested to apply "--suse-signed-grub" to the grub2-install call. Howver this again sounds really really suse specific and I also could not find that option to exist on my system, Leap 15

So if we go the self-signed way as a potential step d) I only can add it upstream if there is a generic way to do it. Otherwise I fear it's causing too much pain.

After all I think the shim stuff seems to be not directly related to this issue and is probably also not directly architecture dependent, or am I mistaken ?

So maybe this deserves its own issue

Thoughts ?

If you change the firmware attribute to be:

```xml
<type .... firmware="efi"/>
```

you would go without secure boot and that should lead to a successful iso build on arm as well
But I haven't tested this and wanted to continue work here at SUSE's hackweek

Thanks much for your feedback

**Comment by Conan-Kudo** [comment]
@ggardet To clarify, `uefi` requires `shim`, `efi` does not, and will use grub2 directly.

**Comment by schaefi** [comment]
correct

**Comment by ggardet** [comment]
@schaefi FYI, on non-x86, there is no `loader/eltorito.img` and no `loader/boot_hybrid.img`.
So, the current implementation does not work for non-x86.
Maybe the product builder used to build openSUSE DVD may help: https://github.com/openSUSE/product-builder/blob/master/modules/KIWIIsoLinux.pm

**Comment by ggardet** [comment]
I managed to get it working (with some hacks) for both `firmware=efi` and `firmware=uefi`:
* I removed the `/loader/eltorito.img` and `/loader/boot_hybrid.img` part as it is not required for aarch64 (Not sure how to do it properly as I cannot have the arch info easily there, apparently)
* I removed the isolinux part in `live.py` file, for aarch64 only.
* I reworked the SecureBoot code to remove the shim for aarch64 (I should add an option for this one, as fedora uses shim for aarch64)

**Comment by schaefi** [comment]
> on non-x86, there is no loader/eltorito.img

That grub image is created by the kiwi code for x86 only. you are right the later xorriso call
referenced that in ```'-boot_image', 'isolinux', 'bin_path={0}'.format(loader_file),``` and will fail on non x86
How did you solve this, just skipped it ?

> and no loader/boot_hybrid.img.

right that file is taken from the grub install ```/usr/lib/grub2/i386-pc/boot_hybrid.im``` and does not exists for other archs. That file is referenced in the xorriso call at ```'-boot_image', 'grub', 'grub2_mbr={0}'.format(mbr_file)```. So hybrid ISO is probably something we can't have on e.g arm ? How did you solve that part, probably skipped ?

Thanks much for the feedback, there is still some work to be done. Would you like to share the patches you did ? Would be great. Thanks

**Comment by schaefi** [comment]
> Maybe the product builder used to build openSUSE DVD may help

The product builder takes information from a pre-built package of the distribution that also does not get released. iirc it is named installation-images. That package contains e.g binaries and other pre-built loader that are used by the product builder to create the media. The problem here is the internal only available information from installation-images. Thus we can't create a generic solution based on this data because it's actually not really available publicly. The reason is not to hide something it's just the case that all this data is exclusively used suse internal to produce product media and there were no effort to make this an opensource project. That's why I did not jump on it so far.

**Comment by ggardet** [comment]
Here is my current branch, on top of your branch: https://github.com/ggardet/kiwi/commits/poc_use_grub_image_as_isolinux_loader

**Comment by ggardet** [comment]
Another thing is `Boot from harddisk` tries to load `bootx64.efi` which is x86 specific.
Is it from https://github.com/SUSE/kiwi/blob/979a42cbc493e3b7fceadd3e16b17eedeed2d3ec/kiwi/bootloader/template/grub2.py#L304 ?

**Comment by schaefi** [comment]
yeah that's stupid. The information should be taken from Defaults.get_efi_image_name(). The static template entry cannot be used that way if we open up iso builds for other archs. Thanks for pointing it out

**Comment by schaefi** [comment]
Pushing two commits that fixes the creation of the install iso media and makes the ```boot from harddisk```  arch dependent. While looking at that menu entry I realized this will only work if that harddisk has root set with the label EFI and is actually an efi based disk. So this entry had its limitations before and we might have another discussion how useful it is at all...

**Comment by schaefi** [comment]
>I removed the /loader/eltorito.img and /loader/boot_hybrid.img part as it is not required for aarch64 (Not >sure how to do it properly as I cannot have the arch info easily there, apparently)

included now

> I removed the isolinux part in live.py file, for aarch64 only.

included now by the distinction between the bios|efi firmware setting

> I reworked the SecureBoot code 

I will leave that part as it is for now. We are going to handle the shim stuff separately as there are also other changes in flux. With firmware="efi" all should be good

I also have setup an integration test in the arm space for testing. During the next days I'll do further changes and are confident to get this done by the end of the week.

More details will follow

**Comment by schaefi** [comment]
@ggardet thanks much for all your feedback and coding. It all summarized in #1113 and I have a successful iso build for arm here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_arm/test-image-iso

**Comment by ggardet** [comment]
> @ggardet thanks much for all your feedback and coding. It all summarized in #1113 and I have a successful iso build for arm here:
> 
> * https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_arm/test-image-iso

@schaefi Thanks!
I tested this image and it does boot in a non-SecureBoot environment. 
But it fails to boot in a secure environment. I guess the grub used, is not the signed grub, but the modular unsigned grub?

The `Boot from hard disk` entry fails with `error: no such device: EFI` .

**Comment by schaefi** [comment]
Thanks for testing, that's great

regarding secure boot it is expected to fail. I'm not using the signed grub. Regarding the EFI label lookup of the harddisk I need to do some checks. The current way expects the rootfs to take the EFI label if that does not apply to any of the attached disks you will receive the "no such device message". It has its limits. The concept is based on the label as kiwi would set but the OS not necessarily has to have that layout. I'm open for any better generic way of saying "Boot installed system"

**Comment by schaefi** [comment]
@ggardet I have setup a secure boot build without shim package for aarch64 here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_arm/test-image-secure-boot-iso

As expected it fails with:

```
[  238s] [ WARNING ]: 10:46:06 | --> Running fallback setup for shim secure boot efi image
[  238s] [ ERROR   ]: 10:46:06 | KiwiBootLoaderGrubSecureBootError: Microsoft signed shim loader not found
```

We are looking for a signed image at

```python
shim_file_patterns = [
    '/usr/share/efi/*/shim.efi',
    '/usr/lib64/efi/shim.efi',
    '/boot/efi/EFI/*/shim.efi'
]
```

There is none in the system which is not a surprise because the shim package usually provides it.
So this now heads into the discussion about the suse-specific grub extension and the refactoring of all that. As of now I think we have to wait until they have completed their refactoring.

Thoughts ?

**Comment by ggardet** [comment]
@schaefi 
Regarding secureboot, we should use `/usr/share/grub2/arm64-efi/grub.efi` file which is the signed grub. Maybe just make the missing `shim` non-fatal? A small rework of https://github.com/ggardet/kiwi/commit/4ac0c87810f65b99d2bbc6eb4c7f0bfb10e680c0 should do it.

Regarding the boot from hard disk, could we use the `boot` flag set on EFI partition instead of (or in addition to) the label?

**Comment by schaefi** [comment]
Thanks for the update. I'll take a look to the signed loader you mentioned

> Regarding the boot from hard disk, could we use the boot flag set on EFI partition

I'm not aware of the concept of a boot flag for EFI set on some GPT partition. Does that exist ?  I only know this from the dos partition table.

Thanks

**Comment by Conan-Kudo** [comment]
The problem with grub being signed by Microsoft means that it's a pain to update how GRUB is built. That's the original reason for the split after all.

This is why KIWI handles `uefi` requiring `shim` and `efi` not requiring `shim`. That said, these labels for describing this feature are awful...

**Comment by Conan-Kudo** [comment]
@ggardet If you don't want `shim`, just use `efi`. Plain and simple.

**Comment by ggardet** [comment]
> @ggardet If you don't want `shim`, just use `efi`. Plain and simple.

The problem is `efi` does not use a signed grub.

**Comment by schaefi** [comment]
@ggardet ok a small change on the kiwi side allows the fallback code now to use a signed grub module without a shim signed pre-loader available. The resulting integration test build is here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_arm/test-image-secure-boot-iso

Could you give this a test with regards to secure boot. The fallback code has kicked in:

```
[  439s] [ WARNING ]: 08:10:52 | --> Running fallback setup for shim secure boot efi image
[  439s] [ DEBUG   ]: 08:10:53 | EXEC: [cp /usr/src/packages/KIWI-iso/build/image-root/usr/share/efi/aarch64/grub.efi /usr/src/packages/KIWI-iso/live-media.w31cahg8/EFI/BOOT]
```

Now we only need to make sure this also works on other distros. Unfortunately the Fedora build still did not start

**Comment by ggardet** [comment]
> Now we only need to make sure this also works on other distros. Unfortunately the Fedora build still did not start

You should remove this part:
```
<!-- The line below is required in order to use the multibuild OBS features -->
<!-- OBS-Profiles: @BUILD_FLAVOR@ -->
```
from the kiwi file.

**Comment by schaefi** [comment]
>    You should remove this part:
> 
> 

I'm so stupid. Thanks much. This was just a cut&paste problem
Fedora test is now also in building state

**Comment by vinyanalista** [comment]
Does that change (using GRUB2 for both EFI and non EFI ISO boot) affect all the architectures? (including x86_64)

The appliance I build here seems to be working that way (using only GRUB2):

- https://build.opensuse.org/package/show/home:kamarada:15.1:dev/Linux-Kamarada-GNOME
- Source: https://github.com/kamarada/Linux-Kamarada-GNOME/tree/15.1-dev

What if I want the old behavior? Is there a way to achieve that using latest KIWI?

openSUSE Leap 15.1 live images downloaded from [software.opensuse.org](https://software.opensuse.org/distributions/leap) work that way:

- isolinux is used when booting on a non EFI machine
- GRUB2 is used when booting on an EFI machine

That is easy to test using VirtualBox.

**Comment by schaefi** [comment]
>Does that change (using GRUB2 for both EFI and non EFI ISO boot) affect all the architectures ?
>(including x86_64)

yes

> What if I want the old behavior?

If you set ```firmware="bios"``` you will get back isolinux on x86 archs. That is considered the most stable boot method for BIOS based systems.

If you have efi|uefi firmware enabled you run on EFI machines which supports legacy (CSM) old bios style booting. On such systems grub is the most stable method and used in any boot mode

The exact same behavior: meaning isolinux in bios mode and grub in efi mode you can't get back

> openSUSE Leap 15.1 live images downloaded from software.opensuse.org work that way:

only because they got build with a kiwi builder that didn't had this change. As soon as the live images gets build with the kiwi that has this patch they will also apply to grub being used if the efi firmware is enabled

**Comment by vinyanalista** [comment]
Your answer explains everything. Thank you for the clarification!

**Comment by vinyanalista** [comment]
Maybe you want to review these appliances:

- https://github.com/OSInside/kiwi/blob/master/build-tests/x86/test-image-iso/appliance.kiwi

I believe it does not need `gfxboot-branding-openSUSE` anymore, as it only uses `firmware="efi"`, and `gfxboot-branding` is for isolinux. For EFI images, `grub2-branding` should be enough.

- https://build.opensuse.org/package/view_file/openSUSE:Leap:15.1:Images/livecd-leap-gnome/livecd-leap-gnome.kiwi?expand=1

Maybe `gfxboot-branding-openSUSE` should be included only on the EFI profile.

**Comment by schaefi** [comment]
>    Maybe you want to review these appliances:
>      * [1]https://github.com/OSInside/kiwi/blob/master/build-tests/x86/tes
>        t-image-iso/appliance.kiwi
> 
>    I believe it does not need gfxboot-branding-openSUSE anymore

You are right. Good catch. See: https://github.com/OSInside/kiwi/pull/1178

Thanks

**Comment by sicevi4913** [comment]
[Watch Ruby reid Onlyfans s – Lesbian Sex Tape With Splatxo](https://porncheck.live/archives/4151)

[Watch Anna Malygon/Maligoshik Play Dildo On Bed ](https://porncheck.live/archives/3502)
 
Watch [Alexisshv – Riding With Dildo ](https://porncheck.live/archives/7674)

[Watch Jellybeanbrains Onlyfans Blowjob Skill Pro ](https://porncheck.live/archives/4131)

[Watch Kawaiisofey / Aishah Sofey Nude – Fuck BackSide ](https://porncheck.live/archives/6577)

[Watch Kelsey Lawrence s – Doggy Style ](https://porncheck.live/archives/5644)

[Watch Hannah Becker Onlyfans – Fuck With dildo]( https://porncheck.live/archives/6859)

[Watch Marie Temara Onlyfans – POV Dildo Ride Porn ](https://porncheck.live/archives/3142)
 
[Watch Mellooow – Nude Play Body  ](https://porncheck.live/archives/4152)

[Watch Itscarlyjane Onlyfans – Play With Dildo](https://porncheck.live/archives/4832)

[Watch Camilla Araujo Onlyfans s – Nude Shower Tease Boobs](https://porncheck.live/archives/3945)
