### ISSUE TITLE
Running commands after setup but before packages

### ISSUE THREAD

**Issue by Sandvich** [SUSE/kiwi#1099]
Hi,
I'm looking to run some commands after an OEM image has been written to the filesystem. To be precise, it can happen any time after the users are created, but ideally should be before the additional packages are installed.

I found some limited documentation about "postImageDump.sh", but this appears to be for an old version of kiwi.
Is there a way to do this?

In case it helps (because it's entirely possible that I'm approaching this in completely the wrong way), I want to do the following in this script:
- Make sure that the default python is 3.x, not 2.x
- Import some GPG and SSH keys (for a repo and to enable me to SSH to the newly installed OS)
- Enable SSHD and open port 22
- Edit the polkit rules so that libvirtd can be accessed by regular users, not just root/sudoers.

Thanks!
**Note: I'm running kiwi locally on my system, not via OBS.**

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.17.39
+ Operating system: OpenSuse Leap 15.1
+ OBS version: N/A

**Comment by davidcassany** [comment]
> I'm looking to run some commands after an OEM image has been written to the filesystem. 

This is no possible with KIWI, once the image data is rsynced to a disk with the specified filesystem is not possible to run commands over there anymore. There is only an exception for that, but it is meant to be used to customize the bootloader with non standard procedures (e.g. uboot for ARM plus some specific board)

> To be precise, it can happen any time after the users are created, but ideally should be before the additional packages are installed.

Users are created after all packages are installed and then `config.sh` is executed chrooting into the image root tree. Are you using dracut base images? (aka your `<type>` section includes `initrd_system="dracut"` attribute). I'd suggest you to use dracut based images unless you have some old OEM specific hook in place for the initrd. Probably the custom initrd installation creation is confusing you. In any case, I believe the scripting logic you want suits well with the `config.sh` script.
 
> In case it helps (because it's entirely possible that I'm approaching this in completely the wrong way), I want to do the following in this script:
> 
>     * Make sure that the default python is 3.x, not 2.x

Yes, this can be configured in adding some commands in `config.sh`

>     * Import some GPG and SSH keys (for a repo and to enable me to SSH to the newly installed OS)

Again you can import the keys in `config.sh` script. Just note that if you are not pulling them from internet and importing them from some local files you should make sure to include them in the root overlay tree (add them in `root.tar.gz` tarball or the `root` folder).

>     * Enable SSHD and open port 22

This can be also done in `config.sh`, see this example [here](https://github.com/SUSE/kiwi-descriptions/blob/18827c21911e847b97725b702556cdcb6ae06277/suse/x86_64/suse-leap-15.1-JeOS/config.sh#L50)

>     * Edit the polkit rules so that libvirtd can be accessed by regular users, not just root/sudoers.

Again just append the commands you need to modify the polkit rules in `config.sh`

**Comment by Sandvich** [comment]
Perfect - thanks for the reply. Right now I'm attempting a new build based on my own system (I looked at the patterns installed on here to decide what to install on the image). Hopefully it'll work :)

**Comment by Sandvich** [comment]
Okay, so for some reason that's only partially worked. Specifically, the issue I'm having is that regardless of what I put in it still targets the CLI interface. I've installed:
```xml
  <!-- Installed packages -->
  <packages type="image">
    <package name="checkmedia"/>
    <package name="patterns-openSUSE-base"/>
    <package name="plymouth-branding-openSUSE"/>
    <package name="plymouth-dracut"/>
    <package name="grub2-branding-openSUSE"/>
    <package name="ifplugd"/>
    <package name="iputils"/>
    <package name="vim"/>
    <package name="grub2"/>
    <package name="grub2-x86_64-efi" arch="x86_64"/>
    <package name="grub2-i386-pc"/>
    <package name="syslinux"/>
    <package name="sudo"/>
    <package name="lvm2"/>
    <package name="plymouth"/>
    <package name="fontconfig"/>
    <package name="fonts-config"/>
    <package name="tar"/>
    <package name="parted"/>
    <package name="openssh"/>
    <package name="iproute2"/>
    <package name="less"/>
    <package name="bash-completion"/>
    <package name="dhcp-client"/>
    <package name="which"/>
    <package name="shim"/>
    <package name="kernel-default"/>
    <package name="timezone"/>
    <package name="git" />
    <package name="java-10-openjdk-devel" />
    <package name="python3-pip" />
    <namedCollection name="32bit" />
    <namedCollection name="apparmor" />
    <namedCollection name="base" />
    <namedCollection name="console" />
    <namedCollection name="enhanced_base" />
    <namedCollection name="fonts" />
    <namedCollection name="imaging" />
    <namedCollection name="kde" />
    <namedCollection name="kde_pim" />
    <namedCollection name="kde_plasma" />
    <namedCollection name="kvm_server" />
    <namedCollection name="kvm_tools" />
    <namedCollection name="multimedia" />
    <namedCollection name="office" />
    <namedCollection name="sw_management" />
    <namedCollection name="update_test" />
    <namedCollection name="x11" />
    <namedCollection name="yast2_basis" />
  </packages>
  <packages type="oem">
    <package name="gfxboot-branding-openSUSE"/>
    <package name="dracut-kiwi-oem-repart"/>
    <package name="dracut-kiwi-oem-dump"/>
    <package name="enpass" />
    <package name="x11-video-nvidiaG05" />
    <package name="nvidia-glG05" />
    <package name="nvidia-gfxG05-kmp-default" />
    <package name="nvidia-computeG05" />
    <package name="qemu-kvm" />
  </packages>
  <packages type="bootstrap">
    <package name="udev"/>
    <package name="filesystem"/>
    <package name="glibc-locale"/>
    <package name="cracklib-dict-full"/>
    <package name="ca-certificates"/>
    <package name="ca-certificates-cacert"/>
    <package name="ca-certificates-mozilla"/>
    <package name="openSUSE-release"/>
  </packages>
```
Is there a package I'm missing?

**Comment by schaefi** [comment]
I guess you just forgot to enable the services that actually starts the X system.

So in your config,sh add

```
baseInsertService display-manager
```

rebuild the image and boot. If you still don't see any graphics. Check ```systemctl status display-manager```

**Comment by Sandvich** [comment]
I'm not sure if that's what fixed it or not, but I was also referring to SDDM as SSDM... So that may well have been part of it ^^;
Thanks for all your help!
