### ISSUE TITLE
Allow users with no passwords

### ISSUE THREAD

**Issue by Sandvich** [SUSE/kiwi#1100]
## Problem description
Plenty of times, we need a user who doesn't have a password. There are workarounds in kiwi (for now I've simply added a random string as the root password, whilst leaving it as the hashed type), but it should be possible to omit the password field altogether.

Note: The [schema documentation](https://opensource.suse.com/kiwi/development/schema.html#id316) claims that the password field is optional, as I would expect. However, kiwi still raises this as an error.

**Comment by schaefi** [comment]
The field error has been fixed with #1070 

Regarding an empty password for the attribute is a bit tricky. I haven't tried it but I assume PAM will refuse login of users that has no password set. Thus apart from allowing the user setup with an empty
password I think more places of the system would need to change, or am I mistaken ?

Thanks

**Comment by schaefi** [comment]
I have tried several ways to configure an account without a password on Leap 15.0. I tried the ideas from:

* https://old-en.opensuse.org/How_can_I_create_a_passwordless_user
* https://unix.stackexchange.com/questions/128/how-do-you-create-a-user-with-no-password

None of them ever worked. I always get prompted with a password and if not set can't login.

I'm pretty sure any distro is different in this regard and some information on the web might also be wrong or outdated. Thus if you have a process that works on any distro I'm willing to implement it :)

Thanks

**Comment by schaefi** [comment]
I'm closing this on behalf of the above information. I'm sorry I could not came up with a process that would be cross distro functional. Thus I'm afraid custom code in config.sh is needed to address this.

I'm happy to implement a procedure when the time comes that this follows a common standard.

Thanks
