### ISSUE TITLE
Insane memory usage in container_image_oci_test.py when a kiwi.yml exists

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#1110]
## Problem description

I've just checked out KIWI's master branch (HEAD is at 79c8c05fb27770c48f0669eb632a0bf59014eb12) and tried running the unit tests, only seeing my system freeze completely. Turns out that once pytest reaches `container_image_oci_test.py`, it starts consuming more and more memory and never gives it back (I usually kill it at the 10 GB mark, but I don't expect it to stop). I've tried this from a fresh copy too, same behavior.

The only remaining difference to a pristine system is my local `/etc/kiwi.yml` configuration file. Removing it solves the problem: the memory leak is gone. Once the file exists (it needn't have any content at all), the memory leak is back.

## Expected behavior

The unit tests shouldn't consume all my system's memory.

## Steps to reproduce the behavior

**Warning!** Keep the memory usage of your system under constant observation and be prepared to kill tox.
``` shell
$ sudo touch /etc/kiwi.yml
$ # The following command will nuke your system if you don't Ctrl+C it
$ tox -e unit_py3_7
```

## OS and Software information
+ KIWI version: 79c8c05fb27770c48f0669eb632a0bf59014eb12
+ Operating system: openSUSE Tumbleweed

**Comment by schaefi** [comment]
That sounds really bad. Thanks for reporting

**Comment by schaefi** [comment]
@davidcassany could you have a look if time permits ? Thanks

**Comment by davidcassany** [comment]
@scheafi, @dcermak sure I'll start having a look right now. This sounds really bad.
