### ISSUE TITLE
dracut output should not be suppressed

### ISSUE THREAD

**Issue by seife** [SUSE/kiwi#1114]
## Problem description
I built an vmx image with LVM setup for root and /var and it did not boot, because "lvm2" was not in the packages list.

It would have helped the debugging, if dracut output during build would have been available, a message like:

```
dracut: dracut module 'lvm' will not be installed, because command 'lvm' could not be found!
```

would surely helped pin down the issue :-)

**Comment by davidcassany** [comment]
I started to work on this one. Today I hit the same need to debug an inconsistent initrd created by dracut within a KIWI build and I also missed this output.

@schaefi gonna present the output in a similar way of what we do when calling `config.sh` script.

**Comment by schaefi** [comment]
That's great :+1: Thanks
