### ISSUE TITLE
Don't set vm.base_mac in Vagrantfile created by kiwi

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#1119]
## Problem description

When kiwi builds a vagrant box, then it embeds a `Vagrantfile` into the box with roughly these contents (for Virtualbox boxes, for libvirt there's a little more):
``` ruby
Vagrant.configure("2") do |config|
  config.vm.base_mac = "00163E010101"
end
```

This can be a problem: depending on your exact setup, your boxes might not come online, because the DHCP server will assign all of them the same IP.

## Expected behavior

Either we shouldn't set the MAC address at all or create a random one for each launched VM, but this MAC address **must** persist over reboots.

## References

- I've asked upstream what is the official recommendation: https://github.com/hashicorp/vagrant/issues/10946

- @sigsteve ran into DHCP issues with KIWI boxes, but I was unable to reproduce these.

## OS and Software information
+ KIWI version: git master
+ Operating system: openSUSE Tumbleweed
+ OBS version: build.opensuse.org

**Comment by davidcassany** [comment]
This is interesting, I believe from an appliance builder point of view that KIWI should not provide any MAC and let Vagrant (or vagrant provider) manage it. The machine should be stateless and deployable any time any where, so no MAC, no machine ID, etc unless those values are not explicitly provided in the image description, they should not be part of the image IMHO. I doubt there is much we can do from a KIWI perspective to improve this specific issue, as far as I see this is something that should be handled by the vagrant provider.

What should be done in KIWI, in relation to this issue, is do not provide any MAC address in the templated vagrant file.

Does it make sense to you?

**Comment by dcermak** [comment]
> This is interesting, I believe from an appliance builder point of view that KIWI should not provide any MAC and let Vagrant (or vagrant provider) manage it. The machine should be stateless and deployable any time any where, so no MAC, no machine ID, etc unless those values are not explicitly provided in the image description, they should not be part of the image IMHO. I doubt there is much we can do from a KIWI perspective to improve this specific issue, as far as I see this is something that should be handled by the vagrant provider.
> 
> What should be done in KIWI, in relation to this issue, is do not provide any MAC address in the templated vagrant file.
> 
> Does it make sense to you?

Completely! I only kept the code inserting `config.vm.base_mac` into the embedded `Vagrantfile` because I was not sure why it existed and because I saw exactly the same in packer images. According to my understanding it used to be required for Virtualbox boxes, because Vagrant wouldn't give these an automatically generated MAC.

If upstream responds to the issue I created confirming my suspicion, then I'd vote to remove that code as it appears to be no longer used and just causes problems. With the current vagrant release (2.2.5), `config.vm.base_mac` seems no longer required (at least it wasn't in my experiments).

**Comment by schaefi** [comment]
> If upstream responds to the issue I created confirming my suspicion, then I'd vote to remove that code 
> as it appears to be no longer used and just causes problems. With the current vagrant release (2.2.5), > config.vm.base_mac seems no longer required (at least it wasn't in my experiments).

Let's remove it

**Comment by schaefi** [comment]
I would do this part before the implementation of #1120

**Comment by dcermak** [comment]
> Let's remove it

I'd rather not do that unless upstream confirms that that's safe, as it might cause issues for users with older Vagrant version or with different setups.

**Comment by schaefi** [comment]
At the time I worked with vagrant the version there refused to run the machine if no mac was set. The setting however could be overwritten in a custom Vagrantfile. I thought it would be a user friendly feature to create a random mac at creation time of the box. But this could cause the problems you mentioned and it's hard to revert a setting in an embedded configuration. I agree, feedback from upstream is appreciated but I think it's correct to prevent the static mac setup in any case.

**Comment by dcermak** [comment]
Upstream confirmed what I was thinking in https://github.com/hashicorp/vagrant/issues/10946: the `base_mac` used to be required for Virtualbox but that necessity got removed in https://github.com/hashicorp/vagrant/pull/10255. Unfortunately that PR was made only last fall and made it to vagrant v2.2.0 (which is still pretty recent and not in every distro's repositories).

What we definitely can do:
- [ ] drop the `base_mac` option for libvirt, it is not used by the vagrant-libvirt provider

We have the following options:
1. Drop the addition of `base_mac` for Virtualbox and break every kiwi box for users of Vagrant < 2.2.0.
2. Keep the `base_mac` setting for now until Vagrant 2.2.0 is old enough that most people should have migrated away from it. Users who encounter issues with the MAC address, should simply upgrade vagrant to solve the issue.

I would prefer option two if we document this issue.
