### ISSUE TITLE
Provide a way how the embedded Vagrantfile of vagrant boxes can be modified

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#1120]
## Problem description

Currently there is no way how the embedded `Vagrantfile` inside a built vagrant box can be modified. For most purposes that is fine, but sometimes we have to ship custom settings: e.g. for aarch64 vagrant boxes one has to turn off certain libvirt features, as these are unavailable on ARM.

cc @sigsteve

## Expected behavior

It would be nice if we could provide a custom Vagrantfile instead of the standard one.

I see two options:
1. KIWI will first look into the description directory for a file named `Vagrantfile` and use that. If it is not present, it will use the generated one. This is about the simplest solution, unfortunately it has the disadvantage that boxes for multiple archs (x86, aarch64) will share the Vagrantfile.
2. Embbedd the Vagrantfile or parts of it in `config.xml`, e.g.:
``` xml
<type image="vmx" filesystem="ext4" format="vagrant" boottimeout="0" bootloader="grub2">
  <vagrantconfig provider="libvirt" virtualsize="42">
    <vagrantfile>
  config.vm.provider :libvirt do |libvirt|
    libvirt.features = ["apic"]
    libvirt.driver = 'kvm'
    libvirt.host = 'localhost'
    libvirt.uri = 'qemu:///system'
    libvirt.memory = '2048'
    libvirt.cpus = '1'
    libvirt.host = "master"
    libvirt.nvram = ""
    libvirt.loader = "/usr/share/qemu/aavmf-aarch64-code.bin"
    libvirt.video_type = "vga"
    libvirt.cpu_mode = "host-passthrough"
    libvirt.machine_type = "virt-3.1"
    libvirt.emulator_path = "/usr/bin/qemu-system-aarch64"
  end
    </vagrantfile>
  </vagrantconfig>
  <size unit="G">42</size>
</type>
```

Thoughts/opinions?

**Comment by sigsteve** [comment]
I think option 1 looks the cleanest. Could we append the provider and arch to the Vagrantfile file name? (ie: Vagrantfile.libvirt.x86_64)

**Comment by dcermak** [comment]
> I think option 1 looks the cleanest. Could we append the provider and arch to the Vagrantfile file name? (ie: Vagrantfile.libvirt.x86_64)

That's only a solution for this specific problem, you could create two different libvirt boxes from the same `config.xml` via profiles and then you wouldn't be able to provide each box with a different Vagrantfile. 

On the other hand, embedding the custom settings in `config.xml` (option 2) will not work for different arches on OBS.

So maybe we should just provide option 1 and "outsource" the logic into the `Vagrantfile` (which can execute arbitrary Ruby code, so you're not really limited a lot in there)?

**Comment by davidcassany** [comment]
I dislike the 2nd option. I don't like adding free code into the XML. In case it needs to be part of the XML I'd say we should extend the schema for `<vagrantconfig>`  section and add there the parameters the are required. The problem of that is that those parameters are provider dependent, right? So this doesn't scale on providers.

I also dislike the option 1 as it looks like adding vagrant specific obscure logic. The description itself does not include the vagrantfile reference.

> That's only a solution for this specific problem, you could create two different libvirt boxes from the same `config.xml` via profiles and then you wouldn't be able to provide each box with a different Vagrantfile.

Yes this is correct. Also I'd prefer to avoid embedding parameters in vagrantfile name.

> On the other hand, embedding the custom settings in `config.xml` (option 2) will not work for different arches on OBS.

Well this is not completely correct, profiles can be arch specific and OBS can handle profiles. Thus you could just add a profile for the specific arch with the specific vagrant file.

> So maybe we should just provide option 1 and "outsource" the logic into the `Vagrantfile` (which can execute arbitrary Ruby code, so you're not really limited a lot in there)?

Not sure how hard it can be to create some vagrant file that reacts on architecture to customize parameters, but this looks nice to me.

I have another suggestion (3rd option), similar to what @dcermak already suggested in option 1. What if we just include the vagrant file reference into the `<vagrantconfig>` element. Something like:

```xml
<type image="vmx" filesystem="ext4" format="vagrant" boottimeout="0" bootloader="grub2">
  <vagrantconfig vagrantfile="some_path_of the_host_goes_here" virtualsize="42">
  <size unit="G">42</size>
</type>
```
Then you could have multiple archs with different vagrant files using arch specific profiles. `_some_path_of_the_host_goes_here` could be an absolute path or a relative path.  If relative it reads from the project description folder.  `vagrantfile` attribute would be incompatible with the `provider` attribute, the user should not be capable to set both. If `vagrantfile` is provided obviously KIWI would not produce any vagrant file and just use the provided one without any modification and/or verification.

My doubt here, which  also applies for option 1, is if there are parameters of the KIWI description file that affects the Vagrantfile (e.g. disk size)

Any thougths?

**Comment by sigsteve** [comment]
Option 3 seems the best. The default disk information is stored in the metadata.json and shouldn't impact the Vagrantfile. With the ability to specify vagrantfile=, we should be able to handle any kiwi specific challenges that come up. We will be in a better spot than we are today with building vagrant boxes.

**Comment by dcermak** [comment]
> I have another suggestion (3rd option), similar to what @dcermak already suggested in option 1. What if we just include the vagrant file reference into the `<vagrantconfig>` element. Something like:
> 
> ```
> <type image="vmx" filesystem="ext4" format="vagrant" boottimeout="0" bootloader="grub2">
>   <vagrantconfig vagrantfile="some_path_of_the_host_goes_here" virtualsize="42">
>   <size unit="G">42</size>
> </type>
> ```
> 
> Then you could have multiple archs with different vagrant files using arch specific profiles. `_some_path_of_the_host_goes_here` could be an absolute path or a relative path. If relative it reads from the project description folder. `vagrantfile` attribute would be incompatible with the `provider` attribute, the user should not be capable to set both. If `vagrantfile` is provided obviously KIWI would not produce any vagrant file and just use the provided one without any modification and/or verification.
> 
> My doubt here, which also applies for option 1, is if there are parameters of the KIWI description file that affects the Vagrantfile (e.g. disk size)
> 
> Any thougths?

I like this idea except for one detail: it shouldn't be mutually exclusive with `provider` in `<vagrantconfig>`. The problem is that we **need** to know which provider the user wants to build the correct format (a libvirt box is completely different from a Virtualbox box).

If there's no objections from @schaefi and @davidcassany, then I'll implement a draft.

**Comment by davidcassany** [comment]
> I like this idea except for one detail: it shouldn't be mutually exclusive with `provider` in `<vagrantconfig>`. The problem is that we **need** to know which provider the user wants to build the correct format (a libvirt box is completely different from a Virtualbox box).

Damn this sort of stuff is what I was afraid off... What happens when `provider` defined in `<vagrantconfig>` does not match the `provider` defined in `Vagrantfile`? I can imagine my self doing so in a copy & paste process from some reference project... But probably this is something we can live with.

> If there's no objections from @schaefi and @davidcassany, then I'll implement a draft.

No objections from my side.

**Comment by dcermak** [comment]
> Damn this sort of stuff is what I was afraid off... What happens when `provider` defined in `<vagrantconfig>` does not match the `provider` defined in `Vagrantfile`? I can imagine my self doing so in a copy & paste process from some reference project... But probably this is something we can live with.

You don't have to define a provider in the `Vagrantfile` at all. The `Vagrantfile` that we ship with Virtualbox vagrant boxes have absolutely no provider specific settings. The libvirt boxes do, but vagrant will *probably* just ignore them if they appeared in a Virtualbox box.

I'd mark this feature as "**caution** use at your own risk and if you provide an invalid Vagrantfile your box won't boot, will eat your dog, etc.pp.".

> 
> > If there's no objections from @schaefi and @davidcassany, then I'll implement a draft.
> 
> No objections from my side.

:+1:

**Comment by schaefi** [comment]
I like option 3 best. The other two are imho off the table for reasons that has been already discussed.
I think the risk that the contents of the referenced Vagrantfile does not match the configured provider is something we can live with. The author of the image description that does the vagrant setup will most likely be aware of this.

So no objections from my side to add a vagrantfile attribute to the vagrantconfig section

:+1:
