### ISSUE TITLE
[kiwi] OBS KIWI dont work on Fedora 29 / 30 and CentOS 7

### ISSUE THREAD

**Issue by mmohring** [SUSE/kiwi#1124]
## Problem description

If OBS calls KIWI for Fedora 29 & Fedora 30 targets, image builds fail

## Expected behaviour

Since Fedora 27 & 28 work, 29 & 30 should also work ?

## Steps to reproduce the behaviour

1. build kiwi 9.17.41 for Fedora 27, 28, 29, 30
2. install those kiwi pages via prjconf
3. let OBS run you kiwi build target

## OS and Software information
+ KIWI version: 9.17.41
+ Fedora 27, 28, 29, 30
+ OBS version: git master as deployed in build.opensuse.org

**Comment by mmohring** [comment]
Looks like Fedora 29 or newer have moved /usr/bin/python, needed by createrepo, moved to a separate package python-unversioned-command.

**Comment by mmohring** [comment]
Looks like the CentOS problem is different:  expansion error "dnf needed by python2-kiwi, nothing provides xorriso needed by python2-kiw" . But xorriso and dnf are not existing for CentOS 7, are they ?

**Comment by mmohring** [comment]
Related to #1036. createrepo also affected by python2 drop.

**Comment by Conan-Kudo** [comment]
kiwi itself doesn't use `createrepo`/`createrepo_c`. That's an OBS issue.

Fedora 29 and Fedora 30 have a `createrepo_c` update that replaces `createrepo`, but OBS may be ignoring this.

As for CentOS 7, you need to add `Fedora:EPEL:7/standard` for `xorriso` and `CentOS:CentOS-7/extras` for `dnf`.

You can see an example here: https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86/test-image-centos

**Comment by mmohring** [comment]
system-packages:kiwi-image seems to be a predefined dependency inside the build script. It expands to 'kiwi', 'createrepo', 'tar'. So if I substitute it to createrepo_c and tat it works. So this is a build script issue. @schaefi so this needs a fix in the build script, right ? I work around with this substitute...

**Comment by schaefi** [comment]
That was an issue of obs and Adrian fixed it after we talked on the phone. I have a Fedora30 integration test build here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_arm/test-image-fedora

It's for arm but you can use the same setup for the other archs as well

**Comment by mmohring** [comment]
> That was an issue of obs and Adrian fixed it after we talked on the phone. I have a Fedora30 integration test build here:
> 
>     * https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_arm/test-image-fedora
> 
> 
> It's for arm but you can use the same setup for the other archs as well

@schaefi, @adrianschroeter  Can you explain ? I had to remove the createrepo dependency by hand. No package or config file added it. So what is the solution ? I dont see any fix in the OBS or Build Script code. Of course did I get of it working after createrepo got substituted by createrepo_c. Then the builds do work. I now use createrepo_c for all newer targets supporting createrepo_c. But my question was what is the "official way" to do this.

**Comment by mmohring** [comment]
Also, osc seems to have own code to handle repository creation by createrepo and friends. This might be another source of some hardcoding.

**Comment by adrianschroeter** [comment]
we adpated the fileprovides for /usr/bin/python

the createrepo package changed via maintenance updates on fedora, made this a bit tricky, but the solution should be always correct now.
