### ISSUE TITLE
Be more specific than using Exception

### ISSUE THREAD

**Issue by tomschr** [SUSE/kiwi#12]
Most of your code contains exception handling which is a good idea as it supports [EAFP (Easier to Ask for Forgiveness than Permission)](https://docs.python.org/3/glossary.html#term-eafp).

However, you code contains lots of check for `Exception` which is, well, a dangerous idea. ;) I guess this is done because it's a new project.

Let me explain why it's dangerous with the following code:

```python
def foo(**kwargs):
   try:
      x = kwargs["x"]
      y = kwargs["y"]
      return x + y
   except Exception as err:
     print("Something bad happen! :-(")

# Example 1:
foo(x=1, y=5)
# -> will return 6

# Example 2:
foo(x='2', y='5')
# -> will return '25'

# Example 3:
foo(x='3', y=6)
# -> Something bad happen! :-(

# Example 4:
foo(a=2, y=10)
# -> Something bad happen! :-(
```

As you can see, due to Python's duck typing capabilities, example 1 and 2 works just out of the box. It's because of the plus operator is implemented for both types. However, the other examples fail with very different reasons:

* Example 3 fails, because `x` and `y` has different types and you can't add an integer with a string. You would get this error message:

   ```
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

* Example 4 fails, because `x` is missing in the `kwargs` dictionary. You would get this error message:

   ```
KeyError: 'x'
```

The examples above show, if you use the very general class `Exception` you will catch **all** errors regardless if it has something to do with your code. This mask errors which would be raised if you would use a more specific exception.

The solution to the above code would be to use one of the specific [hierarchy of exception classes](https://docs.python.org/3.4/library/exceptions.html). Depending on what you are expect in your code, you could catch the `KeyError` exception. If that's not enough, write your own exception class and derive it from `Exception` (or something else).

I would recommend to check for specific exceptions only. Don't be too general as that leads to errors which are *really* hard to debug. Let other exceptions bubble up and deal with them in other places appropriately. That way, if something goes wrong it will be displayed. Or, as Python says it in the `this` module:

    Errors should never pass silently.

:-))

**Comment by schaefi** [comment]
I agree completely :)

Let me explain how the exceptions are handled:

1. if you find a place in the code which really handles an "Exception as e" without classifying it, I
    agree to what you have said and it must be fixed.

2. However I choose to pass along any Exception by raising a classified exception of type KiwiError
    You can see this if you look at kiwi/exceptions.py. Therefore in the code you should see things
    like

    ```
    except Exception as e:
            raise KiwiBootStrapPhaseFailed(
                'Bootstrap package installation failed: %s' % format(e)
            )
    ```

    but never something like

    ```
    except Exception as e:
         print('Something bad happened without passing e')
    ```

3. The main entry point of the application receives all exceptions and checks them as follows:

    ```
    try:
        App()
    except KiwiError as e:
        # known exception, log information and exit
        logger.log.error('%s: %s', type(e).__name__, format(e))
        sys.exit(1)
    except KeyboardInterrupt:
        logger.log.error('kiwi aborted by keyboard interrupt')
        sys.exit(1)
    except docopt.DocoptExit:
        # exception caught by docopt, results in usage message
        raise
    except SystemExit:
        # user exception, program aborted by user
        sys.exit(1)
    except Exception:
        # exception we did no expect, show python backtrace
        logger.log.error('Unexpected error:')
        raise
    ```

    So any Exception which is not a KiwiError is unknown and should not happen

I think it's ok to generically catch for a set of exceptions which could potentially happen at a certain place if the full classification of the exceptions is passed along and makes it clear to the user what the problem is

I agree completely hiding the real cause is a pita, but I really tried not to do so

Let me know if this makes sense :)

Thanks

**Comment by tomschr** [comment]
> I agree completely :)

Hehe, thanks. :+1: 

I agree with all of your points. Mostly I was focusing on point 1.

I was mostly skipping through the source code and found some spots with only Exception were raised. That is usually something when my Python alarm bells starts ringing. :bell: :grinning: 

Feel free to close it if you already aware of it.

**Comment by schaefi** [comment]
ok :grinning: 

It's good when alarm bells ring before the ship sinks, please continue to do so :grinning:
