### ISSUE TITLE
partition activation (sfdisk) fails with util-linux => 2.26

### ISSUE THREAD

**Issue by jloeser** [SUSE/kiwi#129]
## Problem description

sfdisk changed '--activate<[=device]>' parameter to '--activate <dev>' in util-linux 2.26

[  188s] [ DEBUG   ]: 09:20:01 | EXEC: [sfdisk --activate=1 /dev/loop0]
[  188s] [ DEBUG   ]: 09:20:01 | EXEC: Failed with stderr: sfdisk: option '--activate' doesn't allow an argument

**Comment by davidcassany** [comment]
@jloeser  Thanks for posting it. It definitely needs to be fixed. 
@schaefi One option would be to react on sfdisk version like we did with the tar command. However I am no really sure it is the best solution. Do you have any other thoughts?

**Comment by schaefi** [comment]
Uhm, why are they changing this in such an incompatible way :-1:  causing only pain on our side

yes must be fixed

**Comment by schaefi** [comment]
From sfdisk manual page (util-linux 2.25-15.2)

```
             This option takes an optional argument.  When no option argument
              is given, the command will list the  partitions  that  have  the
              bootable  flag set for the device specified as command argument.
              For example:

                  % sfdisk --activate /dev/sda

              When a device name is given as option argument,  the  partitions
              specified  as  command  argument  will  have  the  bootable flag
              switched on.  Other partitions for the same device will have the
              bootable  flag cleared.  For example, with the following command
              the partitions 1 and 4 are set to be bootable, while 2 and 3 are
              cleared:

                  % sfdisk --activate=/dev/sda 1 4

              If  only a single partition needs to be activated, then the par-
              tition number must be given as option argument, and  the  device
              as command argument.  For example:

                  % sfdisk --activate=1 /dev/sda

              The  activate  option is turned by default on when the program's
              invocation name is activate.
```

So my question would be what exactly has changed ?

**Comment by schaefi** [comment]
We can switch to fdisk and toggle the active flag as follows

```
fdisk /dev/disk
a
<partition number>
w
q
```

the 'a' command toggles the active flag. sfdisk was nicer because I could explicitly say 'activate'
However in the kiwi environment we know that the initial table has the active flag not set at that time, therefore a state toggle will set the active flag

Other more stable solutions are welcome

I'm still puzzled why it's possible to incompatible change core utility command options
