### ISSUE TITLE
Builds with vmconfig-entries produce invalid VMX files

### ISSUE THREAD

**Issue by novasbc** [SUSE/kiwi#130]
It appears that newlines are not created in the VMX if you have more than one entry, which fails to parse properly by ovftool later, to create an OVF.

`#!/usr/bin/env vmware
# kiwi generated VMware settings file
config.version = "8"
tools.syncTime = "true"
uuid.action = "create"
virtualHW.version = "9"
displayName = "enterprise_lexington"
guestOS = "centos7-64"
priority.grabbed = "normal"
priority.ungrabbed = "normal"
powerType.powerOff = "soft"
powerType.powerOn  = "soft"
powerType.suspend  = "soft"
powerType.reset    = "soft"
memsize = "8192"
ide0:0.present = "true"
ide0:0.fileName= "/home/jenkins/jenkins_slave_builds_prod/workspace/enterprise_lexington_appliance/appliance/target/output/vmx/ovf/enterprise_lexington.x86_64-0.0.1.vmdk"
ide0:0.redo = ""
ethernet0.present = "true"
ethernet0.allow64bitVmxnet = "true"
ethernet0.addressType = "generated"
ethernet0.virtualDev = "e1000"
ethernet0.connectionType = "bridged"
usb.present = "true"
**numvcpus = "4"cpuid.coresPerSocket = "2"**`

**Comment by davidcassany** [comment]
Looks like we missed to add the line separator, let me verify it. If so it should be easy to solve it.
