### ISSUE TITLE
rpm-excludedocs handling missing

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#133]
## Problem description

The XML setup for rpm-excludedocs is not taken into account by the code

## Actual behaviour

package installation happens without docs excluded

**Comment by schaefi** [comment]
for zypper the following needs to be done in zypp.conf

```
[main]

rpm.install.excludedocs = yes
```

Also see https://doc.opensuse.org/projects/libzypp/HEAD/group__ZyppConfig.html

**Comment by schaefi** [comment]
yum and apt seems to not have an option to exclude the installation of package documentation. However that needs investigation to be sure about

**Comment by davidcassany** [comment]
@schaefi It can be done with both.

For apt it can be achieved by setting the path-include and path-exclude options of dpkg, i.e:
```
# Delete man pages
path-exclude=/usr/share/man/*

# Delete docs
path-exclude=/usr/share/doc/*
path-include=/usr/share/doc/*/copyright
```
This can be added to dpkg.cfg and then target the custom conf file with the environment variable DPKG_CONFFILE_NEW. Another option would be to use the apt.conf file which can also include DPKG options in syntax like:

```
Dpkg::Options {
   "--path-exclude=/usr/share/doc/*";
   "--path-include=/usr/share/doc/*/copyright";
}
```

For yum it can be achieved via the  `~/.rpmmacros` file, theoretically it is enough to append `%_excludedocs 1`. The problem in yum is that I could not find any where how to target custom `.rpmmacros` file. Having rpmmacros located in $HOME is problematic for kiwi, we should not modify $HOME content in the underlying platform neither in the image image.

**Comment by schaefi** [comment]
Sorry my fault, this should stay open.

@davidcassany I'll investigate the ZYPP_CONF problem you pointed out

**Comment by davidcassany** [comment]
@schaefi no problem, why should you keep it open if already merged? :smile:   

About ZYPP_CONF, I still see data in /usr/share/man/man1 if I do not include something like
```
chroot_env = dict(self.command_env)
chroot_env['ZYPP_CONF'] = self.root_bind.move_to_root(
    [self.command_env['ZYPP_CONF']]
)[0]
```
in kiwi/package_manager/zypper.py. Because of that I also ended up adding a new method in root_bind in order to move_to_root a single path and not having to create a list to modify a single value of a dict.

**Comment by schaefi** [comment]
because we fixed this only for zypper, but the issue should also be fixed for yum and apt. So what I merged was only a part of the story

**Comment by schaefi** [comment]
Thanks for pointing out the command_env path problem. I have a patch and testing it currently. Sorry that I have ripped out that part from your initial implementation, my bad

**Comment by davidcassany** [comment]
Nevermind, my initial implementation was also wrong since I was not copying the command_env dict, but modifying it, which is also bad, as later on there were other zypper operations without chroot and they were also getting the modified ZYPP_CONF.

**Comment by schaefi** [comment]
for yum we are out of luck here. rpm supports

```
rpm -i ... --excludepath=....
```

but this option can't be passed along to rpm via yum, see the following information

* http://unix.stackexchange.com/questions/209605/how-to-pass-options-to-rpm-through-yum-cli

Therefore we are not going to implement this feature for yum. I will however let kiwi print a warning that we are not supporting it
