### ISSUE TITLE
ovf disk format missing

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#14]
The legacy version of kiwi provides an OVF writer module which is incomplete and broken in many parts of the created configuration file. Actually it should not be the task of the image builder to create the ovf metadata

There is the openovf project which seems also outdated and due to a missing upstream alternative this version of kiwi does not provide ovf support

**Comment by schaefi** [comment]
This needs further evaluation of alternatives before we can start an implementation. It should also be clear for what target systems we want to support ovf's

**Comment by Conan-Kudo** [comment]
@schaefi You might want to take a look at the [ImageFactory](https://github.com/redhat-imaging/imagefactory). It seems like it'd be able to do what you're looking for.

**Comment by schaefi** [comment]
Thanks much, I will take a look at it

**Comment by schaefi** [comment]
Hmm, sorry I could not find how ImageFactory can write an ovf configuration from a template.
Do you have an example ? KIWIOVFConfigWriter takes the information from the <machine> section and was able to write ovf container metadata for the subsystems:

* vmware
* powervm
* zvm

I'm searching for a replacement

**Comment by schaefi** [comment]
That's because I think a good ovf config writer seems to be complex enough to form its own project :smile:

**Comment by schaefi** [comment]
* vmware: provides own tools for vmdk to ovf conversion
* zvm: no use case after discussion with s390 team
* powervm: ibm has tools in powerVM

we are not going to try to add a "one can do all" in kiwi again. This failed the last time and there is still rotten code in kiwi v7 concerning ovf creation
