### ISSUE TITLE
kiwi 8 and repository priority

### ISSUE THREAD

**Issue by SantoshKumar4** [SUSE/kiwi#153]
## Problem description
Repository priority support in kiwi 8.

## Actual behaviour
 yum normally installs the latest version of a package, regardless of which repository provides it.
Kiwi has an attribute to set the priority for a given repository but rpm may get picked from lower ordered repository if it has latest version of rpm.

## Steps to reproduce the behaviour
Have 2 repositories and put latest rpm in lower ordered repository. Latest rpm will get installed in-spite of repository priority set in the reverse order. 

other information:
============
fedora documentation recommends using yum-plugin-priorities package to override the default behavior but not sure if KIWI 8 is already using it or doing this differently. Here is the link:
https://docs.fedoraproject.org/en-US/Fedora/14/html/Musicians_Guide/sect-Musicians_Guide-CCRMA_Repository_Priorities.html

============================================================
I'm aware of the prio plugin. However, the setup to make use of it is not 
implemented in kiwi at the moment. I think it would be very handy to have 
support for yum repo prios in kiwi. 

Could you open an issue on the kiwi github including the information you've 
sent here by mail ? That would be great. I think it's not a big effort 
to implement that feature 

Thanks 

Regards, 
Marcus

**Comment by schaefi** [comment]
Started to work on this one

**Comment by SantoshKumar4** [comment]
Thank you.
