### ISSUE TITLE
Build fails when image size is not set

### ISSUE THREAD

**Issue by kravciak** [SUSE/kiwi#186]
## Problem description
Element image->preferences->type->size default value is not set according to v7 documentation:
"If the size element is not used, KIWI will create an image containing approximately 30 % free space."

## Actual behaviour
Image without size element fails to build with error:
KiwiCommandError: rsync: stderr: rsync: write failed on "/tmp/kiwi_mount_manager.4qy_vkin/var/lib/rpm/Packages": No space left on device (28)

The same project builds properly in kiwi v7, but fails in v8.

## Steps to reproduce the behaviour
    <preferences>
        <version>1.1.0</version>
        <packagemanager>zypper</packagemanager>
        <bootsplash-theme>openSUSE</bootsplash-theme>
        <bootloader-theme>openSUSE</bootloader-theme>
        <rpm-excludedocs>true</rpm-excludedocs>
        <type
            image="vmx"
            filesystem="xfs"
            boot="vmxboot/suse-leap42.2"
            format="qcow2"
            vga="normal"
            boottimeout="1"
            bootloader="grub2"
            firmware="uefi"
            kernelcmdline="plymouth.enable=0 console=tty1 console=ttyS0 net.ifnames=0"
            bootpartition="false"
            bootkernel="custom"
            devicepersistency="by-label">
        
        </type>
    </preferences>

**Comment by davidcassany** [comment]
@kravciak I have already found that issue too, I have a patch on the way. The estimated image size is slightly smaller that the really needed size. I have just some little things to verify and I'll commit a fix.
