### ISSUE TITLE
Result bundle might override a hardlink that is expected to be untouched somewhere else

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#199]
## Problem description

OBS builds of multiple profiles ends up with all images (one per profile) being actually the same file, the last one being build.

## Steps to reproduce the behaviour

Run the sequence ``prepare``, ``create`` and ``bundle`` a couple of times with the same command line but different profiles. All the images in the bundle directory will actually be the same, more concretely hard-link to the same file inside the bundle-dir, which has be overwritten by the new build.

**Comment by davidcassany** [comment]
@schaefi this could be fixed by switching the copy command line in bundle task ``result_bundle.py`` to make a regular copy instead of a hardlink. It could also be solved in ``SUSE/obs-builds/build-recipe-kiwi`` forcing to remove the ``KIWI-vmx`` after each bundle run, this way we would not overwrite any linked file. 

IMHO is a bit tricky that KIWI is capable to overwrite files that are hard-linked with the result-bundle, so a third option would be to delete the file before overwriting it, as  a method to delink it.

**Comment by schaefi** [comment]
Hmm, yet another use case of bundle which I did not thought about. For the moment I think a real copy should be the way to solve this

**Comment by davidcassany** [comment]
Right, this might not be the most optimal solution, but certainly the simplest and safest. I'll make that little change.
