### ISSUE TITLE
Makefile -> Tox (tox.ini)

### ISSUE THREAD

**Issue by tomschr** [SUSE/kiwi#2]
I think, the (most?) Pythonic way is to use [tox](https://testrun.org/tox/latest/) to build all the necessary targets.

One of the benefits is that it fits well into a virtual environment.

**Comment by schaefi** [comment]
make sense to me too. I have merged in all your former preparation patches, we should be ready for tox now. I need to update the README.md of the project to explain how to use virtual envs. I'll take your mail as data source if ok :)

**Comment by tomschr** [comment]
>  I have merged in all your former preparation patches

Thank you very much! :+1: 

> I need to update the README.md of the project to explain how to use virtual envs.

You can also have a look into our [Docmanager wiki](https://github.com/openSUSE/docmanager/wiki/Testing-DocManager) although it's based on Python 3.

>  I'll take your mail as data source if ok :)

Absolutely! :-)

**Comment by schaefi** [comment]
for reference these are the places where I still use Makefiles

./Makefile
./boot/locale/Makefile
./doc/man/Makefile
./schema/Makefile
./tools/Makefile
./tools/dcounter/Makefile
./tools/driveready/Makefile
./tools/isconsole/Makefile
./tools/kversion/Makefile
./tools/setctsid/Makefile
./tools/startshell/Makefile
./tools/utimer/Makefile

**Comment by schaefi** [comment]
I have cleaned up the Makefile mess and we are now down to two Makefiles, the master one which needs to be moved to tox and the one which builds manual pages from markdown. Regarding the man pages we will switch to Sphinx/ReST thus I leave that part as it is for the moment

**Comment by tomschr** [comment]
Great news Marcus! Thanks a lot! :+1: 

>  Regarding the man pages we will switch to Sphinx/ReST thus I leave that part as it is for the moment

Sure, I can take care and open a new PR.

**Comment by schaefi** [comment]
yep that would be nice

**Comment by tomschr** [comment]
> Regarding the man pages we will switch to Sphinx/ReST thus I leave that part as it is for the moment

This is covered now in #26 which was merged already.

As almost everything can be handled now through Tox with the changes from #26, I think we can close this issue. If you disagree or I've missed something important, just reopen it.
