### ISSUE TITLE
packages/arch: comma seperated list not working

### ISSUE THREAD

**Issue by thkukuk** [SUSE/kiwi#202]
## Problem description
https://doc.opensuse.org/projects/kiwi/doc/ states in 4.1.8.2:
"To restrict a package to a specific architecture, use the arch attribute to specify a comma separated list of allowed architectures. "
## Actual behaviour
If I use a comma separated list of architectures for a package, it will be installed on no architecture.

## Steps to reproduce the behaviour
Create an entry like "<package name="XX" arch="x86_64,aarch64". The package will not installed on any architecture.

**Comment by davidcassany** [comment]
@thkukuk you are right, this KIWI version is not parsing the comma separated list. I am on it.
