### ISSUE TITLE
Storage calculation is wrong for LVM volumes and VMX images.

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#207]
## Problem description
When creating a VMX with LVM custom partitions of specific size the virtual disk that is created to hold the system is not big enough. When creating the volumes KIWI fails due to lack of space.

## Actual behaviour
`DiskSetup.get_disksize_mbytes()` method for VMX images makes a sum of all defined volume sizes and creates a raw disk with this exact value, however there are a couple of overheads that are not taken into consideration. First, modern `fdisk` implementations assume the first partition to start at sector 2048 (1MB with 512 bytes per sector); second, LVM metadata causes an offset of one Physical Extent (4MB by default in current `lvm2` implementations). Given the fact that volumes are aligned at PEs boundaries it would be enough to include one extra PE to hold both, the `fdisk` offest and LVM metadata offset.

## Steps to reproduce the behaviour
Use a systemdisk configuration like the following in a VMX image:

```xml
<systemdisk name="vg0">
  <volume name="@root" size="4G"/>
  <volume name="LVhome" size="1G" mountpoint="home"/>
  <volume name="LVtmp" size="1G" mountpoint="tmp"/>
</systemdisk>
```

**Comment by schaefi** [comment]
I thought all of these constraints were taken into account by a minimal volume size defined in Defaults:get_min_volume_mbytes(), currently set to 30MB which should be enough to hold any kind of overhead for empty volumes

But there might be other problems causing trouble regarding pre-calculation of size constraints I constantly run into trouble

**Comment by davidcassany** [comment]
@schaefi this is only applied if `freespace` options is selected. When volumes are specified to a concrete size, the whole disk size is calculated as a sum of all volumes, see that DiskSetup:_accumulate_volume_size() only applies the 30MB in `freespace` case, when explicitly defined it just calculates the sum of everything without applying any offset.
