### ISSUE TITLE
oem install includes /dev/ram as possible target storage device 

### ISSUE THREAD

**Issue by db-at-work** [SUSE/kiwi#209]
## Problem description

think the title says it all

## Actual behaviour

dialogue shows /dev/ram[0-15] as 500MB disks that one could select as the target for the image deployment

## Steps to reproduce the behaviour

build JeOS template --type oem and attempt to install should reproduce

**Comment by db-at-work** [comment]
this is a regression - mentioned on the mailing list here:
https://groups.google.com/d/msg/kiwi-images/3-aHLIaEeps/k03i3j_6AgAJ

**Comment by davidcassany** [comment]
Are you using the `<oem-device-filter>` section within the `<oemconfig>`. This should be used to avoid certain devices to be considered as possible installation devices. You can see it in [this example](https://github.com/SUSE/kiwi-descriptions/blob/master/suse/x86_64/suse-leap-42.2-JeOS/config.xml).

**Comment by db-at-work** [comment]
right. no. saw that in an old thread on the list. thanks for the example. who would want to use /dev/ram as an install target (why do we need the filter vs having this in kiwi code)?

**Comment by schaefi** [comment]
The reason why those devices appear is that kiwi searches for all possible block device targets. In former kernel versions the brd (ramdisk driver) was a module which we loaded on demand. In current
kernels the driver is compiled in and thus the kernel always provides a series of ram disk devices which we now find.

In principal there is nothing wrong with installing the system on a ramdisk if the configuration did not tell us anything specific (device filter or device spec) it would be hard to guess why the ramdisk is unwanted

I agree most people won't have this use case

Adding the following to your setup will fix this problem

```xml
<oemconfig>                
        <oem-device-filter>/dev/ram</oem-device-filter>
</oemconfig>
```

We could think of a default filter but for the moment I'm quite uncertain if that is the right way as it really depends on the kernel and that's different on each distro and distro variant

Thoughts ?

**Comment by schaefi** [comment]
guess the above filter information was enough to deal with the reported issue
