### ISSUE TITLE
Publish man page and api documentation to github.io

### ISSUE THREAD

**Issue by tomschr** [SUSE/kiwi#21]
When Kiwi is considered as stable enough, you could think of publishing the documentation to github.io as an idea. The doc for Kiwi would then be accessible through `http://suse.github.io/kiwi`.

All the necessary steps are described in the article [Creating Project Pages manually](https://help.github.com/articles/creating-project-pages-manually/).

Probably there are methods to make it semi-automatic.

Update: I've found [`travis-sphinx`](https://github.com/syntaf/travis-sphinx) which could be useful.

**Comment by schaefi** [comment]
the kiwi docs in the source repo will only cover manual pages. Does it still make sense to have them on the suse github ? Is the suse github not replaced by a gitlab system ?

**Comment by tomschr** [comment]
Well, depends how useful you think it is. :)

For example, on my [openSUSE/rstxml2docbook](https://github.com/openSUSE/rstxml2docbook) repo, I've implemented such a system. There is also only one manpage. However, if I change something in my doc dir and create a new release, it will be automatically deployed to http://opensuse.github.io/rstxml2docbook/.

I think, it's pretty neat to have it in one place and with an up-to-date manpage. People can look at them directly or search for terms without checking it out and building it manually. Plus, when people ask you question, you can redirect them to the manpage (if it is explained there).

The SUSE Gitlab is just a private space. Not sure what it has to do with this idea.

**Comment by schaefi** [comment]
> The SUSE Gitlab is just a private space. Not sure what it has to do with this idea.

I was on the wrong page, forget it

> owever, if I change something in my doc dir and create a new release, it will be automatically
> deployed to http://opensuse.github.io/rstxml2docbook/.

That sounds cool. I think once kiwi is publicly available and the man pages are good enough I will make use of it. At the moment I think it would be strange to have public man pages without an application :smile:

**Comment by tomschr** [comment]
> That sounds cool.

It is. It's quite easy to set up. I've submitted Syntaf/travis-sphinx#4 and suggested to build in other branches than master.

> At the moment I think it would be strange to have public man pages without an application 

Absolutely. It's something for the future you can implement.

**Comment by schaefi** [comment]
Ok I plan for the first release soon and would like to have the man and api documentation online as you suggested. The 'make html' sphinx target is working well and I think I'd like to get in touch with you for the details next week

@tomschr would you have a minute for me on Monday ?

**Comment by tomschr** [comment]
@schaefi This is great! I'm not in the office today (Monday), but we can look into this tomorrow (Tuesday). :smiley:

**Comment by schaefi** [comment]
Thanks, I have started the work. You can see the result here

https://suse.github.io/kiwi

I have updated the travis setup to call travis-sphinx deploy any time a pull request or push to master happens.

I think the main index.rst should provide a bit more information :smile: Let's discuss when you are back. Thanks much

**Comment by schaefi** [comment]
Updated index main page to provide an introduction

Also included the travis-sphinx calls into tox targets

**Comment by schaefi** [comment]
all done :smile:
