### ISSUE TITLE
Set kiwidebug=1 for recovery partition

### ISSUE THREAD

**Issue by permeable** [SUSE/kiwi#213]
## Problem description

 How can I configure kiwi to add kiwidebug=1 to the grub boot
  configuration for my recovery/restore partition?

  If I add it to the kernelcmdline in my config.xml, the string is added
  to the regular image boot config, not the recovery/restore partition.
  It would be great if kiwi could add it to both grub boot
  configurations.

**Comment by schaefi** [comment]
The value of $kiwi_cmdline has now been added to the 'Recover/Repair System' and 'Restore Factory System', thus if you set kernelcmdline="kiwidebug=1" in your XML setup it should be populated into all grub configurations
