### ISSUE TITLE
dbus uuid should be unique

### ISSUE THREAD

**Issue by jgleissner** [SUSE/kiwi#219]
## Problem description
The D-Bus UUID is supposed to be unique for any running OS instance.

## Actual behaviour
Any machine started from the image has the same UUID generated at image creation.

## Potential solution
At first boot, remove /var/lib/dbus/machine_id and run `dbus-uuiden --ensure`.

**Comment by davidcassany** [comment]
@jgleissner thanks for reporting that issue, we could easily include the command in some of the functions of the kiwi boot procedure, however that would not work when using `dracut` initrd images, as in that case there isn't any kiwi specific code executed during the first boot. 

Do you have any idea of what happens when the `/var/lib/dbus/machine_id` is not present at boot time? Would be nice to find a way that dbus itself regenerates that UUID. I'll try to make some trials around that.

**Comment by jgleissner** [comment]
Hi @davidcassany , I don't think dbus regenerates the UUID automatically. At least on openSUSE, it's done in the postinstall script.

I just noticed that on newer openSUSE installations (current Tumbleweed), /var/lib/dbus/machine_id is actually a link to /etc/machine_id. Seems reasonable to me as there shouldn't be a need for two UUIDs. The link could actually be made in config.sh without changing KIWI AFAICS.

**Comment by schaefi** [comment]
On my system its two files with identical content

```
stat /etc/machine-id
  File: '/etc/machine-id'
  Size: 33              Blocks: 8          IO Block: 4096   regular file
Device: 26h/38d Inode: 117179      Links: 1


stat /var/lib/dbus/machine-id 
  File: '/var/lib/dbus/machine-id'
  Size: 33              Blocks: 8          IO Block: 4096   regular file
Device: 26h/38d Inode: 115952      Links: 1
```

I'm about to fix this but I'm uncertain what is the right way ?

in kiwi we have setupMachineID function which just calls systemd-machine-id-setup
I would now just create a hardlink from that file and be done

Thoughts ?

**Comment by schaefi** [comment]
config.sh ist not the right place because the kiwi boot code (if used) creates the machine id on first boot one time. So this needs to be fixed in the kiwi boot code

**Comment by jgleissner** [comment]
If /var/lib/dbus/machine_id was a symlink to /etc/machine_id, it wouldn't need to be created on first boot. It wouldn't work with a hard link though. A hard link would also fail if /etc and /var are not on the same fs.

**Comment by schaefi** [comment]
right, so lets go with a symlink
