### ISSUE TITLE
unique /etc/machine_id for kiwi7

### ISSUE THREAD

**Issue by jgleissner** [SUSE/kiwi#224]
## Problem description
Appliances come up with the same machine ID (the one generated when the images was built), which should actually be unique per machine (virtual or not). This was fixed for kiwi8 (issue #169). It would be helpful to have that in kiwi7 too. See also related issue unique dbus uuid (issue #219).

**Comment by schaefi** [comment]
Thanks, could you move this issue to the kiwi (v7) git repo here:

* https://github.com/openSUSE/kiwi/issues

Thanks

**Comment by jgleissner** [comment]
Oh, sorry. Reopened here: https://github.com/openSUSE/kiwi/issues/624

**Comment by schaefi** [comment]
Thanks, closing here :)
