### ISSUE TITLE
isolinux: boottimeout ignored

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#228]
After rebuilding openSUSE Krypton (https://build.opensuse.org/package/view_file/KDE:Medias/openSUSE-Krypton/plasma5-unstable-live.kiwi?expand=1) with KIWI 8, the resulting image only shows the boot menu for roughly half a second. This was around 10 seconds with KIWI 7.

Additionally, specifying ```boottimeout="10"``` does not have any effect.

See also https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2356

**Comment by schaefi** [comment]
Thanks for the report, I'm looking into the issue

**Comment by schaefi** [comment]
Ah I see isolinux counts in units of 1/10 seconds.

**Comment by okurz** [comment]
@Vogtinator I assume you will track this and see for a rebuild of openSUSE Krypton when new kiwi is available?

**Comment by Vogtinator** [comment]
@okurz I already added boottimeout="500" as a workaround an hour ago, I just need to remember to change it back again sometime...

**Comment by schaefi** [comment]
I have fixed it and submitted a new package, the rest happens automatically but will take some time
