### ISSUE TITLE
Idea: Use more Subpackages

### ISSUE THREAD

**Issue by tomschr** [SUSE/kiwi#23]
Again just one of my crazy ideas. :grin:  To be honest, I'm not 100% sure if this is really a good idea, so treat it as non-important and something for the future. Feel free to close it. :smile:

The basic idea is to use more (sub)packages. Packages in Python are directories which contains a `__init__.py` file.

For example, you have lots of `filesystem_*.py` files. The same applies to `bootloader*.py`, `container*.py`, and others. For me, that cries for refactoring it into (sub)packages. 

Let's assume for the moment, the idea has any value and we want to refactor all the `filesystem*.py` files. In that case, we could do this:

1. Create the directory `filesystems` (or use the singular form, doesn't matter for the time being).
2. Move `filesystem.py` to `filesystems/__init__.py` (or better leave `__init__.py` empty and use a different name).
3. Move the other `filesystem_<NAME>.py` files to `filesystems/<NAME>.py`.

There you have it, a `filesystems` (sub)package!  :-)

What do we gain?

* The `kiwi` directory doesn't look so crowded after the restructuring.
* Maybe a little bit easier to type ("Readability counts"¹).
* Creates a `filesystems` "namespace" instead of packing everything into a file ("Namespaces are one honking great idea -- let's do more of those!"¹)
* No special file naming schema is needed, just add everything under `filesystems` and you're done.
* Probably easier to collect all the relevant files under the `filesystems` directory (think of a plugin systems).
* Easier to extend.

¹ cited from `import this`

Disadvantages:
* All(?) tests need to be examined and probably rewritten
* Problem with circular dependencies? I don't know.
* Other things...?

Ok, that's all. ;-)

**Comment by schaefi** [comment]
yes it has grown, I think that makes sense

With regards to the plugin system, kiwi already has that with the on demand loading of the _task classes. That having said it would make sense to structure this the way you suggested

**Comment by tomschr** [comment]
> With regards to the plugin system, kiwi already has that with the on demand loading of the _task classes.

Cool, great! :+1: 

I don't consider it as super-important. Maybe something when you refactor your code anyway.

**Comment by tomschr** [comment]
Just a small addition. The `container*` and `system*` files could probably refactored as well.
