### ISSUE TITLE
Allow to skip bootloader configuration and installation

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#235]
## Problem description

kiwi supports custom bootloader setup and installation via the editbootconfig and editbootinstall script hooks. However even if those are specified a bootloader setup and installation takes place which requires the user to device for some bootloader. KIWI should allow to skip its own bootloader code by allowing:

```xml
<type .... bootloader="custom"/>
```

## Current behaviour

bootloader config and installation can't be skipped

**Comment by schaefi** [comment]
NOTE: editbootconfig and edtibootinstall scripts must _not_ be skipped

**Comment by agraf** [comment]
Dirk mentioned that bootloader="custom" is probably a better name

**Comment by schaefi** [comment]
good point
