### ISSUE TITLE
Add ability to filter network interfaces used by kiwi PXE installer.

### ISSUE THREAD

**Issue by permeable** [SUSE/kiwi#245]
We have an appliance that for historical reasons, has eight (8) network interfaces.  The appliance is deployed in data-centers that require connectivity between several independent networks.

When I PXE install this appliance, kiwi waits for all eight network interfaces to come up, even though the PXE server is only available on a single interface, eth5.  It takes about eight minutes for this step to complete.

It would be a great enhancement to have a way to define for kiwi the PXE network interface: 

`<oem-nic-filter>eth1|eth2|eth3|eth4|eth6|eth7</oem-nic-filter>`

**Comment by schaefi** [comment]
Looking into this one now

**Comment by schaefi** [comment]
@permeable Hi, I appreciate your review on #279 

Thanks

**Comment by permeable** [comment]
This implementation filters _in_ which is different then the existing \<oem-device-filter> in v7 which filters _out_.  Does \<oem-device-filter> in this version filter _out_?  \<oem-nic-filter> and \<oem-device-filter> should have similar behavior.

**Comment by schaefi** [comment]
Agreed, I have update the pull request, how about it now ?
