### ISSUE TITLE
Support dracut generic initrd as alternative to kiwi initrd

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#25]
At the moment only a kiwi initrd can be used to drive the very first boot. The kiwi initrd contains a lot of features which are e.g not required to boot a simple cloud instance. For this purpose it would be nice to
add a BootImageDracut class which uses a dracut generic initrd

**Comment by Conan-Kudo** [comment]
@schaefi Why can't a dracut initrd drive the whole thing in normal cases?

**Comment by schaefi** [comment]
the kiwi initrd supports e.g:

* recovery / restore
* split systems
* oem pxe deployment
* oem iso deployment (install iso)
* oem custom disk resize (similar to what cloud-init does but flexible/configurable)
* ...and more

There is a lot outside of the scope of dracut depending on the image type you build with kiwi.
Therefore it is nice to have both in place to cover all use cases

**Comment by schaefi** [comment]
Support for dracut initrd has now been added

you can specify

```
<type .... initrd_system="kiwi|dracut"/>
```
