### ISSUE TITLE
Kiwi doesn't respect patternType="plusRecommended"

### ISSUE THREAD

**Issue by mkrawiec** [SUSE/kiwi#285]
## Problem description
I marked packages section with `patternType="plusRecommended"` what I would expect to happen is that Kiwi installs pattern-related recommends while still ignoring package-related recommends. 

## Additional info
Zypper backend

## Actual behaviour
Kiwi ignores `plusRecommended` and installs only required pattern packages.

## Steps to reproduce the behaviour

1. Create pattern package spec file with a few `Recommends:`
2. Mark `<packages type="image" patternType="plusRecommended">`
3. Build

**Comment by schaefi** [comment]
Hmm, can't reproduce this so far, could you attach the build log file and the version of kiwi you used to build ? Thanks

**Comment by mkrawiec** [comment]
Maybe my setup is not correct then. The [build log](https://github.com/SUSE/kiwi/files/907386/image-root.log.txt) clearly indicates kiwi knows what to do: 

    INFO: --> collection type: plusRecommended

My config looks like this:
```xml
    <packages type="image" patternType="plusRecommended">
        <!-- ... -->
        <namedCollection name="gekon_yast"/>
        <!-- ^^ The pattern in question ^^ -->
    </packages>
    <packages type="image" profiles="gnome">
        <!-- ... -->
    </packages>
```
And I've created a pattern like this:

```
# ...
Provides:       pattern() = gekon_yast
Provides:       pattern-icon() = yast-misc
Provides:       pattern-order() = 1140

Recommends: yast2-control-center-qt
Requires: libyui-qt7
Requires: libyui-qt-pkg7
Recommends: yast2-firewall
Recommends: yast2-fonts
Recommends: yast2-country
Recommends: yast2-users
Recommends: yast2-sudo
Recommends: yast2-bootloader
# ...
```

Still no yast2 packages got installed as you see in the build log. `libyui` packages marked as Required were indeed installed

**Comment by davidcassany** [comment]
@mkrawiec you are right, plus recommended it is not taken into account in some cases. I think I already found the issue, I am working on a patch.
