### ISSUE TITLE
yum repo, dnf repo and apt repo-files are deleted in image if imageinclude=true is used

### ISSUE THREAD

**Issue by msrex** [SUSE/kiwi#304]
## Problem description

This happens only when using yum, dnf or apt as repo-type (basically everybody besides zypper I guess...).

If you include any repo and mark it with imageinclude=true, all default repos in `/etc/yum.repos.d/` and `/etc/apt-get/sources-list.d/` are deleted. This includes the main repo and the updates repo etc. - the only one remaining is the repo marked with imageinclude=true.

**THIS IS SERIOUSLY NOT GOOD!**

It is especially bad as Fedora/RHEL/Centos include their repo-definition files as a file inside an rpm (check the contents package `epel-release.rpm`). That leads to package verification failures as the repo definition has changed or is missing. Also some rpms contain more than one repo (e.g. the Centos main repo-definition rpm). In the middle of #303 @Conan-Kudo explains a bit more.

Actually this issue only came to light after fixing #303 - before then the repo-definitions in the wrong place were deleted so all appeared fine.

The different behaviour of `yum`/`dnf` and `zypper` is that `yum`/`dnf` simply overwrite any existing repo whereas `zypper` complains, hence we are very aggressive in deleting all repos (class `SystemSetup` function `import_repositories_marked_as_imageinclude`).

Looking at `RepositoryZypper` and the `addrepo`-function this deletion seems to be unnecessary as it removes an existing file there anyways, if `zypper` is used. For the other package managers the deletion is not needed as they don't complain.

## Actual behaviour

See above.

## Reproduction
-  set up a Kiwi builder with v9.4.11 WITHOUT applying #303
1. create an image (Centos in this example) with @schaefi 's JeOS definition
2. go in the image-root (no need to boot) and check the files in `/etc/yum.repos.d`. Those files are the definitions for binary, update and a few other repos
3. if you want to go fancy verify them with `rpm -V centos-release` (chroot!)

- Now apply #303 and repeat. You will still see all files there as long as you have no repos marked with `imageinclude="true"`

- Next use a Kiwi builder **without** #303
1. change @schaefi 's Centos JeOS definition and give any repo the flag `imageinclude="true"` and build
2. go into the image-root and check that the files in `/etc/yum.repos.d` are still there. Also you will now find a `.repo` file with the contents you marked as `imageinclude="true"` in `/etc/yum/repos.d` (the wrong location per #303!).

- Finally apply #303 again
1. build the JeOS from above with a repo having the flag `imageinclude="true"`
2. go into the image-root and discover to your horror that `/etc/yum.repos.d` is empty except for the one repo-file that you specified
3. be fancy in your horror and verify the rpm with `rpm -V centos-release`

**Comment by davidcassany** [comment]
@msrex, thanks so much for such an elaborated and detailed issue report, it helps a lot. 

Deleting any defined repository in the image if `imageinclude` is used is design decision, we want to make sure that **only** those repositories with `imageinclude` flag are included in the resulting image. It also caused some issues in zypper in the past (see #178 and #182), but even though, the design principle is still valid, in the sense that we should make sure no other repos apart from the ones that have this flag enabled should be present in the resulting image. Obviously, as you noted, if some repositories are included as a package (or as part of a package), this might lead to some inconsistencies, in that case I guess we should not use `imageinclude`, as the distribution has its own parallel mechanism to achieve the same via packages. Maybe we could include some warning for yum if `imageinclude` is used. Any further thoughts?

About #303 and the repository locations, this needs to be addressed, thanks for testing and reporting it.

**Comment by msrex** [comment]
@davidcassany I think the different philosophies of the distributions warrant different behaviour. On the one hand I understand the philosophy that only and solely the repos listed should show up, but I think the current approach is very inconsistent. If I forget/ignore the `imageinclude` on apt/yum based builds I get exactly what I want, but not on zypper. And vice-versa.

I think it is totally fair that for zypper we delete everything as that is how SUSE defines repositories. Only the ones that were included in `config.xml` are added, everything else isn't. And IIRC `config.sh` is called after the deletion so a user can add a repo there. 

For the non-zypper distros nothing should be deleted as currently there is no way to reliably add repos. And besides the ones that come with packages such as `epel` I still might want to manually add some in `config.xml` so I should not be limited to either choice which is what your warning would accomplish. Your proposal means that I can either add repos via a package (and that means that I have to create a package for every repo I want to add) or I can add them via `imageinclude`. That is not a good choice to make.

Whether #305 is the best approach I don't know but it accomplishes that on zypper/SUSE it works as designed as well as on apt/yum, if my python skills were not too rusty to understand when which purge was executed.

**Comment by msrex** [comment]
@davidcassany I had another thought. Maybe instead of a warning it would be best to have a config flag so that the user can decide. Re-reading the above it is really tough to make a policy / automated decision about what the user really wants to have happen. I for one would always want the platform's standard way of handing things preserved, but there are equally strong arguments against that. And no side is right.

So if `cleanrepositories=true` is present in `config.xml` the current behaviour continues (and this is the default), if set to `false` the broad wipe is disabled and the user has more control. In the future you could then even decide whether the default is different by platform... but that's for the future :-)

**Comment by davidcassany** [comment]
@msrex yes this is definitely an option to evaluate, as you say, is hard to find an automated decision that is functional for different distros without leading to inconsistencies. Yesterday I was also wondering if we could achieve some kind of slightly different behavior according to the package manager (we have specialized classes so it would be clean to implement), the problem of this approach is that it would be quite obscure from the user perspective to understand what is going on.

I think that would be useful to find out or list some specific use cases where KIWI is lacking support or even having an erratic behavior. I will try to find out some cases later today, you already described some. Maybe then will be easier to find out some kind of automated behavior or easier to see how it should be handled, might happen that cleaning/not cleaning repositories is not really the answer. Also I'd like to include @schaefi on the discussion, he will be back in some days.
