### ISSUE TITLE
root on btrfs

### ISSUE THREAD

**Issue by k0da** [SUSE/kiwi#31]
root on btrfs requests to have /boot on separate partition. Makes kind of sense but then /boot have btrfs, which doesn't makes sense at all.

Either btrfs shouldn't request /boot or ext[23] should be used there

**Comment by schaefi** [comment]
you can configure that

bootpartition="false"

**Comment by k0da** [comment]
Yes, but does it makes sense to keep that default?

**Comment by schaefi** [comment]
I think as long as people can build from the same image description using the legacy kiwi and the new one we should behave the same in the default handling

**Comment by k0da** [comment]
So by default bootfs is btrfs in a template. So using grub1 will fail here

**Comment by schaefi** [comment]
>    So by default bootfs is btrfs in a template. So using grub1 will fail
>    here

good point, the default here would be different from legacy kiwi because
iirc we use ext2 as boot partition default. However grub1 is completely
out of scope for kiwi v8, there is no support for it.

If you have strong feelings about the bootpartition default filesystem
you can open an issue for it
