### ISSUE TITLE
Rearrange and Restructure Quick Start

### ISSUE THREAD

**Issue by tomschr** [SUSE/kiwi#319]
## Problem description
As we all know, users don't want to read too much or too complicated stuff. Additionally, the documentation should be presented in a way, that it makes it easy to follow it. As we know, users are impatient and want results NOW.

After looking at the Quick Start, I think, it doesn't serve this idea well. IMHO. I see the following issues with the current content:

* It does not contain step-by-step instructions to guide the user.
* Although compatibility is an important topic, it isn't something a Quick Start should deal with. IMHO this is a topic which belongs to another chapter.
* The Quick Start doesn't distinguish between concepts (background information, design etc.) and procedural information (target, step-by-step instructions)
* It's not clear what the goal is.
* Too many options ("Using KIWI NG from Build Service" vs. "Using KIWI NG in a Python Project"); 

## Proposed Solution
The Quick Start should answer the following questions:

* **What is our target group?**
  Developers or users who aren't familiar with the concept yet. The are impatient and want results NOW.
* **What's the aim for the Quick Start?**
  Help the user to get a success story quickly! 😄
* **How to do it?**
  * Give users steps to guide them so they can follow them quickly.
  * Distinguish between concept and procedural information in headers by using nouns and verbs

WIth the previous ideas in mind, I would propose to rearrange and restructure the information in the Quick Start as follows (draft):

```
KIWI Quick Start: Building an Image
   1. Usage Scenario
       Lays the foundation of the topic, describes what the user will get
   2. System Requirements
       States what is required when you use this guide
   3. Basic Workflow
       Describes the concept of KIWI
   4. Installing KIWI
       Gives instructions on what the user has to do when installing KIWI.
   5. Building an Image
       Gives step-by-step instructions on what the user needs to execute
   6. Using Additional Example Appliance Descriptions
       Shows some additional usage, extending the basic usage in section 5.
```

The above structure is certainly not perfect, but it will give you a good impression. Probably it has to be shifted here and there to make it work. Maybe, we should move some content ("Basic Workflow") to a different location.

Lot of the above sections can be filled with the content we already have. The task would be to group and rearrange them accordingly to fit the proposed idea in this issue.

@davidcassany, @schaefi Comments? Thoughts? 😄

**Comment by davidcassany** [comment]
@tomschr thanks for having a look at it. 
I like your proposal, even I am not sure I fully understand it. Your suggestion is about re-arranging the `Quick Start` in order to include, according to the summary of your suggestion, the current `Basic Workflow` (or shorter version of it, I would like to keep quick start short) and a new section of `Additional Examples` (which could include the currently under discussion containers documentation), other the sections are mostly a restructure of what is already there. All other sections of the docs would be kept as they are with the exception of `Basic Workflow` which would be removed (already present in `Quick Start`). Is that right?

In that case we would have to figure out were to place or what to do with the `Basic Workflow` leftovers 😅 

I like the idea, it requires some work, but I like it.

**Comment by tomschr** [comment]
> Your suggestion is about re-arranging the Quick Start...

Yes, that's basically it. The basic idea is to make it easier for the user to get a success story fast.

> to include, according to the summary of your suggestion, the current Basic Workflow (or shorter version of it, I would like to keep quick start short)

Maybe. 😁 Depends on if we want to keep that section or not. It's purely informational, no user action involved. So I think, it isn't really necessary that a user knows about the underlying KIWI design or its workflow. At least, not at this stage and not for this Quick Start. Of course, the section should be kept, but maybe in another chapter/guide/whatever.

> All other sections of the docs would be kept as they are with the exception of Basic Workflow which would be removed (already present in Quick Start). Is that right?

Almost. 😄 For example, I wouldn't include the sections about "Compatibility" and "Using KIWI NG in a Python Project". IHMO these don't belong to a Quick Start. At least the latter.

> I like the idea, it requires some work, but I like it.

Thanks!

**Comment by davidcassany** [comment]
Right I see, having a closer look to the current `Basic Workflow` section maybe we could just remove from that section all initial part (until `Image Customization with config.sh Shell Script`) and rename that section to `Image Customization` (or something like that). Then the current start part of the `Basic Workflow` could be used as basis for `Usage Scenario` or some kind of `KIWI fundamentals` subsection in the `Quick start` (I like the idea of having a very quick overview of the kiwi projects structure in the `Quick Start` so the user knows which files to expect/create/modify).

**Comment by tomschr** [comment]
Ok, I will try to come up with something and will publish it to a branch once it's ready. If you review mine, I'll review your open PR. Deal? 😁

**Comment by davidcassany** [comment]
Yes sure! But I never intended you to work for us 😅

**Comment by tomschr** [comment]
Ok, great! 👍 Maybe I will have some questions when I rearrange that. I'll keep you in the loop.

**Comment by tomschr** [comment]
@davidcassany David, I've opened the PR #321 for you.

It's probably a bit difficult to review as there are so many changes. I've tried to be as short as possible so the user doesn't have to read too much. 😁

I've assembled the Quick Start from other parts of the KIWI documentation with my own wording. Some sentences will probably look familiar to you. However, my goal was not to copy existing documentation.

You will notice, I've removed some sections from the original documentation. This was done on purpose. I was lead by these questions:

* What does the user need to know?
* What needs the user at a certain stage?

Some level of detail is IMHO just too much and distracts from the goal to deliver a **Quick** Start Guide. As such, these section should be moved to different locations of the KIWI documentation.

Furthermore, I've added some FIXMEs and TODOs for you. Maybe you can fill the gaps. Also I'm not sure if the order of the sections is good enough. I was a bit dissatisfied with myself and tried several arrangements, but in the end, I've come up with the one that you can see in this PR. If you have better ideas, let's discuss that!

Hope this will help. Now you can dissect this PR so we can make the Quick Start even better! 😁

**Comment by schaefi** [comment]
This one is handled in #324
