### ISSUE TITLE
The name of the dracut initrd output file is different on each distro

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#325]
## Problem description

The default output file of dracut is different on any distribution and several tools of the distribution
rely on that output name format. In order to stay compatible kiwi should be able to produce the
same output name schema

* Fedora uses initramfs-*.img,
* Mageia uses initrd-*.img,
* SUSE uses initrd-*,
* Debian uses initrd.img-*

## Actual behaviour

kiwi always produce the SUSE style names which inherits to the bootloader configuration
and causes trouble when the distro toolchain is used to e.g rebuild the initrd on a kernel
update

**Comment by schaefi** [comment]
```bash
grep 'outfile="/boot/init' $(which dracut)
```

would be a way to check which schema is used

**Comment by schaefi** [comment]
The better solution would be to aim for a standard

**Comment by schaefi** [comment]
suggestions welcome how to handle this in a stable way

**Comment by Conan-Kudo** [comment]
@schaefi So Fedora's scheme is the one upstream dracut has. Fedora used to use a different scheme a long time ago, but switched to dracut's scheme. RHEL/CentOS 7 also uses dracut's scheme.

**Comment by Conan-Kudo** [comment]
@schaefi I think `grep 'outfile="/boot/init' $(which dracut)` is pretty much the only way to do it right now. :(

**Comment by msrex** [comment]
Or you make it a parameter in ``config.xml``. But I agree with @schaefi and @Conan-Kudo besides the ``grep`` there is no good way.

**Comment by schaefi** [comment]
ok, I'll work on this one and will come up with a suggestion
