### ISSUE TITLE
The "yum" binary can be named "yum-deprecated", which breaks KIWI for building with Yum

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#329]
## Problem description
In Fedora and Mageia, the `yum` binary for Yum has been renamed to `yum-deprecated`, since `yum` is now a pointer to `dnf`.

KIWI needs to test for the existence of `/usr/bin/yum-deprecated` and use it instead of `/usr/bin/yum` when Yum is the selected package manager for an image build.

## Actual behaviour
Building an image with Yum will use DNF and send the wrong options in some situations (like for turning weakdeps off), which breaks the whole thing.

## Steps to reproduce the behaviour
1. Install `dnf-yum`. (You'll need to remove yum first on openSUSE). 
2. Try to build an image with `yum` as the package manager.

**Comment by schaefi** [comment]
question is why do we want to configure yum as package manager on Fedora and Mageia when dnf is the one which should be used and is also supported by kiwi ?

I would consider yum only for systems without an alternative and I guess on such systems the yum binary is not renamed to yum-deprecated

or am I overlooking something ?

Thanks

**Comment by Conan-Kudo** [comment]
@schaefi When you want to build CentOS/RHEL images from a Fedora/Mageia host, you probably want to use yum rather than DNF. :)

**Comment by schaefi** [comment]
ah this direction, ok got it
