### ISSUE TITLE
Consider leaving compression parameters up to image-dracut

### ISSUE THREAD

**Issue by msrex** [SUSE/kiwi#335]
## Problem description
When configured to use `dracut` Kiwi creates an initrd without compression, and then compresses with fixed parameters for compression. That was required to have a seekable initrd. Newer `dracut`-based systems have presets for compression that in some cases are slightly different than the ones fixed in Kiwi. I would suggest to let `dracut` handle the compression with the system-defaults. That way each system gets exactly what it expects and the initrd is still seekable.

As I have not done PRs here I created a patch (yeah, old-style):
```diff
--- dracut.py-orig      2017-05-18 19:56:07.834178132 -0400
+++ dracut.py   2017-05-18 19:56:23.790170970 -0400
@@ -53,7 +53,7 @@
                     'dracut', '--force',
                     '--no-hostonly',
                     '--no-hostonly-cmdline',
-                    '--no-compress',
+                    '--xz',
                     os.path.basename(self.initrd_file_name),
                     kernel_details.version
                 ]
@@ -70,6 +70,4 @@
             log.info(
                 '--> xz compressing archive'
             )
-            compress = Compress(self.initrd_file_name)
-            compress.xz()
-            self.initrd_filename = compress.compressed_filename
+            self.initrd_filename = self.initrd_file_name
```

It took me a while to figure out the difference betwee initrd_file_name and initrd_filename :-)

**Comment by schaefi** [comment]
yes the variable naming is confusing, I'm going to change that and will make use of your patch :) Thanks
