### ISSUE TITLE
generalize shim support

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#337]
## Problem description

KIWI's shim support is based on the presence of the `shim-install` program which only exists for SUSE systems :( On other distributions the shim setup is done at package installation time which is imho not the right place because it puts the requirement on the package that at install time all required parts of the system are available and ready to use, which is not necessarily the case within an image build process.

The super nice solution in my eyes would be to have a generic shim-install program as a project for all distributions and no package scripts which does things they should not do. The world is unfortunately not working that way so we need a practical solution to this problem

## Actual behaviour

shim setup only works for SUSE systems

**Comment by schaefi** [comment]
Suggestion for a possible solution, inspired by PhaPharaoh_Atem

1. check presence of shim-install, if it exists use it (covers the working suse case and would
    allow for an upstream solution if there is on in the future)

2. if no shim installer exists, assume that a package has installed all relevant data to /boot/efi/EFI
    of the KIWI generated root directory. mount the efi partition and copy all EFI data into at as a
    fallback solution.

**Comment by msrex** [comment]
Your 2. above covers RHEL/CentOS and Fedora nicely. I did your approach manually in config.sh and a faking `shim-install` - it works fine.

**Comment by schaefi** [comment]
nice, thanks for the feedback, even before the actual implementation :)
