### ISSUE TITLE
Provide option --clear-cache

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#341]
## Problem description

As found for the zypper package manager, all data loaded into the cache is trusted, which means if the user changes the trust level on the image description level e.g via `rpm-check-signatures` it might still happen that a package with an unverified signature is taken from the cache

While we can't change the zypper behavior we could at least provide an option to kiwi which allows to
empty the cache to make sure all data is reloaded with the configured trust level

As this might apply to other package managers as well the option should apply to the cache of the selected package manager

**Comment by davidcassany** [comment]
@schaefi, do youhave in mind something like `kiwi system [build|prepare|create] --clear-cache ...` which clears only the cache of the provided repositories? This looks like the most clean way to do it IMHO.

**Comment by schaefi** [comment]
yep that's what I thought about
