### ISSUE TITLE
Wrong kernel version selected when different build numbers are used

### ISSUE THREAD

**Issue by msrex** [SUSE/kiwi#355]
## Problem description
An image needs custom kernel modules. They come from a different repo than the main kernel. Their build number is different, while the version is the same. Building an image with a dracut initrd the creation of the dracut initrd fails.

## Actual behaviour
A `KiwiKernelLookupError` is thrown. The kernel with the lowest build number is looked for, when in reality the one with the highest build number is the correct one.

## Steps to reproduce the behaviour
It is a CentOS 7-based build. The kernel is missing `hfs` and `hfsplus`, which are supplied by elrepo (http://iad.mirror.rackspace.com/elrepo/elrepo/el7/x86_64/) as two kmods. 
The full kernel version string: 3.10.0-514.21.1.el7.x86_64
The hfs module version string: 3.10.0-229.el7.x86_64
The hfsplus module version string: 3.10.0-327.28.2.el7.x86_64
As the kernel ABI is stable for CentOS those different build numbers are not a problem.

`/lib/modules` has this content:
```
# image-root/lib/modules # ls -1
3.10.0-229.el7.x86_64
3.10.0-327.28.2.el7.x86_64
3.10.0-514.21.1.el7.x86_64
#
```
`/boot` has this content:
```
# image-root/boot # ls
.vmlinuz-3.10.0-514.21.1.el7.x86_64.hmac
System.map-3.10.0-514.21.1.el7.x86_64
config-3.10.0-514.21.1.el7.x86_64
efi
grub
grub2
initramfs-3.10.0-514.21.1.el7.x86_64.img
initrd-plymouth.img
mbrid
symvers-3.10.0-514.21.1.el7.x86_64.gz
vmlinuz-3.10.0-514.21.1.el7.x86_64
#
```

Given that the lowest build number is picked, I suspect `_setup-kernel-names-for-lookup()` in `kiwi/system/kernel.py` simply picks the first directory in `/lib/modules` and passes that on. Better would be to try all.

**Comment by schaefi** [comment]
yes you are right, the code will take 3.10.0-229.el7.x86_64 from /lib/modules and try to search a vmlinuz-3.10.0-229 but it's vmlinuz-3.10.0-514

This needs a fix
