### ISSUE TITLE
KIWI creates invalid `.repo` files for Yum

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#357]
## Problem description
When having KIWI "include" repos into a CentOS based image, it writes out a `.repo` file in the following form:
```ini
[foo]
name = foofar
baseurl = http://host.dev/foo

```
There are two problems:

1. Yum cannot handle spaces between the key and the value
2. `enabled=1` is missing, and `gpgcheck=` setting is missing (respective to whether signatures should be checked).

This causes Yum to freak out and refuse to do any actions.

## Actual behavior
Yum throws an error about bad repo configuration and does nothing.

## Steps to reproduce the behavior
1. Use a CentOS kiwi description and add a repo and set it to be included in the image
2. Build it and boot into the image
3. Try yum install/upgrade/check-update.

**Comment by davidcassany** [comment]
Thanks for reporting it, just a side note, the **rpm-signatures-check** and **rpm-excludedocs** options are used only for build time, the repos included to the image with **imageinclude** attribute are configured mostly with all default values.

@schaefi, do you think it makes sense to also import **exlcude-docs** and **check-signatures** options to the included repositories with **imageinclude**? IMHO both behaviors would make sense, personally I think I would expect the included repository to be configured with defaults (i.e. `zypper ar <url> <alias>`), but I understand that you might also expect it to be configured with **no-recommends**, **exclude-docs** or **check-signatures** if those are used for building.

Any thoughts?

**Comment by schaefi** [comment]
I think adding the setting for check-signatures makes sense to become imported. For exclude docs I'm not so sure if users expects this to end up in their image repo setup

**Comment by davidcassany** [comment]
Yes, that's a good point, maybe these options need a differentiated behavior, I would not include exclude-docs in the resulting image, as exclude docs can be some kind of opaque feature. Someone might loose quite a lot of time trying to install and use man pages before he realizes that option is set on the packager manager configuration.

On the counter part check-signatures is quite obvious to realize if it is  activated or not.

**Comment by schaefi** [comment]
I'm looking into the space problem

**Comment by davidcassany** [comment]
Ok, I was looking into the the wrong .repo config (adding enabled and any other potential missing option).

**Comment by schaefi** [comment]
I appreciate an extra issue to discuss which repo options should be moved over to the system when imageinclude is specified. Thanks

**Comment by davidcassany** [comment]
Yes, if your patch is enough to be able to use the repo included by kiwi this is true, it should be treated as a separate issue.
