### ISSUE TITLE
Improve package/repository signature checking setup

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#358]
## Problem description

KIWI currently has only global flags for rpm signature checks, but doesn't support global repo signature checks and per-repository overriding of rpm/repo signature check behavior.

When appliance makers use a mix of repositories from different sources, this granularity matters.

For example:

* In Fedora and Mageia, *all* distribution repositories and third party repositories hosted by COPR are package signed, but all but one repository is _**not**_ repo signed. That means that the global default would be rpm sig checks on, repo sig checks off, but for one repo, repo sig checks would be switched on.
* In CentOS, the primary distribution repositories are package _and_ repo signed, but most ancillary and third party repositories are _not_ repo signed. This means the global default would be rpm sig checks on, repo sig checks off, and distribution repos would have repo sig checks switched on.
* In openSUSE/SLE, _all_ repositories are generally package and repo signed, so the global default would be rpm and repo sig checks on. In the event something is not signed, they can be switched off individually.

Without this granularity, it's impossible to provide the maximum assurance that the content sources are, in fact, secure.

This would also probably necessitate adding a field for specifying each repository's gpg public key file.

**Comment by schaefi** [comment]
I think this will lead to a change in the schema:

1. delete rpm-check-signatures from preferences
2. write an xslt stylesheet that moves rpm-check-signatures if present from preferences into repository(s)
3. allow for the following extended repository definition

```xml
<repository ... rpm-check-signatures="true" repository-check-signature="true">
    <source path="..."/>
</repository>
```

The handling of the attributes might be different compared to the used package manager.
e.g in zypper rpm signature check can imho be only enabled for all repos or none. I also
think in zypper repo signatures checking is always enabled and the repo will just be accepted
in non-interactive mode which can't be configured.

In such or similar situation we would use the signature checking as available and print a message
explaining the behavior

Thoughts ?

**Comment by davidcassany** [comment]
The suggestion looks fine for me, just a very minor comment, maybe I would change those attributes to something shorter, something like: `package_gpgcheck` and `repository_gpgcheck`; which is also close to the terms used in package manager config files.

I have just tested and zypper supports per repo gpgchecks. Not sure about Apt, which handles gpg keys in a quite different way and, moreover, the debootstrap requires a keyring not individual keys, but anyway this are apt specific issues.

**Comment by schaefi** [comment]
I'm fine with short names :) if the signatures are always gpg keys that's good naming. I have adapted the example above

> I have just tested and zypper supports per repo gpgchecks. 

great thanks for the update

**Comment by Conan-Kudo** [comment]
Zypper supports `gpgcheck`, `pkg_gpgcheck`, and `repo_gpgcheck` on per repo basis, just like Yum and DNF do.

**Comment by Conan-Kudo** [comment]
@schaefi We also are missing an attribute to specify the GPG public key to import for each repo.

We also probably want to copy the GPG public key into the image `/etc/pki/rpm-gpg/` for RH/Fedora/Mageia, and whatever the equivalent path is on SUSE systems so that in case they need to be validated later, they exist somewhere...

That also means that the `gpgkey=` value in the .repo files installed in the image should be filled in with the path to the key, so that verification can continue.

**Comment by Conan-Kudo** [comment]
I'd also suggest that global values are still useful, as if things are *mostly* one or the other, it's handy to not have to specify them every time...

**Comment by davidcassany** [comment]
> I'd also suggest that global values are still useful, as if things are mostly one or the other, it's handy to not have to specify them every time...

Yes that could be handy in some cases, but in my opinion I would prefer to have only a single way to handle signatures in XML, that would make the XML file and the KIWI code cleaner imho. For zypper, yum and dnf, we could state that the global values affect the package manager config file and the specific repository values would only affect the specific .repo file. I am not a fan of that option because different package mangers could behave differently when having overlapped global and specific configurations.

**Comment by Conan-Kudo** [comment]
Well, all three of those package managers behave exactly the same way when it comes to gpgcheck flag behavior (in terms of main config -> override). The main difference is that `pkg_gpgcheck` isn't split out from `gpgcheck` in yum/dnf, though it certainly doesn't hurt to set it (since it ignores unknown values).

**Comment by davidcassany** [comment]
@Conan-Kudo Finally I started implementing your suggestion of keeping global and repo specific flags 😄. So, the `rpm-check-signatures` is still present and applies the configuration at a package manager level (sets `gpgcheck` option for zypper, dnf and yum). Then, if `repository_gpgcheck` or `package_gpgcheck` attributes are **not** set, there is no value included in the repo file (then inherits whatever is set at package manager level), on the counterpart, if `repository_gpgcheck` or `package_gpgcheck` attributes are set, the corresponding **true** or **false** value is included into the repo configuration.

@schaefi, I think @Conan-Kudo got a point here (even did not see it at begining) as it provides full package manager (and repo) control and also it lets treat it as an additional feature (thus no xslt conversion is needed), not an update as it was there.

Going to make  PR now, so we can discuss any thoughts over the code.

**Comment by schaefi** [comment]
ok let's keep the system wide signature check option, but we should make sure to update the schema inline documentation to be correct and detailed enough. I'll add to to the PR. Thanks for your effort it really looks great
