### ISSUE TITLE
Provide zsync serverside file from image

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#364]
## Problem description

In order to keep a big data blob like an image in sync it would be great to have the opportunity to update only the changed blocks of the image file instead of transferring the entire blob with every change.
The zsync tool allows to do that. KIWI should be extended to provide a .zsync variant via:

```
$ zsyncmake image
```

as part of a bundler call

## Actual behaviour

The KIWI bundler provides its data not as a zsync variant
Also see: http://zsync.moria.org.uk/server for details

**Comment by adrianschroeter** [comment]
We support this already in AppImage case and extract the download there using the rpm macros:

ZSYNC_URL="$ZSYNC_URL$( rpm --eval '%{_download_url}/%{_project}/%{_repository}'|sed -e 's,:,:/,g' -e 's,//,/,g' )"
ZSYNC_URL="$ZSYNC_URL/${PKG_NAME}-latest-${PKG_ARCH}.AppImage.zsync"

the underscore macros are set by OBS and the build script.

**Comment by schaefi** [comment]
@adrianschroeter could you have a look at #390 if that meets the requirements ? Thanks
