### ISSUE TITLE
plymouth-set-default-theme not called on Centos when customizing bootsplash

### ISSUE THREAD

**Issue by msrex** [SUSE/kiwi#366]
Newest Kiwi with UEFI isos, Leap 42.2.

When theming a CentOS image with `bootsplash="asdf"` in `config.xml` the default theme is not set.

The command `plymouth-set-default-theme` needs to be called, or kiwi needs to make the correct entry in `/etc/plymouth/plymouthd.conf`.

**Comment by Conan-Kudo** [comment]
This also likely affects Fedora, too, since the plymouth theme setup is the same (or really, most distributions, since `plymouth-set-default-theme` is the plymouth tool for doing this...).

**Comment by schaefi** [comment]
This is interesting. I have built a centos7 image with

```xml
<preferences>
    <bootsplash-theme>charge</bootsplash-theme>

<packages type="image">
    <package name="plymouth-theme-charge" bootinclude="true"/>
```

and the image contains:

```
$ cat /etc/plymouth/plymouthd.conf 

# Administrator customizations go in this file
#[Daemon]
#Theme=fade-in
[Daemon]
Theme=charge
```

Assuming this is not correctly set in your case shouldn't the following script in config.sh solve the problem:

```bash
test -f /.profile && . /.profile

plymouth-set-default-theme $kiwi_splash_theme
```

My thoughts on splash are

* the package providing the splash screen sets itself as the default
* in case of multiple packages installed for some reason the script code above configures the desired splash. The splash theme name from the xml is available as $kiwi_splash_theme in the custom kiwi profile
* splash is handled very differently in the existing linux distributions. I'd like to avoid kiwi providing setup code for it

Thoughts ?

**Comment by Conan-Kudo** [comment]
The answer of "the package providing the splash screen sets itself as the default" is correct. This actually can be somewhat racey if more than one splash package gets installed (as it's perfectly fine to have multiple installed, and may be unavoidable).

What you'd want to do is just have it apply the setting after all the package actions are done, just to confirm that it's set the way the image creator expects.

As far as I know, splash screen stuff is handled the same way everywhere now, since everyone uses Plymouth...

**Comment by Conan-Kudo** [comment]
You are correct that we could set it in the config.sh file, but I think it makes sense that the splash does at least get attempted to be set by kiwi itself, since it's defined in the xml.

**Comment by schaefi** [comment]
ok that can be done based on the presence of `plymouth-set-default-theme` in the image

**Comment by Conan-Kudo** [comment]
@schaefi That's perfectly fine. 👍
