### ISSUE TITLE
ISO builds are broken in 9.7.1

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#371]
## Problem description

With kiwi 9.7.1, hybrid iso images don't boot with UEFI. After some trials, I figured out it was caused by b3e4b871d52da2b5ab579d592ccc7ae39de75339 (how? I have no clue). Reverting this change in [my branched kiwi package](https://build.opensuse.org/package/show/home:Pharaoh_Atem:branches:Virtualization:Appliances:Builder/python-kiwi) fixed this.

## Actual behavior
* When ISO is burned to a stick, the EFI firmware can't find anything to boot from the stick.

## Steps to reproduce the behavior
* Build a CentOS 7 ISO with UEFI support
* dd to a disk image with notruc flag
* Try to boot it and cry when it doesn't. 😢

**Comment by schaefi** [comment]
That sounds bad :( no idea why this is now broken, I'm sorry and will immediately take a look

**Comment by schaefi** [comment]
Hmm, I can't reproduce it. I build with the following type:

```xml
<type image="iso" boot="isoboot/rhel-07.0" flags="overlay" hybrid="true" firmware="uefi" hybridpersistent_filesystem="ext4" hybridpersistent="true"/>       
```

plug in a stick and:

```
$ dd if=/tmp/mytest/LimeJeOS-CentOS-07.0.x86_64-1.2.0.iso of=/dev/sdg
```

plug in the stick to real hardware configured for secure boot only without any legacy boot options enabled and it just boots

?

**Comment by schaefi** [comment]
nevertheless I've reverted the change, strangely enough both worked on my side
