### ISSUE TITLE
Include imageinclude information for --add-repo command line flag.

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#398]
## Problem description

When adding repositories at runtime through the command line KIWI it does not permit to configure imageinclude repository attribute. It is not possible to use --add-repo to configure the repositories for the resulting image.

## Actual behaviour

`imageinclude` is not considered in the --add-repo syntax. Current --add-repo syntax is:

```bash
--add-repo=<source,type,alias,priority>
```
and could be something like:

```bash
--add-repo=<source,type,alias,priority,imageinclude>
```

Related to #393

**Comment by davidcassany** [comment]
@schaefi I am not sure if it makes sense to include also `imageonly` attribute to be configurable with --add-repo, thus I have not included it in the description, also I don't like the idea of having something like

```bash
--add-repo=<source,type,alias,priority,imageinclude,imageonly>
```

as it looks like they could be both used together which doesn't have much sense.

**Comment by schaefi** [comment]
yes we should not allow imageonly on the command line, that doesn't make sense as --add-repo aims for repos used to build. You also have a point here with the mixture of flags which could be easily avoided if only imageinclude is allowed
