### ISSUE TITLE
Docker images doesn't require lxc configuration

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#40]
---mail snippet Aleksa Sarai <asarai@suse.de> ---

I just want to point out that I'm not entirely sure why we generate LXC
configurations (Docker hasn't used the LXC execdriver as the default
for about 2 years, and support for it was entirely dropped in Docker
1.10 -- a month ago).

**Comment by ChrisBr** [comment]
Removed the LXC configuration files and the container still works.
@schaefi what about the LXC folder? Do we want to remove the whole folder also?

**Comment by schaefi** [comment]
yes I think we don't need the directory, but I can't tell for sure
