### ISSUE TITLE
Rename kiwi --compat to kiwi compat

### ISSUE THREAD

**Issue by mlschroe** [SUSE/kiwi#407]
## Problem description

`kiwi --compat -- [legacy_args]` seems a bit weird to me, wouldn't it make sense to use `kiwi compat [legacy_args]` instead? That would also better fit the scheme kiwiv9 is using for the other commands.

**Comment by schaefi** [comment]
The reason for the --compat style is that it is in line with the legacy kiwi version style. It would be easy to change to a positional 'compat' argument but that would mean an incompatible option change for an already released package.

Thus my question is, other than personal preference is there any technical reason which makes this necessary ? if not I already can hear the people blaming us why we changed the option

Thanks

**Comment by schaefi** [comment]
@mlschroe Thoughts ?

**Comment by schaefi** [comment]
I guess no response means we don't have to invest more time in this one ? feel free to re-open if I'm mistaken. Thanks

**Comment by mlschroe** [comment]
Sorry, seems github didn't send me mails about your comments (or I missed them).

I don't think the argument "is in line with the legacy kiwi style" holds,  because AFAIK you always have to add a "--" dummy option after the "--compat" to end argument processing. This makes it somewhat weird and awkward.

The dummy "--" option is not needed for the "compat" sub-command style, and it is in line with the other commands of kiwi9.

Regarding the change in behavior: you could still accept the "--compat --" form, but not document it.

**Comment by mlschroe** [comment]
(github does not allow me to re-open this issue, as I didn't close it.)

**Comment by schaefi** [comment]
really if I close it the generator of the issue can't re-open it... that's useful, isn't it :-)

**Comment by schaefi** [comment]
ok I have added a pull request which makes this to work.

* kiwi --compat -- --build ...
* kiwi compat --build ...
* kiwi compat --build -- ...

all possible now. A review/testing is much appreciated
