### ISSUE TITLE
Make --ignore-repos switch imageinclude repos to imageonly

### ISSUE THREAD

**Issue by mlschroe** [SUSE/kiwi#410]
## Problem description

A `imageinclude` repo is conceptually equivalent to having a repo without `imageinclude` plus a repo with `imageonly` set. With `--ignore-repos` leaving imagonly repos intact, it would thus be logical that a `imageinclude` repo gets to be a `imageonly` repo in that case.

(It might also make sense to rename --ignore-repos to --ignore-repos-used-for-build' and have --ignore-repos again remove all repos. Just my 2 cents ;-) )

**Comment by mlschroe** [comment]
(But see the e-mail thread with David)

**Comment by schaefi** [comment]
> It might also make sense to rename --ignore-repos to --ignore-repos-used-for-build' and
> have --ignore-repos again remove all repos. 

That sounds like a good idea :+1: 

From a logic standpoint you are completely right, however I think people would be confused if the existing repo definition gets converted when the option --ignore-repos is passed. Thus I like the idea to have:

* --ignore-repos: does what it says, and ignores all repos
* --ignore-repos-used-for-build: does what it says and ignores all non imageonly repos

Thoughts ?

**Comment by davidcassany** [comment]
Yes, I also like the idea and it is pretty simple to implement, I doesn't require anything complex on KIWI side, as all the pieces and methods are already implemented do so. It is just a matter of the new option definition.

**Comment by mlschroe** [comment]
Ah, but the point of this issue is that imageinclude should be treated as imageonly when --ignore-repos-used-for-build is used. I don't see what's confusing about it.

**Comment by schaefi** [comment]
In my eyes this would be an unexpected behavior. From a repo definition used for building and marked as imageinclude I would expect:

* packages are taken from this repo and makes it into the image
* the very same repo is configured in my system

if this repo is explicitly ignored via --ignore-repos-used-for-build it means ignore it completely and not ignore it but keep it in my system repo setup.

I agree your logic is inarguable but the discussion seems like on the level of Spock talking to McCoy :-)
I doubt the standard user would expect an implicit conversion, most of them will think "I said ignore it" which means that definition basically does not exist
