### ISSUE TITLE
strip section in the image description file is not applied to the boot image

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#414]
## Problem description

Trying to prevent some file removal in the boot image through the system image `config.xml` does not work as exposed in [boot image documentation section](https://suse.github.io/kiwi/overview/workflow.html#faq-boot-image-customization).

## Actual behaviour

Including a section like the one below does not make any effect in the boot image:

```xml
<strip type="tools">
  <file name="lsblk"/>
</strip>
```

## Steps to reproduce the behaviour

Build a leap 42.2 JeOS with `boot="oemboot/suse-leap42.2"` and try to keep **lsblk** tool with the strip block provided above. The lsblk tool will be deleted anyways.

**Comment by davidcassany** [comment]
@schaefi not sure if I fully understood correctly the `strip` use case inside the system image description file. In case I did not understand it properly then I'd suggest to slightly modify or rephrase the docs 😃

**Comment by schaefi** [comment]
ok so here is how this should work:

* in boot/image/base.py we call import_system_description_elements() which among others copies the strip section data in copy_strip_sections to the boot image description

* In system/profile.py we call _strip_to_profile() which produces profile environment variables. The relevant one for your setup should have lsblk listed in kiwi_strip_tools

* The boot/arch/x86_64/oemboot/suse-leap42.2/images.sh calls among others suseStripInitrd which is the method which evaluates the contents of kiwi_strip_tools. The code for this is put into the common config functions in config/functions.sh

maybe you can check where in the process the lsblk information is missing

**Comment by davidcassany** [comment]
Great, then I got it right, I already investigated it and found the issue, just wanted to make sure I was using `<strip type="tools">` correctly. 

> in boot/image/base.py we call import_system_description_elements() which among others copies the strip section data via copy_strip_sections to the boot image description

The problem is here, copy_strip_sections is never applied from the system image to the boot image. Only the the strip sections distributed in the strip.xml file are copied.
