### ISSUE TITLE
Remote URL verification should not ever happen inside the buildservice

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#418]
## Problem description

KIWI fails when trying to verify a translated obs:// URI inside the buildservice. By design, buildservice does not provide internet connection during the build, hence this test will always fail.

## Actual behaviour

KIWI does the appropriate URL translation but it should not try to validate it when building inside the buildservice.

## Steps to reproduce the behaviour

A repository configuration like the following fails inside the public suse buildservice:

```xml
<repository type="rpm-md" imageonly="true">
  <source path="obs://openSUSE:Factory/snapshot"/>
</repository>
```

See the image [here](https://build.opensuse.org/package/show/home:dcassany:experimental_images:repositories_tests/obsrepositories_style)

**Comment by schaefi** [comment]
Fixed with #419

**Comment by davidcassany** [comment]
@scheafi, sorry this issue is not properly closed, as it is not really related to #419,  this one is related to `translate` and `_obs_project_download_link` methods of `kiwi/system/uri.py`. Note that `_obs_project_download_link` always tries to go to internet to verify the download link, and this method runs inside the buildservice if *imageinclude* or *imageonly* are used and a URI translation is needed.

IMHO `_obs_project_download_link` should have a differentiated procedure to validate the URL if running inside the buildservice. Something like:

```python
    def _obs_project_download_link(self, name):                                 
        name_parts = name.split(os.sep)                                         
        repository = name_parts.pop()                                           
        project = os.sep.join(name_parts)                                       
        try:                                                                    
            download_link = os.sep.join(                                        
                [                                                               
                    self.runtime_config.get_obs_download_server_url(),          
                    project.replace(':', ':/'), repository                      
                ]                                                               
            )
            if is not Defaults.is_buildservice_worker():
                request = requests.get(download_link)                               
                request.raise_for_status()
                return request.url
            elif self.runtime_config.is_obs_public():
                 return download_link
            raise KiwiUriOpenError('Not a public available URI')
        except Exception as e:                                                  
            raise KiwiUriOpenError(                                             
                '{0}: {1}'.format(type(e).__name__, format(e))                  
            )
```

Note I do not consider this issue a bug, since before the repository URI translation refactor this was not possible, thus it does not break any current project or build. This is just an enhancement to support a wider case of scenarios.

I consider that the projects tested [here](https://build.opensuse.org/project/monitor/home:dcassany:experimental_images:repositories_tests?arch_x86_64=1&defaults=0&failed=1&repo_images=1) should just build without issues.

**Comment by schaefi** [comment]
sorry I was too fast closing this one, my fault

**Comment by schaefi** [comment]
ok this addresses the issue that we can't validate the link in the world when running inside of the buildservice because the worker does not allow outgoing connections. Yes that makes sense

we loose the check if this url can really be reached but I guess there is not other way when running
inside of the buildservice
