### ISSUE TITLE
Include /.buildenv file inside the buildroot when building inside the buildservice

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#421]
## Problem description

In current KIWI versions when building inside the buildservice the build root is not populated witht he /.buildenv file. This specific file is provided by the buildservice and some packages installation scripts behave differently depending on the presence or not of this file. This results in a different installation of some packages (in concrete detected with plymouth-branding-openSUSE) when comparing the builds done with former kiwi versions compared with the current kiwi-ng.

## Actual behaviour

One example of this differences is the initrd image that gets created during the installation of plymouth-branding-openSUSE package. This initrd is created only if we are not running inside of the buildservice, that produces a difference of around 20MB when comparing the image size of the some ISO builds using former kiwi and current kiwi-ng.

## Steps to reproduce the behaviour

Create a live ISO and extract the resulting squashfs to verify that in includes a `/boot/initrd-xxxxx-default` file, which, in this concrete context, is just useless.

**Comment by davidcassany** [comment]
@DimStar77 I believe this might be the main cause of the size difference between KIWI v7 and KIWI v9 live images. In Kiwi v7 that initrd is not included into the image, but it is in the new version.

**Comment by davidcassany** [comment]
@schaefi, I think this issue must be closed or completely redefined. I finally found the issue here (I hope this time I really found it), the problem with the initrd is due to the /.buildenv file, expected to be present in build service build environments.

Some packages during installation perform some tests over this file and behave differently according to the result, the problem comes when kiwi installs any of those packages inside the buildservice being, at the same time, inside the kiwi buildroot chroot. Then is when we have a problem (not sure if this should be considered a problem though), because in current kiwi no /.buildenv is created inside the buildroot when building inside the buildservice. In legacy kiwi versions a /.buildenv file is created inside the buildroot.

In our concrete case this is leading to plymouth-branding-openSUSE to create a new initrd in kiwi-ng but not in legacy versions. Resulting in difference of around 20MB in the resulting build root, which is all then included in the squashfs of the ISO.

A note for @DimStar77, I believe that including plymouth-branding-openSUSE package in the bootstrap packages section in your config.xml file could solve this problem in this concrete case. I have not test it though.

**Comment by schaefi** [comment]
Ah that was the reason why we touched this file in the legacy kiwi code base. Thanks much for investigating this issue. I suggest we add back the .buildenv when we are building inside of the buildservice and make sure it is not going to be synced into the image (see _get_exclude_list_for_root_data_sync for details)

**Comment by schaefi** [comment]
and I agree the issue could be renamed according to your findings
