### ISSUE TITLE
Kiwi - Makefile uses call to python3

### ISSUE THREAD

**Issue by mmohring** [SUSE/kiwi#424]
## Problem description

The global Makefile uses explicit calls to python3. This prevents building a python2 only version for older distros.

## Actual behaviour

python2 setup.py build --cflags="${RPM_OPT_FLAGS}" 

in the spec file calls the Makefile which calls python3

## Steps to reproduce the behaviour

Look into the git repo, at Makefile.

**Comment by mmohring** [comment]
Is it really needed to call python3 explicitely in the global Makefile ? If not I provide a version for python2 only on older distros, to be used as OBS plugin for targets like CentOS 7.

**Comment by schaefi** [comment]
our spec file builds python2-kiwi and python3-kiwi packages in one build, see e.g:
http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_42.3/x86_64/

The kiwi code base including all helper and packaging tools are written with a focus on py3 compatible to py2 but we recommend and also documented to setup the development environment in py3.

Nevertheless you have a point here, I'll check the places where we directly call python3 and come up with a fix

**Comment by mmohring** [comment]
@schaefi, my patch looks exactly the same as yours. I have cleaned up everything, added the missing packages for CentOS and tested it to build a VMX Image on CentOS 7.3 with OBS. The python2-kiwi works and produces a CentOS image that works. So I will provide you with a pull request for the remaining patch to build the OBS package for use with OBS on Fedora and CentOS.

**Comment by mmohring** [comment]
As a follow up I have submitted #428 , which packages python-kiwi now for CentOS / RHEL 7 and Fedora > 25 in the spec file template. Since CentOS / RHEL 7 is python 2 only, it is a follow up patch so to say.
