### ISSUE TITLE
kiwi - 9.9.3 - fails with - No such file or directory: '.buildenv'

### ISSUE THREAD

**Issue by mmohring** [SUSE/kiwi#431]
## Problem description

Current 9.9.3 version fails with:

[  220s] [ ERROR   ]: 12:19:13 | KiwiRootInitCreationError: IOError: [Errno 2] No such file or directory: '.buildenv'
[  220s] [ INFO    ]: 12:19:13 | Cleaning up SystemPrepare instance

## Actual behaviour

Did not happen before this patch, with 9.9.2

## Steps to reproduce the behaviour

Use the package from b.o.o in OBS

**Comment by schaefi** [comment]
yes sorry this was a regression fixed with #422 

You should not see this with 9.9.4
