### ISSUE TITLE
Default to use all cores for xz compression

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#433]
Maybe the default option for xz should be to use all cpu cores, in that case we should add:
```diff
    @classmethod
    def get_xz_compression_options(self):
        return [
            '--check=crc32',
            '--lzma2=dict=512KiB',
+          '--threads=0'
        ]
``` 
https://github.com/SUSE/kiwi/blob/80b3c1a139d33de29820971719edb96ba3fe0871/kiwi/defaults.py#L66

`--threads` seems to be available since 5.2.0 (2014-12-21) according to https://git.tukaani.org/?p=xz.git;a=blob;f=NEWS;hb=HEAD#l127

**Comment by md-work** [comment]
This only affects the compression of the initrd. Not the compression of the whole image (e.g. the suqashfs file).

Correct!?

**Comment by davidcassany** [comment]
This affects compression calls of xz and tar utilities, except for the initrd (which uses other non-configurable specific options). Compressed squashfs files are done with mksquashfs utility, thus they are not affected by that change.
