### ISSUE TITLE
Default xz options too strict

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#435]
The default xz options specifies `--check=crc32 --lzma2=dict=512KiB` for compressing 
(https://github.com/SUSE/kiwi/blob/80b3c1a139d33de29820971719edb96ba3fe0871/kiwi/defaults.py#L69)
These options are only needed for files uncompressed by the kernel
(see https://www.kernel.org/doc/Documentation/xz.txt for more information)

This causes other files compressed by kiwi to become unnecessary big since their dictionary becomes very limited:
Wrong:
`[  429s] [ DEBUG   ]: 11:49:25 | EXEC: [xz -f --check=crc32 --lzma2=dict=512KiB --keep /usr/src/packages/KIWI-oem/FOOBAR_JEOS_SLE12.2.x86_64-5.0.0.raw]`

Correct:
`[  703s] [ DEBUG   ]: 11:53:58 | EXEC: [xz -f --check=crc32 --lzma2=dict=512KiB /usr/src/packages/KIWI-oem/FOOBAR_JEOS_SLE12.2.x86_64-5.0.0.initrd]`

Wrong:
`[  779s] [ DEBUG   ]: 11:55:15 | EXEC: [bash -c tar -C /usr/src/packages/KIWI-oem/kiwi_pxe_install_media.q6ptbwwx --xattrs --xattrs-include=* -c --to-stdout FOOBAR_JEOS_SLE12.2.append pxeboot.initrd.xz FOOBAR_JEOS_SLE12.2.xz pxeboot.kernel FOOBAR_JEOS_SLE12.2.md5 | xz -f --check=crc32 --lzma2=dict=512KiB > /usr/src/packages/KIWI-oem/FOOBAR_JEOS_SLE12.2.x86_64-5.0.0.install.tar.xz]`

**Comment by Jellyfrog** [comment]
Size difference after re-compression:
198M - Kiwi's output
186M - xz foobar.raw
171M - xz -9 foobar.raw

**Comment by schaefi** [comment]
yes thanks we need to change this and apply the above only for the initrd compression case

**Comment by schaefi** [comment]
hope you don't mind the rename of the issue, as I don't think the options are wrong ;)

**Comment by schaefi** [comment]
Comment from @Jellyfrog to improve the options for initrd compression

>Dracut defaults to 1MB, maybe kiwi should bump its default value too? https://github.com/dracutdevs/dracut/blob/295194ee42c2e5b67484010b78908b76113a8291/dracut.sh#L816

This would generate a slightly smaller file :)

**Comment by Jellyfrog** [comment]
@schaefi probably should make two different xz "default options", one for general use and one specifically for initrd

**Comment by davidcassany** [comment]
I was thinking something similar to what @Jellyfrog suggests. In my opinion, the relevant question here is if we want to let the user provide its own custom xz options for initrd (I think this is the case). Then, if so, I would distinguish two different defaults and also two different fields in config.yml.

Does it makes sense to you?

**Comment by schaefi** [comment]
I think we should not provide a way for customers to change the compression options for the boot image because the kernel set constraints on it.

I'll prepare a patch and we can discuss the code
