### ISSUE TITLE
Ability to delete drivers/firmwares

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#442]
## Problem description
There is no way to define a list of drivers/firmwares to strip, there is `<strip type="delete">` but its more for generic file/binary use.

`<drivers>` should learn a new attribute `type="delete"` and ideally it should be included in the "Deleting unwanted module"-step

**Comment by schaefi** [comment]
Why does the following not work for you ?

```xml
<strip type="delete">
    <file name="/lib/firmware/brcm/*-pcie.bin"/>
</strip>
```

actually kiwi automatically strips the firmware to the one which is required by the still installed drivers. If you intentionally delete more firmware data it can be done with the generic strip delete as indicated above.

I don't see a real use case for providing a specific firmware deletion

Thoughts ?

**Comment by Jellyfrog** [comment]
Because the `<strip>`-removing happens after firmware-deleting, so if I delete a driver in `<strip>` it wont be taken into account in the "Deleting unwanted firmware"-step (https://github.com/SUSE/kiwi/blob/ca5d036b52751e1cbba320873c2b1ffb4217e09c/kiwi/config/functions.sh#L1363-L1391)
So then i would have to also manually specify all firmware-files to cleanup.
But if there would be a `<drivers type="delete">` this would happen automatically.
Hope that makes sense...

**Comment by schaefi** [comment]
Thanks that makes perfect sense. I consider this a bug in kiwi then, the check for unused firmware should happen after all potential deletion of drivers. I'll look into it
