### ISSUE TITLE
Ability to add users to boot image

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#451]
## Problem description
I'ts currently not possible to add users to the boot image, they only end up in the system image, could this feature be added with a `bootinclude`-attribute?
Use case is that we need to include a user with a password to be able to ssh (via dropbear), unfortunately due to "corporate reasons" we can't use public key authentication as described in https://suse.github.io/kiwi/overview/workflow.html?highlight=authorized_keys#boot-debugging
## Actual behaviour
N/A
## Steps to reproduce the behaviour
N/A

**Comment by schaefi** [comment]
It sounds weird to me that for "corporate reasons" a password based login is preferred over an authorized ssh key. From my experience it's normally the other way round

I'm sorry we support ssh login to the boot image only via pubkey authentication for debugging purposes as documented and won't extend the boot image to be a user consumable system. That's outside of the scope of an initrd

**Comment by Jellyfrog** [comment]
I'll add it via a package then, no problem :)
