### ISSUE TITLE
Include package in boot image only

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#453]
## Problem description
There is both a `bootdelete` and `bootinclude` attribute, but how do I make a "bootonly" package?
For example, I don't want my "kiwi-hooks" archive to end up on my "system image"

Also, `bootdelete` description makes little sense:
> ...
the attribute is only
evaluated if the bootinclude attribute is specified
along with it too

Why include something that you want to delete?

**Comment by schaefi** [comment]
if you say

```xml
<package name="foo" bootinclude="true" bootdelete="true"/>
```

this package exists for the time the boot image will be built. This could be needed for e.g compile jobs where you need e.g headers only for a short time

If you say

```xml

<package type="image">
    <package name="foo" bootinclude="true"/>
</packages>

<packages type="delete">
    <package name="foo"/>
</packages>
```

The package will be installed in the image and the boot image but gets deleted in the image later
