### ISSUE TITLE
Allow repository data to be refreshed on the generated media

### ISSUE THREAD

**Issue by probonopd** [SUSE/kiwi#461]
## Problem description

I would like my Kiwi-generated Live ISO to have working (refreshed) repository data preinstalled, like on Ubuntu Live CDs.

## Actual behaviour

Adding `zypper refresh` to `config.sh` would result in the build to be stalled forever.

## Steps to reproduce the behaviour

Add `zypper refresh`.  Example:
https://build.opensuse.org/package/view_file/home:probono:branches:KDE:Medias/openSUSE-Argon/config.sh?expand=1

**Comment by schaefi** [comment]
sure because obs does not allow outgoing connections

**Comment by davidcassany** [comment]
@probonopd, currently this is not possible and this is more a limitation of the build service than a KIWI limitation. Note that using the build service the build environment has no access to internet by design, so a call like `zypper refresh` in your config.sh won't work. From the KIWI side there isn't much we can do about that.

**Comment by probonopd** [comment]
That's too bad. Is there a way I could get this to my local machine and upload it in an archive?

**Comment by schaefi** [comment]
why do you want to do that ? there is no time you can be sure a repo has fresh metadata unless you request for it. Why is zypper's auto refresh method not suitable for you ?

**Comment by probonopd** [comment]
It adds time (and download bandwidth) to the first invocation of `zypper install ...`.

**Comment by schaefi** [comment]
correct, given you build the image with some state of metadata on let's say Monday that the state is frozen to that build time. If you run the live iso at any later point in time and you reference non frozen repository state (which I assume is the case) the first invocation of zypper install will fetch updated metadata no matter if you have some old one as part of the image.

That concept is questionable to me, but maybe your use case is different.

In any case we can't do much here, obs does not allow outgoing connections at build time.
You can of course tar up some repo state and put that as overlay tarball to root.tar.gz
kiwi will copy all of that data to your image.
