### ISSUE TITLE
oem-kiwi-initrd fails on reboot

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#465]
## Problem description

There is a report on the mailing list saying that the use of

```xml
<oem-kiwi-initrd>true</oem-kiwi-initrd>
```

will cause the image to boot once but failed on reboot in a configuration with lvm
enabled as follows:

```xml
<type image="oem" boot="oemboot/rhel-07.0" filesystem="ext3" installiso="true" bootloader="grub2" >
         <systemdisk name="volgroup01" preferlvm="true">
              <volume name="LVhome" size="200M" mountpoint="/home"/>
              <volume name="@root" freespace="5G" />
              <volume name="LVvar" mountpoint="/var" freespace="all"/>
              <volume name="LVlog" size="200M" mountpoint="var/log"/>
              <volume name="LVtmp" size="1800M" mountpoint="/tmp"/>
          </systemdisk>
          <oemconfig>
              <oem-kiwi-initrd>true</oem-kiwi-initrd>
          </oemconfig>
</type>
```

**Comment by davidcassany** [comment]
I have already verified the bug, I could reproduce it in rhel/centos builds, not in openSUSE. The bug appears regardless the presence of `<oem-kiwi-initrd>true</oem-kiwi-initrd>` or not. Looks like there's something wrong with the dracut initrd build. Still digging it.
