### ISSUE TITLE
Refactor live iso layout to be able to use dracut

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#470]
## Problem description

kiwi implemented its own live iso layout which is nice and works. However with regards to the intention of kiwi to not re-invent the wheel and the fact that newer versions of dracut also implements a live boot mechanism it would be worth to investigate to use the dracut initrd instead of the kiwi isoboot code.
This would also generalize the live layout throughout the various distributions

**Comment by schaefi** [comment]
Details how the iso structure must look like:

* https://github.com/haraldh/dracut/blob/master/dracut.cmdline.7.asc#booting-live-images

**Comment by schaefi** [comment]
Started to work on this one

**Comment by schaefi** [comment]
![screenshot_20170822_190025](https://user-images.githubusercontent.com/912234/29577602-4ff4799c-876c-11e7-9128-69f938050c7d.png)

**Comment by schaefi** [comment]
this is what I got on a first shot, do I need to call dracut with options or is a dracut module missing ? How can I check that ?

**Comment by schaefi** [comment]
ah found it, I need a dracut conf e.g

```
add_dracutmodules+=" dmsquash-live pollcdrom "
hostonly="no"
dracut_rescue_image="no"
```

**Comment by schaefi** [comment]
Looks good so far, still investigating how persistent writing is implemented in dracut, thus the attributes

* hybridpersistent_filesystem
* hybridpersistent

are still orphan

**Comment by schaefi** [comment]
Also still to be done:

* deletion of all isoboot code as no longer needed :) __last step__

**Comment by schaefi** [comment]
Successfully tested with dracut v046, this version or higher is required for use with overlayfs
which also makes it hard to get merged because not all distros have this version of dracut. I've also contacted Harald (dracut developer) to investigate the persistent writing issue

**Comment by FGrose** [comment]
See below (inline) for response to this email:

from: | Harald Hoyer <harald@redhat.com>
to: | Marcus Schäfer <ms@suse.de>,Frederick Grose <fgrose@sugarlabs.org>
date: | Thu, Aug 24, 2017 at 6:46 AM
subject: | Re: dracut and persistent writing using rd.live.overlay

Maybe Frederick can answer your questions, as he wrote most of it.

On 24.08.2017 12:36, Marcus Schäfer wrote:
> Hi Harald,
>
> hope you don't mind disturbing you by mail.
>
> Newer versions of dracut supports the use of overlayfs for live
> systems apart from the still existing dmsquash layout. This is
> a great extension and gives me the opportunity to replace all
> the isoboot code I use in kiwi with dracut. I have done all the
> code changes in reference with the issue from here:
>
>     https://github.com/SUSE/kiwi/issues/470
>
> and successfully tested live images using overlayfs and
> dracut-live-046-2.git20170811.fc27.x86_64.rpm
>
> So far this is really great :)
>
> In the kiwi isoboot code there is a feature which does the
> following if the live iso file is dumped on a persistant storage
> device like e.g a usb stick:
>
> - on boot we detect that we can write here
>
> - on boot the iso embedded hybrid partition table gets a new
>   partition spawning the entire rest space of the device
>
> - a filesystem is created on that new partition
>
> - overlayfs is setup to use this writable space as persistent
>   storage instead of a tmpfs
>
> With the iso image using the dracut generated initrd I have
> done the following to test persistent overlay as documented
> here: https://github.com/haraldh/dracut/blob/master/dracut.cmdline.7.asc#booting-live-images

The current repository is at the following link:
https://github.com/dracutdevs/dracut/blob/master/dracut.cmdline.7.asc#booting-live-images

This has the added instructions for OverlayFS overlays.
Note that various alternative and independent storage configuration options have accumulated over time and are presented together for completeness with little advice or segregation.

>
>   qemu-img create mydisk 10g
>   dd if=myimage.iso of=mydisk conv=notrunc
>
>   qemu-kvm mydisk
>
>   --> boot and login, on the machine call
>
>       fdisk /dev/sda
>       * create new primary partition
>
>       partprobe /dev/sda
>       mkfs.ext4 /dev/sda3
>
>       mount /dev/sda3 /mnt
>       truncate -s 4g /mnt/persistent-overlay.img
>       umount /mnt
>
>       reboot
>
> If I understood things right the machine should now be prepared
> for persistent storage :)
>
> At the boot prompt I typed:
>
>   rd.live.overlay=/dev/sda3:persistent-overlay.img
>
> And that end up in a dracut rescue shell
>
> Before I continue I'd like to ask:
>
> Q: Am I doing something wrong ? or is the above intented to work ?
>
> Q: Given there is a way to get persistent writing to work, is there
>    a way to automate the creation of a persistent storage area like
>    I have described it with reference to kiwi in dracut too or do
>    we need to add that code ?
>
> Q: And last but not least my intention with live iso's is that they
>    are smart enough to detect if data can be written persistently
>    and just make use of it if possible, or not if not possible
>    without the need for the user to perform some "storage preparation"
>    process. From the dracut point of view would that be something
>    you would agree to or rather not ?
>
> Thanks much for your help
>
> Regards,
> Marcus

Please see this pull request for some background on this feature in dracut:
https://github.com/dracutdevs/dracut/pull/107

The feature is a first order working demonstration of OverlayFS booting for evaluation purposes derived from the Fedora [LiveOS model](https://fedoraproject.org/wiki/LiveOS_image).  So improvements, such as might result from this work, are intended.

The standard method of preparing a persistent LiveOS device is with the `livecd-iso-to-disk` script.
See https://github.com/livecd-tools/livecd-tools/blob/master/tools/livecd-iso-to-disk.sh
and this commit,
https://github.com/livecd-tools/livecd-tools/commit/04d52c64d946346e48b01127b7b7d4f67f9bcf31
for the implementation of the OverlayFS option.

It might help for you to see the `grub.cfg` for a LiveUSB on an EFI System (Legacy BIOS Bootable) FAT (32-bit version) formatted device prepared by the above script:
```sh
set default="1"

function load_video {
  insmod efi_gop
  insmod efi_uga
  insmod video_bochs
  insmod video_cirrus
  insmod all_video
}

load_video
set gfxpayload=keep
insmod gzio
insmod part_gpt
insmod ext2

set timeout=60
### END /etc/grub.d/00_header ###

search --no-floppy --set=root -l 'Fedora-WS-Live-26-1-5'

### BEGIN /etc/grub.d/10_linux ###
menuentry 'Start Fedora-Workstation-Live 26' --class fedora --class gnu-linux --class gnu --class os {
	linuxefi /syslinux/vmlinuz root=live:UUID=393B-5FCF rd.live.image rw rd.live.overlay=UUID=393B-5FCF rd.live.overlay.overlayfs 
	initrdefi /syslinux/initrd.img
}
menuentry 'Test this media & start Fedora-Workstation-Live 26' --class fedora --class gnu-linux --class gnu --class os {
	linuxefi /syslinux/vmlinuz root=live:UUID=393B-5FCF rd.live.image rw rd.live.overlay=UUID=393B-5FCF rd.live.overlay.overlayfs rd.live.check quiet
	initrdefi /syslinux/initrd.img
}
submenu 'Troubleshooting -->' {
	menuentry 'Start Fedora-Workstation-Live 26 in basic graphics mode' --class fedora --class gnu-linux --class gnu --class os {
		linuxefi /syslinux/vmlinuz root=live:UUID=393B-5FCF rd.live.image rw rd.live.overlay=UUID=393B-5FCF rd.live.overlay.overlayfs nomodeset quiet
		initrdefi /syslinux/initrd.img
	}
}
```
Hope that helps,         --Fred

**Comment by FGrose** [comment]
I added some responses inline to your specific questions above.
