### ISSUE TITLE
Current python3-kiwi package has missing dependences in SLE12SP3

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#475]
## Problem description

Current KIWI version requires _python3-requests_ package for _python3-kiwi,_ which is not included in SLE12SP3 repositories, thus leading kiwi builds in SLE12SP3 (and also for prior SLE12 versions) but the resulting _python3-kiwi_ can't be installed due to missing dependencies.

## Actual behaviour

Python-kiwi builds against SLE12SP3 succeed, but the package _python3-kiwi_ can't be installed due to missing _python3-requests_.

## Steps to reproduce the behaviour

Build python-kiwi in SLE12SP3 and try to install the resulting python3-kiwi.

**Comment by schaefi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update kiwi in SLES12 SP2 and SP3](https://trello.com/c/zkcNJ6GU/204-update-kiwi-in-sles12-sp2-and-sp3)

**Comment by schaefi** [comment]
Tracked in https://fate.suse.com/324024

**Comment by davidcassany** [comment]
Submit request for python3-requests done, SR num: 140814

**Comment by schaefi** [comment]
That's great, I see the request was accepted. Thus there is not more we can do here. Thanks much
