### ISSUE TITLE
obs:// repository syntax

### ISSUE THREAD

**Issue by probonopd** [SUSE/kiwi#487]
## Problem description

It is not obvious how to enter obs repos:

```
  <!-- Unclear how to convert this syntax to the required obs line:
  zypper addrepo http://download.opensuse.org/repositories/devel:tools/openSUSE_Leap_42.3/devel:tools.repo -->
  <repository type="rpm-md" priority="10">
	  <source path="obs://devel:tools/openSUSE_Leap_42.3/devel:tools"/><!-- for prelink -->
  </repository>
```

Possibly this could be simplified, so that one could enter http://download.opensuse.org/repositories/devel:tools/openSUSE_Leap_42.3/devel:tools.repo
Please clarify.

**Comment by schaefi** [comment]
Not sure what you mean, the obs:// syntax follows the same rules as the project name and hierarchy

```
<repository type="rpm-md" priority="10">
    <source path="obs://devel:tools/openSUSE_Leap_42.3"/>
</repository>
```
