### ISSUE TITLE
Document Functions, Class, and Methods in Docstrings

### ISSUE THREAD

**Issue by tomschr** [SUSE/kiwi#49]
## Problem description
*This is probably a long term issue*

Currently, the code base has got different "API documentation": Some functions and methods have docstrings, others comments, and others don't have any documentation at all.

I think, this situation can be improved. :smiley:

## Reasons

I see the following important points why I think this is important:

* It helps contributors to find its way through the code.
* It encourages good coding style.
* It makes interactive development easier (due to introspection).
* It makes it easier to create API documentation automatically (see Sphinx).

## Possible Solution

I think, a good docstring should contain the following parts:

* Short summary of the function 
* Parameters and their datatypes
* Return values and the datatype(s)
* Possible exceptions

In openSUSE/docmanager#7 I've suggested [Sphinx style](http://sphinx-doc.org/domains.html#info-field-lists):

```python
def add(a, b):
    """Adds two numbers

    :param int a: first argument
    :param int b: second argument
    :return:      sum of a and b
    :rtype:       int
    """
    return a+b
```

Here are a few specific ideas, taken from Brett Slatkins book "Effective Python":

* Documenting Modules
  Each module should have a top-level docstring. It should contain a single sentence describing the module's purpose. The paragraph that follow should contain the details that all users of the module should know about its operation.

* Documenting Classes
 Each class should have a class-level docstring. The first line describes the purpose of the class. Paragraphs that follow discuss important details. Also important public attributes and methods should be described in the class-level docstring. If possible or applicable, also provide guidance to subclass.

* Documenting Functions
  Each public function and method should have a docstring. This follows the same pattern as modules and classes. Additionally, there are also some special cases that are important to know:

  * If your function has no arguments and a simple return value, a single sentence description is probably good enough.
  * If your function doesn't return anything, it's better to leave out any mention of the return value instead of saying "returns None".
  * If you don't expect your function to raise an exception during normal operation, don't mention that fact.
  * If your function accepts a variable number of arguments or keyword-arguments, use `*args` and `**kwargs` in the documented list of arguments to describe their purpose.
  * If your function has arguments with default values, those defaults should be mentioned.
  * If your function is a generator, then your docstring should describe what the generator yields when it's iterated.

**Comment by schaefi** [comment]
This make s a lot of sense and should be done

Here is an example for the Cli class

* I don't like the """text syntax, is this somewhat important, or can it be done as suggested below
* Classes should document public attributes and the public interface. To what extend is a description of the methods required ? dos the example below describe it good enough ?

```
"""
Implements the main command line interface

An instance of the Cli class builds the entry point for the application and
implements methods to load further command plugins which itself provides
their own command line interface

public attribute: command_args
    docopt command argument hash

public attribute: command_loaded
    result of importlib command load operation

method: show_and_exit_on_help_request
    execute man to show the selected manual page

method: get_servicename
    return selected service name from docopt parse result

method: invoke_kiwicompat
    execute kiwicompat with provided command line arguments

method: get_command
    return selected command name for service

method: get_command_args
    return docopt command argument hash for selected command

method: get_global_args
    return global arguments docopt hash

method: load_command
    load task class from selected service and command
"""
```

**Comment by schaefi** [comment]
This is just a start, @tomschr what do you think ?

**Comment by tomschr** [comment]
> I don't like the `"""text` syntax, is this somewhat important, or can it be done as suggested below

I've tested it with and without linebreak and it doesn't matter.

>    Classes should document public attributes and the public interface. To what extend is a description of the methods required ? dos the example below describe it good enough ?

I think, a short description would be enough. However, I would use the following syntax:

```python
[... skipped ...]

* :func:`show_and_exit_on_help_request`: execute man to show the selected manual page
* :func:`get_servicename`: return selected service name from argument parse result
```

With the `:func:` syntax, Sphinx will automatically create a link to the respective description of the method. See the [Cross-referencing Python objects](http://www.sphinx-doc.org/en/stable/domains.html?highlight=func#cross-referencing-python-objects) section in the Sphinx documentation for details. By the way, you can leave out the `py` domain by default, so `:py:func:` and `:func:` are the same.


>    to what extend is the syntax important ? thinking about tools reading the doc strings

It's important if you care about automatic cross-referencing. :smiley:  See previous paragraph. Usually it isn't that hard, as you can create editor macros to minimize the task.

**Comment by tomschr** [comment]
> This is just a start, @tomschr what do you think ?

See my short comment

**Comment by tomschr** [comment]
@schaefi This is how Sphinx renders the above commit (excerpt):

![kiwi cli](https://cloud.githubusercontent.com/assets/1312925/14320974/95d393f8-fc17-11e5-8c36-4e7b4adea3a4.png)

**Comment by tomschr** [comment]
Find here the automodule feature: http://www.sphinx-doc.org/en/stable/ext/autodoc.html#module-sphinx.ext.autodoc

**Comment by schaefi** [comment]
The initial setup is done, cli.py serves as example. Now all other source files needs to be adapted with good api documentation. I consider this to be work in progress, thus leaving the issue open until we have gone through all source files.

@tomschr if you are bored by the time, documenting classes is an exciting task ;) :) just kidding

**Comment by tomschr** [comment]
@schaefi This is awesome! :+1: Great work!

> if you are bored by the time, documenting classes is an exciting task ;) :) just kidding

Hehe. :))) I would, but I fear I don't know as much as you. :)

**Comment by schaefi** [comment]
all done
