### ISSUE TITLE
Support dynamic VHDX image format

### ISSUE THREAD

**Issue by mnowaksuse** [SUSE/kiwi#490]
## Problem description

Support dynamic VHDX (gen2) image format for Hyper-V.

## Actual behaviour

Currently VHD (gen1) format is supported as dynamic and fixed 'subformats'.

**Comment by schaefi** [comment]
Just for the record if you call:

```
qemu-img convert -f raw image.raw -O vhdx -o subformat=dynamic image.vhdx
```

That produces a working result for you on $MS HyperV ?

I'm just asking because I don't have access to that virtualization system and I expect that qemu can cope with it but that wouldn't be the target system

Thanks

**Comment by mnowaksuse** [comment]
I manually converted vhdfixed images of JeOS and CaaSP to VHDX and both run fine on WS 2012's Hyper-V.

**Comment by mmohring** [comment]
Hi, IIRC I had a similiar problem. I solved it by using the image converter of virtualbox and not that of qemu. The qemu converted images did not work for example in the azure cloud. The stuffing was complained.

**Comment by schaefi** [comment]
@mmohring well we built all of our Azure images with format="vhdfixed" which set kiwi to use qemu-img with the option -o subformat="fixed". That works nicely no need for other tools.

This one is about vhdx which is the generation2 dynamic vhd format not supported by Azure but on modern versions of HyperV. However I have no access to such a HyperV system and thus asked for the requester to test if the qemu call as in the test from #492 works for him

**Comment by schaefi** [comment]
@mmohring Azure requires the people to build fixed size vhd's of the size of 30G, they don't accept anything else which is really weird :)

**Comment by mnowaksuse** [comment]
Just for the record: I am interested in Azure-less Hyper-V, so to speak :).

**Comment by mmohring** [comment]
@mnowaksuse, @schaefi  I am aware of that the topic was Hyper-V and *not* Azure and vhdxfixed. It just reminded me of the alignment issue in Azure. I could get images other than 30 GB working with that method. I am willing to test this with qemu-img again.
