### ISSUE TITLE
Setting volume id with ISO images breakes dracut boot

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#493]
## Problem description

Live iso images do not boot if `volid` attribute is used. Apparently giving a volume id breaks the boot process with dracut.

## Actual behaviour

iso images do not boot.

## Steps to reproduce the behaviour

Use a `<type>` section like the following one:

```xml
<type primary="true" flags="overlay" hybrid="true" hybridpersistent="true" hybridpersistent_filesystem="ext4" image="iso" firmware="uefi" volid="GNOME Next"/>
```

The resulting image won't boot.

**Comment by davidcassany** [comment]
This only happens when the volid contains spaces. I am wondering if instead tyring to make it work with spaces (by handling them is someway) wouldn't it be best to just limit the characters to be used in that `voild` field. What about something like using the same pattern as we use for the image, this way we are sure there is no combination that breaks the boot.

I noticed the device is mapped by label with some kind of URL coding if white spaces are used, something like:

/dev/disk/by-label/GNOME%20Next

@schaefi any thoughts? I vote to limit the allowed characters as we do for the image name.

**Comment by davidcassany** [comment]
Just tested a `volid` with `.1GNOME-.0Next_` and it worked without problems, thus I would just limit the character set for this attribute to solve this issue and not allow white spaces. Using the same regular expression for the image-name `[a-zA-Z0-9_\-\.]+` looks like a good option to me.

**Comment by schaefi** [comment]
yes fully agree, let's limit it which can be done in the schema

Thanks for finding this I have tested several volid but never used a white space :)
