### ISSUE TITLE
boot attribute is only available for the following image types: oem pxe

### ISSUE THREAD

**Issue by probonopd** [SUSE/kiwi#494]
## Problem description

As of late, getting

> boot attribute is only available for the following image types: oem pxe

I am not aware that I have changed something regarding boot attributes. Please advise.

```
[  163s] running kiwi system build for iso...
[  163s] cd /usr/src/packages/SOURCES && rm -rf /usr/src/packages/KIWI-iso && LANG=en_US.UTF-8 /usr/bin/kiwi --debug  system build --description /usr/src/packages/SOURCES --target-dir /usr/src/packages/KIWI-iso 
[  163s] [ DEBUG   ]: 07:38:55 | EXEC: [mkdir -p /usr/src/packages/KIWI-iso/build]
[  163s] [ INFO    ]: 07:38:55 | Loading XML description
[  164s] [ INFO    ]: 07:38:56 | Schematron validation failed:
[  164s] [ INFO    ]: 07:38:56 | --> boot attribute is only available for the following image types: oem pxe
[  164s] [ ERROR   ]: 07:38:56 | KiwiDescriptionInvalid: Schema validation for /usr/src/packages/SOURCES/config.xml failed
[  164s] 
[  164s] cloud106 failed "build plasma5-unstable-live.kiwi" at Wed Sep 13 07:38:56 UTC 2017.
[  164s] 
```

## Actual behaviour

https://build.opensuse.org/package/live_build_log/home:probono:branches:KDE:Medias/openSUSE-Argon/images/x86_64

## Steps to reproduce the behaviour

https://build.opensuse.org/package/show/home:probono:branches:KDE:Medias/openSUSE-Argon

**Comment by davidcassany** [comment]
@probonopd, yes in fact, currently the boot attribute is only available for the pxe and oem images. Now, iso and vmx images always make use of the dracut initrd, which is smaller and faster. You should just remove the boot attribute from your kiwi config file and, if building iso images, include the package _dracut-kiwi-live_ in your <packages> section. There are some runtime checks to verify the description for iso or vmx includes all what is needed.

**Comment by schaefi** [comment]
yes see our example test build:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86/test-image-iso

It's all on dracut now which solves some of your previous issues in a better way

**Comment by probonopd** [comment]
Thanks. Can `volid` be deleted too?
