### ISSUE TITLE
initrd problem - dracut created initrd for VMX in KIWI is basically empty for CentOS 7, Fedora 25 / 26

### ISSUE THREAD

**Issue by mmohring** [SUSE/kiwi#495]
## Problem description
The dracut call in KIWI causes the the initrd to be basically empty.

## Actual behaviour
When I create an Image of type vmx the initrd is basically empty which can cause boot problems if a driver is missing.

## Steps to reproduce the behaviour
1. create an image with KIWI for CentOS 7.3 or Fedora 25 / 26
2. mount the created image with libguestfs
3. check the initrd:

> `cat <localmountpoint>/boot/<initramfs> | cpio -ivt`
drwxr-xr-x   3 root     root            0 Sep 14 00:37 .
-rw-r--r--   1 root     root            2 Sep 14 00:37 early_cpio
drwxr-xr-x   3 root     root            0 Sep 14 00:37 kernel
drwxr-xr-x   3 root     root            0 Sep 14 00:37 kernel/x86
drwxr-xr-x   2 root     root            0 Sep 14 00:37 kernel/x86/microcode
-rw-r--r--   1 root     root        24070 Sep 14 00:37 kernel/x86/microcode/AuthenticAMD.bin
49 blocks

In case I can boot the system, I can create a real working initrd with:

$ mkinitrd -f `/boot/<initrd> <kernelversion>`

**Comment by mmohring** [comment]
A copy of the project for the KIWI NG for CentOS 7 and Fedora 25 / 26, git master, 9.11.3, is in b.o.o: https://build.opensuse.org/project/show/home:MartinMohring:KIWI-NG:Appliance
A copy of the project for the Image descriptions used is in: https://build.opensuse.org/project/show/home:MartinMohring:KIWI-NG:image

**Comment by schaefi** [comment]
I'm sorry but this can't be a problem of kiwi. I have setup an integration test build for Fedora 25 here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86/test-image-fedora-vmx

I have downloaded the binary and called:

* qemu-kvm VMX-Fedora-25.0.x86_64-1.25.1-Build7.1.raw

The image boots correctly and the dracut created initrd is not empty

**Comment by mmohring** [comment]
Some news: if I call the dracut call in a booted Fedora 26, it also provides an empty initrd:

$ cd /boot
$ dracut --force --no-hostonly --no-hostonly-cmdline --xz image-fedora-26-jeos.x86_64-1.0.0.initrd.xz 4.12.11-300.image-fedora-26-jeos.x86_64-1.0.0.initrd.xzfc26.x86_64
$ file image-fedora-26-jeos.x86_64-1.0.0.initrd.xz
image-fedora-26-jeos.x86_64-1.0.0.initrd.xz: ASCII cpio archive (SVR4 with no CRC)
$ cat image-fedora-26-jeos.x86_64-1.0.0.initrd.xz | cpio -itv
drwxr-xr-x   3 root     root            0 Aug 11 12:19 .
-rw-r--r--   1 root     root            2 Aug 11 12:19 early_cpio
drwxr-xr-x   3 root     root            0 Aug 11 12:19 kernel
drwxr-xr-x   3 root     root            0 Aug 11 12:19 kernel/x86
drwxr-xr-x   2 root     root            0 Aug 11 12:19 kernel/x86/microcode
-rw-r--r--   1 root     root        24070 Aug 11 12:19 kernel/x86/microcode/AuthenticAMD.bin
49 blocks

That means same behavior a booted Fedora 26 system.

**Comment by mmohring** [comment]
@schaefi I have looked into your image, and the initrd inside there is like the one from my example basically empty (except one file):

$ guestmount -a VMX-Fedora-25.0.x86_64-1.25.1-Build7.1.raw -i --ro ./T
$ cat T/boot/initramfs-4.12.11-200.fc25.x86_64.img | cpio -itv
drwxr-xr-x   3 root     root            0 Aug 11 14:23 .
-rw-r--r--   1 root     root            2 Aug 11 14:23 early_cpio
drwxr-xr-x   3 root     root            0 Aug 11 14:23 kernel
drwxr-xr-x   3 root     root            0 Aug 11 14:23 kernel/x86
drwxr-xr-x   2 root     root            0 Aug 11 14:23 kernel/x86/microcode
-rw-r--r--   1 root     root        24070 Aug 11 14:23 kernel/x86/microcode/AuthenticAMD.bin
49 blocks

So like the initrd from my example it contains only two files and no drivers. It might boot, but only because of the default settings of KVM. I might not boot with other settings, or if the kernel has not all the drivers compiled in.

**Comment by schaefi** [comment]
kiwi calls dracut explicitly with --no-hostonly and --no-hostonly-cmdline which sould lead to a generic host initrd. You are right it's not xz compressed and the initrd is almost empty

**Comment by schaefi** [comment]
Ah I found it :)

This about the microcode and initramfs combination. The cpio archive has a microcode blob is _before_ the initramfs blob. The microcode blob contains all kernel modules and drivers. If you want to check this create the initrd with:

* --no-early-microcode

That's all fine but I was also puzzled for a while :) after reading /usr/bin/dracut 
```
if [[ $create_early_cpio = yes ]]; then
  ....
```

things became clear

**Comment by schaefi** [comment]
The compression applies to the microcode if used, the cpio stays uncompressed which is ok

**Comment by ChaseCrum** [comment]
> I'm sorry but this can't be a problem of kiwi. I have setup an integration test build for Fedora 25 here:
> 
> * https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86/test-image-fedora-vmx
> 
> I have downloaded the binary and called:
> 
> * qemu-kvm VMX-Fedora-25.0.x86_64-1.25.1-Build7.1.raw
> 
> The image boots correctly and the dracut created initrd is not empty

this link is dead. CAN I PLEASE get a copy of your config xml you used there for the successful build????

**Comment by zzzoom** [comment]
I'm also getting an empty initrd when trying to build a Rocky 8 kis image, @mmohring @schaefi was this ever fixed?

**Comment by zzzoom** [comment]
Sorry for the mention, now I understand the post about `early_cpio`.
For people that arrive here through search engines, the initial microcode blob that is visible can be skipped using `/usr/lib/dracut/skipcpio`, which dumps the second blob with the real initrd.
