### ISSUE TITLE
kiwi grub config file is different from grub2-mkconfig result

### ISSUE THREAD

**Issue by mmohring** [SUSE/kiwi#496]
## Problem description
If a software update is performed on a VMX Image created with KIWI NG, the grub config created by KIWI is either ignored or broken by the update (e.g. kernel package).

## Intended behaviour
The grub config should be updated by a kernel update. This works, but not with the KIWI NG created grub config.

## Steps to reproduce the behaviour
1. create an image with KIWI NG for Fedora 25 / 26 or CentOS
2. perform a software update with dnf update or yum update
3. after the update, either the new kernel is not in the grub config or the system cannot boot at all

If you:
1. run grub2-mkconfig
2. run dnf update / yum update
3. reboot
then you get a modified grub boot menue where you can boot the new or the old kernels with different options.

**Comment by mmohring** [comment]
A copy of project for the KIWI NG for CentOS 7 and Fedora 25 / 26, git master, 9.11.3, is in b.o.o: https://build.opensuse.org/project/show/home:MartinMohring:KIWI-NG:Appliance
A copy of the project for the Image descriptions used is in: https://build.opensuse.org/project/show/home:MartinMohring:KIWI-NG:image

**Comment by schaefi** [comment]
How about adding a one time systemd script which just calls

* grub2-mkconfig

on first boot of the appliance. The unit file can be provided as overlay file and the activation of the unit is one line in the config.sh script

I'll give that a try in the fedora integration test I have but I think changing the kiwi generated grub config to be kind of distro compatible is not a good solution

Thoughts ?

**Comment by schaefi** [comment]
Here is my suggestion to solve this problem which you can try in your image description as well:

1. Create a oneshot systemd service unit file in your overlay tree:

* root/usr/lib/systemd/system/grub_config.service

```
[Unit]
Description=Rebuild grub config from distro toolkit

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'grub2-mkconfig -o /boot/grub2/grub.cfg'
ExecStartPost=/bin/bash -c 'rm -f /.kiwi_grub_config.trigger'
ConditionPathExists=/.kiwi_grub_config.trigger

[Install]
WantedBy=multi-user.target
```

2. Create the trigger file to meet the unit condition

* touch root/.kiwi_grub_config.trigger

3. Enable the service in your config.sh file

```
baseInsertService grub_config
```

I have added that concept to our test build here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86/test-image-fedora-vmx

and currently test it for Fedora

**Comment by schaefi** [comment]
Worked for me, see

* systemctl status grub_config

```
● grub_config.service - Rebuild grub config from distro toolkit
   Loaded: loaded (/usr/lib/systemd/system/grub_config.service; enabled; vendor 
preset: disabled)
   Active: inactive (dead) since Fri 2017-09-15 07:28:00 UTC; 5min ago
 Main PID: 389 (code=exited, status=0/SUCCESS)

Sep 15 07:27:56 localhost systemd[1]: Starting Rebuild grub config from distro t
oolkit...
Sep 15 07:27:57 localhost bash[389]: Generating grub configuration file ...
Sep 15 07:27:58 localhost bash[389]: Found theme: /boot/grub2/themes/starfield/t
heme.txt
Sep 15 07:27:59 localhost bash[389]: Found linux image: /boot/vmlinuz-4.12.11-20
0.fc25.x86_64
Sep 15 07:27:59 localhost bash[389]: Found initrd image: /boot/initramfs-4.12.11
-200.fc25.x86_64.img
Sep 15 07:28:00 localhost bash[389]: done
Sep 15 07:28:00 localhost systemd[1]: Started Rebuild grub config from distro to
olkit.
Sep 15 07:33:24 d14 systemd[1]: [/usr/lib/systemd/system/grub_config.ser
vice:8] Unknown lvalue 'ConditionPathExists' in section 'Service'
```

**Comment by schaefi** [comment]
@mmohring Let me know if that meets your needs. Thanks

**Comment by mmohring** [comment]
@schaefi interesting solution. Will try and comment.

**Comment by mmohring** [comment]
@schaefi I have tracked it down to a script which is called on a kernel update on CentOS/RHEL/Fedora, its "/usr/sbin/new-kernel-pkg". I try to find out why it fails to update grub.cfg correctly. Can you please not close this issue yet ?.

**Comment by Conan-Kudo** [comment]
@mmohring @schaefi That binary is part of [grubby](https://github.com/rhboot/grubby). You may want to investigate how grubby is used to generate the grub configuration.

**Comment by mmohring** [comment]
@Conan-Kudo That is exactly what I am doing, check what grubby is doing on an install of a kernel.

**Comment by Conan-Kudo** [comment]
(As an aside, this kind of stuff is why @vathpela is working on a Bootloader Spec implementation for GRUB 2...)

**Comment by schaefi** [comment]
@mmohring any news here ?

**Comment by schaefi** [comment]
@mmohring any news here ?

ETA to close this is set to: 2017-10-17
