### ISSUE TITLE
Cannot download package from OBS

### ISSUE THREAD

**Issue by magist3r** [SUSE/kiwi#50]
Hi! I want to test new kiwi version, but I can't download package from OBS. 
http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_42.1 - 404 Not Found

**Comment by tomschr** [comment]
I guess, the URL should be without the colon in "Appliances". Try this URL:

http://download.opensuse.org/repositories/Virtualization:/Appliances/openSUSE_Leap_42.1/

Closing this issue. Feel free to reopen it if this doesn't answer your question.

**Comment by magist3r** [comment]
Your URL is for old kiwi7.
In README I found this URL for OBS https://build.opensuse.org/package/show/Virtualization:Appliances:Builder/python3-kiwi. But there are no packages to download.

Please reopen.

**Comment by tomschr** [comment]
You are right. If I understood him correctly, Marcus hasn't created packages yet as it's not yet "feature complete".

**Comment by schaefi** [comment]
I have not hit the "publish" button, that's why you currently can't install the packages. I will announce and publish for testing by mid of April right after the new azurectl 2.0 release.

**Comment by schaefi** [comment]
what you can do today is:

```
osc co Virtualization:Appliances:Builder
cd python3-kiwi
osc getbinaries ...
rpm -Uhv ...
```

or directly from source within the virtualenv setup as documented in the README

Please be aware as long as no version has been published I'll take the freedom to do incompatible
changes :smile:

**Comment by schaefi** [comment]
Packages are available now

http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder
