### ISSUE TITLE
Not all xz compression steps use the xz options

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#507]
## Problem description
The tar command below won't utilize threading and/or the xz options provided by `~/.config/kiwi/config.yml` 

One solution would be to export the options with `XZ_OPT=`
## Actual behaviour
```
[  174s] [ INFO    ]: 01:40:40 | --> xz compressing archive
[  174s] [ DEBUG   ]: 01:40:40 | EXEC: [xz -f --check=crc32 --lzma2=dict=1MiB --threads=0 /usr/src/packages/KIWI-pxe/SLES12SP3.x86_64-1.42.3.initrd]
[  185s] [ DEBUG   ]: 01:40:52 | EXEC: [tar -C /usr/src/packages/KIWI-pxe -cJf /usr/src/packages/KIWI-pxe/SLES12SP3.x86_64-1.42.3.tar.xz SLES12SP3.x86_64-1.42.3-4.4.82-6.9-default.kernel SLES12SP3.x86_64-1.42.3.initrd.xz SLES12SP3.x86_64-1.42.3 SLES12SP3.x86_64-1.42.3.md5]
```
## Steps to reproduce the behaviour
Build image with `<type image="pxe" kernelcmdline="splash net.ifnames=1" boot="netboot/suse-SLES12" filesystem="btrfs"/>`

**Comment by schaefi** [comment]
Thanks, looking into it next
