### ISSUE TITLE
Run depmod after stripping kernel modules not before

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#508]
## Problem description
When using `<drivers>` or  `<strip type="delete">` to remove kernel modules, `depmod` is not ran afterwards, which makes for example modprobe believe these modules still exists, which causes it to try to load them at boot.

`depmod` is executed in `baseCreateCommonKernelFile`:https://github.com/SUSE/kiwi/blob/336429e7ccee56fd019557a265e260a8fc919ea8/kiwi/config/functions.sh#L1188
However that happens *before* the stripping functions here:
https://github.com/SUSE/kiwi/blob/336429e7ccee56fd019557a265e260a8fc919ea8/kiwi/config/functions.sh#L1261-L1274

Current behavior:
![kiwi-depmod1](https://user-images.githubusercontent.com/759887/30813671-57eb3f16-a20e-11e7-8617-fad34aa3dfb7.png)

## Intended behaviour
When `depmod` is ran after deleting the files;
![kiwi-depmod2](https://user-images.githubusercontent.com/759887/30813899-f41a4648-a20e-11e7-882a-1c34c117226b.png)

## Steps to reproduce the behaviour
1. Create kiwi image with `<drivers>` section, for example:
```xml
<drivers>
  <file name="drivers/acpi/processor.ko"/>
  <file name="drivers/edac/edac_core.ko"/>
  <file name="drivers/mfd/mfd-core.ko"/>
  <file name="kernel/arch/x86/kvm/kvm.ko"/>
</drivers>  
``` 
2. boot it

**Comment by schaefi** [comment]
@Jellyfrog would be great if you can have a look at the suggested patch. Thanks
