### ISSUE TITLE
Bad boot image config.xml files for SLE

### ISSUE THREAD

**Issue by mattc1170** [SUSE/kiwi#523]
KIWI boot descriptions for suse-SLES12 include openSUSE-release package in bootstrap list instead of sles-release package.

+ KIWI version: 9.11.10
+ Operating system: SLE 12 
+ OBS version: 9.11.10-52.1

**Comment by mattc1170** [comment]
Also:  the boot images for SLE also ask for ifplugd, which is not available in SLE repositories.

**Comment by schaefi** [comment]
I'll take a look
