### ISSUE TITLE
Add concept for schema documentation

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#53]
## Problem description

The documentation for kiwi consists out of the manual pages and the api documentation.
However there is no mechanism in place to create the schema documentation

## Solution suggestion

It would be nice to implement something like:

* add inline schema documentation in the `kiwi/schema/kiwi.rnc` file using ReST markup
* write an application which is able to extract the ReST markup from the RelaxNG schema in a form that python-sphinx can handle it. Ideally there is already a module in place which could do that but I could not find anything in the sphinx area for this
* integrate that source in the doc/ processing and auto publish like the rest of the docs

**Comment by tomschr** [comment]
Just for the record: Sphinx allows to create extensions (see [tutorial](http://www.sphinx-doc.org/en/stable/extdev/tutorial.html)). That could probably help.

**Comment by schaefi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yCNBYwb4&#x2F;186-kiwi-description-files-documentation"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Kiwi description files documentation</a>
