### ISSUE TITLE
obs_scm with root overlay causing permission problems

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#557]
## Problem description
When using obs_scm to get a root overlay .obscpio like so; https://build.opensuse.org/package/view_file/Virtualization:Appliances:Images:Testing_x86/test-image-oem/_service?expand=1
tar_scm service will create the "root" folder with chmod 700 as seen below:
```
[   62s]   3609    4 drwxr-xr-x   4 root     root         4096 Dec  1 12:20 /usr/src/packages/SOURCES/
[   62s]   3614    4 -rw-r--r--   1 root     root          401 Dec  1 12:20 /usr/src/packages/SOURCES/_service
[   62s]   9701    4 drwx------   3 root     root         4096 Dec  1 12:20 /usr/src/packages/SOURCES/root
[   62s]   9702    4 drwxr-xr-x   6 root     root         4096 Dec  1 12:20 /usr/src/packages/SOURCES/root/etc
[   62s]   9705    4 drwxr-xr-x   2 root     root         4096 Dec  1 12:20 /usr/src/packages/SOURCES/root/etc/profile.d
....
``` 
When rsync copies the overlay to the image-root:
`[   63s] [ DEBUG   ]: 12:21:10 | EXEC: [rsync -v -r -p -t -D -H -X -A --one-file-system --links /usr/src/packages/SOURCES/root/ /usr/src/packages/KIWI-oem/build/image-root]`

 it will also include the parent folders (`/usr/src/packages/SOURCES/root`) attributes as stated in the rsync man pages;
>A trailing slash on the source changes this behavior to avoid creating an additional directory level at the destination. You can think of a trailing / on a source as meaning "copy the contents of this directory" as opposed to "copy the directory by name", but in both cases the attributes of the containing directory are transferred to the containing directory on the destination.

This will cause `/` on the new image to have `drwx------` as seen below:
```
[   63s] [ DEBUG   ]: 10:02:06 | 655373    4 drwx------  24 root     root         4096 Dec  1 10:02 /
...
```

## Steps to reproduce the behaviour

1. Create a _service in OBS with:
``` 
    <service name="obs_scm">
        <param name="url">https://github.com/SUSE/kiwi.git</param>
        <param name="scm">git</param>
        <param name="subdir">build-tests/x86/test-image-oem/root</param>
        <param name="filename">root</param>
        <param name="version">_none_</param>
      	<param name="revision">master</param>
    </service>
```
2. add a `find / -ls` in `config.sh`
3. Observe permission of `/` in log output

## OS and Software information
+ KIWI version: 9.11.17
+ Operating system: SLES12-SP3
+ OBS version: 2.8

**Comment by schaefi** [comment]
Isn't this more a problem of the obs source service ?

How would we be able to influence that from the kiwi project ? or did I misunderstood the issue ?

Thanks
