### ISSUE TITLE
KIWI 9.11.5 - KiwiRootInitCreationError: TypeError: an integer is required

### ISSUE THREAD

**Issue by mmohring** [SUSE/kiwi#564]
## Problem description
The new kiwi version generates an error for all OS Targets and stops for all my config.kiwi files previosly working, 9.11.4 worked, 9.11.5 does not.

## Expected behaviour
Should work like version before, e.g. 9.11.4.

## Steps to reproduce the behaviour
1. replace old kiwi with new
2. rebuild old image description

## OS and Software information
+ KIWI version: 
Package for 9.11.25 from b.o.o Virtualization:Appliances:Staging/python-kiwi
+ Operating system: 
All target OS supported
+ OBS version: 
OBS 2.8 and git master

**Comment by mmohring** [comment]
Excerpt from the logfile:

[  131s] [ DEBUG   ]: 12:51:50 | EXEC: [mkdir -p /usr/src/packages/KIWI-vmx/build]
[  131s] [ INFO    ]: 12:51:50 | Loading XML description
[  132s] [ INFO    ]: 12:51:50 | --> loaded /usr/src/packages/SOURCES/config.xml
[  132s] [ INFO    ]: 12:51:50 | --> Selected build type: vmx
[  132s] [ INFO    ]: 12:51:50 | Preparing new root system
[  132s] [ INFO    ]: 12:51:50 | Setup root directory: /usr/src/packages/KIWI-vmx/build/image-root
[  132s] [ DEBUG   ]: 12:51:50 | EXEC: [mkdir -p /usr/src/packages/KIWI-vmx/build/image-root]
[  132s] [ DEBUG   ]: 12:51:50 | EXEC: [rsync -a --ignore-existing /tmp/kiwi_root.Rxa9_0/ /usr/src/packages/KIWI-vmx/build/image-root]
[  132s] [ DEBUG   ]: 12:51:50 | EXEC: [rm -r -f /usr/src/packages/KIWI-vmx/build/image-root]
[  132s] [ ERROR   ]: 12:51:50 | KiwiRootInitCreationError: TypeError: an integer is required
[  132s] [ INFO    ]: 12:51:50 | Cleaning up SystemPrepare instance

Do you need more ?

**Comment by mmohring** [comment]
Sometimes I also get the error:

[  117s] [ ERROR   ]: 12:52:45 | KiwiRootInitCreationError: TypeError: an integer is required (got type str)

Can you tell me which parameter it is complaining about ?

**Comment by mmohring** [comment]
I noticed that you get the same issue in b.o.o in your testing inside: Virtualization:Appliances:Images:Testing_x86/test-image-vmx test images.

**Comment by schaefi** [comment]
you mean 9.11.25 from Staging. I just noticed that the builds fail and are about to fix it

Thanks

**Comment by schaefi** [comment]
For the stuff you build you should not reference Staging if the builds are not only for testing
just in case you are not aware of it

**Comment by mmohring** [comment]
I just test git master automatically here.

**Comment by mmohring** [comment]
I tracked down the problem to:

kiwi/utils/sync.py: class DataSync: os.chmod(self.target_dir, target_entry_permissions)

**Comment by schaefi** [comment]
> I just test git master automatically 

ah ok, yeah so you will see failed builds here and there. This one was definitely because I did something stupid ;) but it should be fixed now and Staging builds should succeed next

**Comment by mmohring** [comment]
Only slightly stupid, not seriously stupid :=) Compared to others - only one such error per year 👍
