### ISSUE TITLE
handling all locales

### ISSUE THREAD

**Issue by cbosdo** [SUSE/kiwi#570]
## Problem description

The <locale> element doesn't allow all valid locales. For instance:

+ `C` or `POSIX`
+ All locales with more than two digits in the country or variant part (e.g. ''fur_IT'')
+ Locale `eo` doesn't match the pattern

## Expected behaviour

+ When setting `POSIX`, the /etc/sysconfig/language RC_LANG should contain `POSIX` value. Just changing the pattern to accept that value, the RC_LANG is set to `POSIX.UTF-8`, which seems to work.

## Possible change:

Changing the pattern from `[a-z]{2}_[A-Z]{2}(,[a-z]{2}_[A-Z]{2})*` to
`POSIX|[a-z]{2,}(_[A-Z]{2,})?(,POSIX|[a-z]{2,}(_[A-Z]{2,})?)*` could fly (Note, I didn't check that pattern thoroughly). And BTW, is <locale> actually accepting coma-separated locales?

**Comment by cbosdo** [comment]
of and BTW, setlocale's man also mentions it can have `@...` modifier after the codeset

**Comment by davidcassany** [comment]
Right, to what I could see the non capital letters code stands for language following [ISO-639](https://www.loc.gov/standards/iso639-2/php/code_list.php) standard which can be both, two or three letters (depending on the standard version) and the capital letters stands for the country following [ISO 3166](https://www.iso.org/obp/ui/#iso:pub:PUB500001:en) standard which represents countries in two capital letters. Moreover `POSIX` or `C`, should be considered also portable locales plus multiple codesets and very specific modifiers... Hard to support them all an prevent the inclusion of locales in a bad format.

I suggest just to update the pattern to include POSIX and, in addition, allow two or three characters for the language code. Still not perfect, as someone could enter a non existing value, but at least three characters languages would be supported and the same POSIX locale. I would stick to UTF8 and not consider any `@` modifier, after all there is no real user demand.

We could also consider the option of including a list of options into the schema, but then we would have to maintain it, even I don't think it would change that much. The list could be obtained by filtering the output of `locale -a` with only UTF8 values without any modifier. However I prefer just to slightly modify the schema pattern and include the POSIX exception into the code.
