### ISSUE TITLE
Support oem install image via dracut

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#576]
## Description

Creating an image of type oem with the installiso attribute activated creates in addition to the expandable disk image also an installation iso image which can be used to install (dump) the image on a target system and serves the purpose of a light weight installer

The implementation to drive this process is still part of the custom kiwi oemboot code and is the last part of the oemboot code which is not yet available as a dracut module package

## Plan

* Create a dracut-kiwi-dump package which provides the 90kiwi-dump dracut extension module to allow installation of kiwi images to a selected target disk

**Comment by schaefi** [comment]
Work is in progress in branch: dracut_kiwi_dump

**Comment by schaefi** [comment]
Once oem images with dracut supports all major components of oemboot the next question is how to handle the oemboot code ?

* As this is complex code which grew over years it should not be dropped but available in the kiwi-descriptions repo

* An extra package e.g kiwi-oemboot-descriptions could be created which provides the oemboot code and the descriptions for the distributions we want to support.

* obs could fetch that package if an image wants to build against oemboot via boot="/path/to/oemboot/description..."

Thoughts ?

**Comment by davidcassany** [comment]
I like the idea of removing the code from the main kiwi package, this is clear. Not sure if the boot code should be moved to kiwi-descriptions or not, it feels odd to me to have the bash code there. However I like the idea to move it to somewhere else as it forces us to clean the kiwi repo and to clearly divide what is part of the boot code and what is not part of it. 

I am also fine with having a new package that includes the boot descriptions and the boot code. I think that obs depending on the image type and on the presence of boot=".." could require this new package, probably I would even move some provides from `kiwi-boot-require` to the `kiwi-oemboot-descriptions` (i.e. `Provides: kiwi-boot:oemboot`).

**Comment by schaefi** [comment]
Thanks David for your feedback

> it feels odd to me to have the bash code there.

yes the legacy bash code should stick together with the legacy description(s) that's why I thought both should be moved to the kiwi-descriptions repo
 
>I am also fine with having a new package that includes the boot descriptions and the boot code. I >think that obs depending on the image type and on the presence of boot=".." could require this new >package, probably I would even move some provides from kiwi-boot-require to the kiwi-oemboot->descriptions (i.e. Provides: kiwi-boot:oemboot).

yes I agree and this will include some discussions with the obs people because they validate the provides from the kiwi-boot-requires package which I would like to get rid off too. Once there is no extra boot code this package will become obsolete

**Comment by schaefi** [comment]
I made good progress today with the oem dump, next steps are

* integrate kexec to boot after dump is done
* read and understand dracut's network support for oem install from remote

Once this is done all core components of boot features added by kiwi and not part of dracut are ported and we can think how to smoothly do the move

**Comment by schaefi** [comment]
Just to not forget about it:

* the documentation needs an update at several places when dracut is the default

**Comment by schaefi** [comment]
Last but not least there is this netboot code which I think should have its replacement in remote oem disk deployment. Meaning instead of writing boot code which does disk preparation (partitions, fs, etc...) and then dumping a filesystem image as rootfs it would be way more convenient to just dump a disk image and be done.

To my understanding we have two consumers of the netboot code

* slepos team (to deploy cash register machines)
* obs team (to deploy worker images)

The biggest problem with netboot is that there is an infrastructure connected to it. This means it's not only about the image but also about the connected services. Usually they are highly customized and people tend to add custom scripts like hell to their image builds. Of course this leads to a "never change" philosophy and that makes it hard for us to just say; switch to disk based deployment

That's why I think the netboot code can't be easily moved to dracut. However I think it can be moved to the kiwi-descriptions repo and maintained there. Maybe at some point in the future it could become legacy when it is clear that the people who need extra pxe boot code maintain all of it themselves anyway. My goal is that the kiwi builder itself keeps the capability to build pxe filesystem images but if they boot as expected depends on the initrd built from an external source we are at some point in the future no longer responsible for.

What do you think ? Is that feasible ? too harsh ?

any thoughts are welcome :)

Thanks

**Comment by davidcassany** [comment]
Right, I like the idea of moving also the PXE boot code at once together with the OEM one, having them separate is clearly a bad idea and removing OEM part from the main repo I'd say is a must in order to make firm steps towards dracut adoption.

> it would be way more convenient to just dump a disk image and be done.

Agree, just wondering how different it would be from a oem image with installpxe. Anyway I still have to visit closely the latest dracut-kiwi-dump code.

> The biggest problem with netboot is that there is an infrastructure connected to it. This means it's not only about the image but also about the connected services. Usually they are highly customized and people tend to add custom scripts like hell to their image builds. Of course this leads to a "never change" philosophy and that makes it hard for us to just say; switch to disk based deployment

I completely agree with that, I found my self hacking some stuff to make a virtual deployment with libvirt sometimes. Simplifying all netboot area would be wonderful, but I can see it could imply relevant changes to any current deployment.

> My goal is that the kiwi builder itself keeps the capability to build pxe filesystem images but if they boot as expected depends on the initrd built from an external source we are at some point in the future no longer responsible for.

I like how it sounds, but I don't really see/understand it. Which would be the difference between a filesystem image? In any case I am fine with the overall idea of leaving it as is at the moment, in some kind of maintenance mode and see how the demand for PXE evolves. 

Maybe, at some point in the future (obviously not so close) we can reconsider the capability of building the initrd images as another image type and completely remove the kiwi initrd build from the `system create` task. I imagine current PXE images but splited in two separate kiwi projects, one for the filesystem image another one for the initrd image; that way we provide the tooling to build it, but none of the boot code, just some dummy initrd example to use as a starting template in kiwi-descriptions at most.

**Comment by Jellyfrog** [comment]
Not sure I have much of value to add but here's how we use it at least, with about 25000 machines in production;

- `<type image="oem" ... initrd_system="dracut" ... boot="oemboot/suse-SLES12" installpxe="true">`
- `postprobe`-hook that does the imaging for various reasons, basically curl and dd combined
- `postmount`-hook that setup static IP and some more

So the flow is basically;
1. Pxe boot kiwi image
2. Kiwi triggers postprobe script
3. Own imaging of kiwi image
4. Kiwi expands the partition to max size
5. Kiwi triggers postmount script
6. Kiwi boots the new image

**Comment by schaefi** [comment]
Coding is complete with PR #580 

Next steps:

* Update documentation
* Copy kiwi boot code to kiwi-descriptions git repo
* Create package from kiwi boot descriptions (including meta sub-package for obs)
* Implement a kiwi patch to add the lookup path for legacy boot descriptions, so that boot="oemboot/..." resolves correctly
* Arrange a meeting with the obs team to clarify situation about provides tags in the obs meta package
* Delete kiwi boot descriptions from kiwi repo

@davidcassany thoughts, concerns, things I forgot :-)

Thanks

**Comment by davidcassany** [comment]
I think the next steps you noted are fine, I can't think of anything else right now. I believe that updating the documentation and the kiwi-descriptions repository (in order to include some dracut oem images) is quite relevant so we can provide some clear steps and examples to the users.

**Comment by schaefi** [comment]
> Update documentation

done

> Copy kiwi boot code to kiwi-descriptions git repo

done

> Create package from kiwi boot descriptions (including meta sub-package for obs)

done. Pending submission in request: ```osc rq show 574137```

**Comment by schaefi** [comment]
Meeting with obs people will happen in the week Feb 19th - 23th

**Comment by schaefi** [comment]
```
osc search kiwi-boot-descriptions

# Project                          # Package
Virtualization:Appliances:Builder  kiwi-boot-descriptions
openSUSE:Factory                   kiwi-boot-descriptions
```

will continue with the rest of the task list now

**Comment by schaefi** [comment]
Finally done, meeting with obs team scheduled for Monday next week
