### ISSUE TITLE
VMDK broken

### ISSUE THREAD

**Issue by tanderberg** [SUSE/kiwi#591]
## Problem description
VMDK file built from a superset of the suse-leap-42.3-JeOS example (packages added) can not be read by either VMWare Workstation Player or VirtualBox. The original example works fine. Suspect file size issue (calculated disk size is reported as 3389 MB, consistent with RAW size, actual VMDK size is 2521 MB).

## Expected behavior
Same as when the config.xml in
https://github.com/SUSE/kiwi-descriptions/tree/master/suse/x86_64/suse-leap-42.3-JeOS
is modified by adding format="vmdk" to the vmx type, i.e. KIWI should produce a VMDK file which can be mounted as a drive and read by VMWare Workstation Player and VirtualBox.

## Steps to reproduce the behaviour
Replace the config.xml in 
https://github.com/SUSE/kiwi-descriptions/tree/master/suse/x86_64/suse-leap-42.3-JeOS
with the one in
https://gist.github.com/tanderberg/48d6d41c406a901644c56be35a710c17

It 
1) adds format="vmdk" to the vmx type and
2) replaces the first set of packages with a larger superset (for a KDE desktop build) 
but is otherwise the same.

Build on Leap 42.3 with
kiwi-ng --type vmx system build --description kiwi-descriptions/suse/x86_64/suse-leap-42.3-JeOS

This produces a VMDK file which can not be read by either VMWare Workstation Player or VirtualBox. 
VMWare allows the file to be mounted as a drive but can't boot from it. VirtualBox reports "Could not get the storage format of the medium" (VERR_NOT_SUPPORTED) followed by:

Result Code: VBOX_E_IPRT_ERROR (0x80BB0005)
Component: MediumWrap
Interface: IMedium {4afe423b-43e0-e9d0-82e8-ceb307940dda}
Callee: IVirtualBox {9570b9d5-f1a1-448a-10c5-e12f5285adad}
Callee RC: VBOX_E_OBJECT_NOT_FOUND (0x80BB0001)

## OS and Software information
+ KIWI version: 9.11.30, 9.12.1 (installed with zypper) and latest master (following https://suse.github.io/kiwi/development.html)
+ Operating system: running KIWI on openSUSE Leap 42.3 (fresh virtual machine), VMWare and VirtualBox on Windows 10 Pro (64 bit)
+ OBS version: not using OBS, running locally

**Comment by davidcassany** [comment]
@tanderberg, I haven't been able to reproduce the issue with VMWare Player... I will try now with virtualbox. I only have linux hosts around here, but I doubt it really makes the difference... I am wondering if you could share the config.xml file. 

In my tests I have added big file in the overlay tree (1.5GB) and also included `patterns-openSUSE-kde` package to make the image way bigger, then I get a calculated disk size of 4133MB, which should be enough to reproduce the issue. My VMWare Players just works fine with the resulting image.

**Comment by davidcassany** [comment]
I can't also reproduce it in Virtualbox, the builds I have done are with KIWI 9.12.0 on a Leap 42.2 host and all my tests are green, I can normally boot with qemu-kvm, virtualbox and vmware player... 

@tanderberg , is it possible for you to test the same images in some other host? I am afraid I do not see any other relevant difference than having a Windows host.

**Comment by tanderberg** [comment]
> I am wondering if you could share the config.xml file

See linked gist under "Steps to reproduce the behaviour" above.

> the builds I have done are with KIWI 9.12.0 on a Leap 42.2 host

I have tried 9.11.30, 9.12.1 and now 9.12.4, all on Leap 42.3, all with the same result.

> is it possible for you to test the same images in some other host?

Yes, I have now

- copied the images previously produced to a Leap 42.3 host, and tried mounting them in VirtualBox (5.2.6 r120293 (Qt5.6.1)) and VMWare Workstation Player (14.1.1 build-7528167), with the same result;

- installed kiwi 9.12.1 on the same host, cloned https://github.com/SUSE/kiwi-descriptions/, replaced config.xml with the extended one (see above), and built again, with the same result.

So it doesn't seem to be a Windows problem.

> I am afraid I do not see any other relevant difference than having a Windows host.

I see at least two:

1) Based on your first reply, you don't seem to be using the config.xml I provided.

2) Based on your second reply, you are using Leap 42.2; I am on Leap 42.3. Installing kiwi causes a bunch of dependencies to be installed along with it; the problem could be in one of those, and we may be using different versions. Here's what I saw when I installed kiwi:

The following 27 NEW packages are going to be installed:                                            
  jing kiwi-man-pages kiwi-tools libibverbs libibverbs1 libmlx5-1 librados2 librbd1 liburcu0        
  multipath-tools python3-cffi python3-cssselect python3-docopt python3-future python3-kiwi
  python3-lxml python3-pycparser python3-six python3-xattr qemu-block-curl qemu-block-rbd qemu-tools
  rdma-core saxon6 squashfs xerces-j2 xerces-j2-xml-resolver

The following 3 recommended packages were automatically selected:
  jing qemu-block-curl qemu-block-rbd

27 new packages to install.

**Comment by davidcassany** [comment]
> See linked gist under "Steps to reproduce the behaviour" above.

Sorry I missed it from first read and just applied the changes you mention on the description. I have just executed another build with your config.xml with the same results... I can boot the image with:

* Virtualbox v5.1.32 (having the vmdk disk as SATA)
* VMware® Workstation 12 Player v12.5.7 (having the vmdk disk as IDE)
* Qemu-kvm v2.10 (command `qemu-kvm -m 2048 -hda LimeJeOS-Leap-42.3.x86_64-1.42.3.vmdk`)

Build host is an updated: openSUSE Leap 42.2
Using kiwi: kiwi-ng-3 v9.12.4

Gonna test to build in a Leap 42.3 and Tumbleweed host and see if this is an issue related to some updated underlaying tool.

**Comment by davidcassany** [comment]
@tanderberg I managed to reproduce the issue by upgrading Virtualbox... I could not install vmware player 14, something failed during the installation (I tested it with Tumbleweed an updated host, so it was likely to happen), but looks like its going to happen the same, wondering if vmware deprecated some vmdk version format.

Needs further investigation. At least I could reproduce it, this the first step.

**Comment by tanderberg** [comment]
Judging by
https://github.com/SUSE/kiwi/blob/master/kiwi/storage/subformat/vmdk.py
the heavy lifting is done by qemu-img (called by create_image_format to turn raw into vmdk). In Leap 42.3, 
qemu-img --v
reports version 2.9.1. What do you have on Leap 42.2?

**Comment by davidcassany** [comment]
All right, I did some progress with this issue. 

In kiwi we have a hack in order to tune the vmdk descriptor file and include the open-vm-tools version installed inside image (in case the system image includes it). It appends a couple of lines to the descriptor:

```
ddb.toolsInstallType = "4"
ddb.toolsVersion = "10110"
```

Apparently those lines are creating issues with current versions VirtualBox and VMPlayer. Up to now I could not find any relevant documentation about the vmdk descriptor file format, however I supose this lines are deprecated/outdated in some way. It is curious that VirtualBox 5.1 does not complain, but it does v5.2. VMWare Player 12 also does not complain and I could not test with VMWare Player 14, as the compilation of network modules fails in opensuse (tested with tumbleweed and leap 42.2). Qemu does not complain or fail in any case.

Now I am wondering if the motivation for `_update_vmdk_descriptor` method in DiskFormatVmdk is still valid, is there any infrastructure out there relaying in vmdk images formatted in that way?

@schaefi, do you have any hint about that? Is it something that can be considered outdated?

@tanderberg, could you test the same image but removing the open-vm-tools package from the config.xml? If this package is not present the `_update_vmdk_descriptor` is not executed and then the vmdk image remains untouched. Alternatively, you can also try to convert the image yourself with:

```bash
qemu-img convert -f raw LimeJeOS-Leap-42.3.x86_64-1.42.3.raw -O vmdk  LimeJeOS-Leap-42.3.x86_64-1.42.3.vmdk
```
And then the image should be just ready.

**Comment by schaefi** [comment]
> @schaefi, do you have any hint about that? Is it something that can be considered outdated?

yes the reason for this descriptor field update exists because when VMware runs an image it checks the vmware tools version and prints a warning message if it can't find this information. It results in less features vmware-tools are capable for, e.g mouse-to-image context and others.

The comment block of _update_vmdk_descriptor tries to explains that too ;)

If this is no longer required or even worse causes trouble I suggest to delete it. Less code is better

Other than that the suggested workaround with not installing vmware tools should have the same effect

**Comment by tanderberg** [comment]
@davidcassany, @schaefi, yes removing the open-vm-tools package produces a VMDK which works both with VMware Workstation Player and (with some residual weirdness) VirtualBox on Leap 42.3. 

The weirdness is that VirtualBox Manager still complains about "Invalid settings detected" (without additional details this time), but on Leap I can trick it into enabling the "OK" button by leaving the Storage dialog and then going back; clicking it then produces a virtual machine which seems to work fine. On Windows, "OK" stays grayed out no matter what I do, so I can't mount the VMDK.

With VMware Workstation I get a bootable machine also on Windows.

VMDKs produced on the command line using qemu-img work fine with both VirtualBox and VMware, on Leap and on Windows.

So it really seems that the culprit is the descriptor field update.

**Comment by schaefi** [comment]
ok thanks for the feedback. In this case I suggest we remove that metadata update.

@davidcassany are you going to prepare a patch for this one ?

**Comment by davidcassany** [comment]
> VMDKs produced on the command line using qemu-img work fine with both VirtualBox and VMware, on Leap and on Windows.

I am surprised that using the command qemu-img call you do not see the _residual weirdness_ but it appears with the kiwi image if no open-vm-tools package is installed... it should be the same.

Anyway it seams to be clear that the metadata update should not be there in any case. I'll make a PR for that. Thanks for your feedback
