### ISSUE TITLE
RPM backward compatibility

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#605]
## Problem description

Building Leap 42.3 or older images from a Tubleweed host results into an empty `.packages` file and into an empty `.verified` file, however the build ends successfully.

## Expected behaviour

The build ends successfully with valid `.packages` and `.verified` files.

## Steps to reproduce the behaviour

Build a pre-tumbleweed image using a tumbleweed host. The cause seams to be related to different RPM versions. At the very end KIWI does some rpm calls using the host tool to query and analyze the build image database, the RPM version differs form the one used by the image (which is older) and and, apparently, because of that fails to query the database.

The call
```bash
rpm --root <path to target dir>/build/image-root -qa
```
does not work if run after the image build. However
```bash
chroot <path to target dir>/build/image-root rpm -qa
```
does.

## OS and Software information
+ KIWI version: Irrelevant
+ Operating system: Tumbleweed
+ OBS version: none

**Comment by davidcassany** [comment]
We could work around that by calling rpm in a chroot, which, IMHO, actually makes sense as we would use the tools provided by the image to verify the rpm database. However that approach could lead to some failures in edge cases where the image does not include the rpm tool (very unlikely but possible if included in delete section or the image has just a bootstrap section). 

On the other side should be analyzed the root cause to verify our code is safe and that it is not an RPM bug.

**Comment by davidcassany** [comment]
Found the cause of it, #537 strikes back again, the issue appears when the host and the image have a different evaluation of the `%_dbpath` macro, which has been recently changed to a different default in current RPM versions.

I guess the update took into consideration to make some kind of symlink trick in current RPM packages making it possible to query the database of current rpm versions using the old path, that way the issue does not appear when building tubleweed images from a leap 42.2 host, but it appears the other way round.

**Comment by Conan-Kudo** [comment]
@davidcassany As much as I understand the reasoning behind changing the rpmdb location in SUSE distributions, this has been a big pain to work around. It's going to be very annoying for a while... :/
