### ISSUE TITLE
Building uefi system on host that does not have uefi results in error

### ISSUE THREAD

**Issue by rjschwei** [SUSE/kiwi#610]
## Problem description
[ ERROR   ]: 13:59:36 | KiwiBootLoaderGrubModulesError: Module synchronisation failed with: rsync: stderr: rsync: change_dir "/work/tmp/cb-leap-oem/build/image-root/usr/lib/grub2/x86_64-efi" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.0]

## Expected behaviour
Image creation succeeds or user is informed taht image cration is not possible on this host

## Steps to reproduce the behaviour
Use:
	<type image="oem" filesystem="xfs" boot="oemboot/suse-leap42.3" installboot="install" bootloader="grub2" firmware="uefi">

build on a host that does not have uefi enabled

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.12.7
+ Operating system:  host openSUSE 42.3
+ OBS version:

**Comment by schaefi** [comment]
From the error message to me this seems the image description requested efi but has not installed the package ```grub2-x86_64-efi``` kiwi searches the modules in the system root tree (/work/tmp/cb-leap-oem/build/image-root/ in your case) and not on the host machine which imho would be a mistake

Can you check if the package from above is installed in /work/tmp/cb-leap-oem/build/image-root/

Thanks
