### ISSUE TITLE
kiwi builds of CentOS 7 images fail from Fedora hosts (yum is not yum-deprecated in CentOS)

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#624]
## Problem description
KIWI fails to build CentOS 7 images using KIWI on Fedora 27 because it detects `yum-deprecated` on the host, but then tries to use that in the chroot, which doesn't work, since CentOS has Yum as `yum`.

## Expected behavior
KIWI should detect `yum-deprecated` on the host for bootstrap, and then detect `yum` for the chroot and use that for the Yum backend. That way, KIWI doesn't crash trying to build a CentOS 7 image.

## Steps to reproduce the behavior
1. On Fedora 27, enable the kiwi repo: `sudo dnf copr enable ngompa/KIWI`
2. Install kiwi: `sudo dnf install kiwi`
3. Grab the description for CentOS 7 and try to build it

## OS and Software information
+ KIWI version: 9.12.8
+ Operating system: Fedora 27 x86_64
+ OBS version: N/A

**Comment by schaefi** [comment]
@Conan-Kudo #633 open for review :)

**Comment by schaefi** [comment]
Would be great if you can give it a test on your fedora system. Thanks much

**Comment by Conan-Kudo** [comment]
@schaefi Will check ASAP! :D
