### ISSUE TITLE
Move from genisoimage to xorriso

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#635]
## Problem description

`genisoimage` (from `cdrkit`) is old and unmaintained. These days, the modern replacement available is from [`xorriso`](https://www.gnu.org/software/xorriso/), which looks like it supports all the features that exist in the RH/SUSE variant of `genisoimage`.

Please switch from `genisoimage` to `xorriso`.

## OS and Software information
+ KIWI version: 9.13.0
+ Operating system: Fedora 27, openSUSE Tumbleweed (20180218)
+ OBS version: N/A

**Comment by Conan-Kudo** [comment]
I'm also intending to move to xorriso for `livecd-tools`: https://github.com/livecd-tools/livecd-tools/issues/97

I've also filed a similar request for lorax: https://github.com/rhinstaller/lorax/issues/326

**Comment by schaefi** [comment]
I like the plan, we just need to keep an eye on the compat case when the build host for some reason has no xorriso. Especially for suse we need to check if sle15 has it

There is also this isoinfo tool we use and which is provided in a weird way either by cdrkit or the compat package. I guess xorriso only provides the plan isofs creation and no further tools or am I mistaken ?

**Comment by Conan-Kudo** [comment]
The `xorriso` tool itself has multiple modes. It can list, edit, create, and extract content from ISO filesystems. It just doesn't have legacy syntax support for anything except `mkisofs` (through `xorrisofs`).

**Comment by Conan-Kudo** [comment]
Full man page for `xorriso`: https://www.mankier.com/1/xorriso

Man page for `xorrisofs`: https://www.mankier.com/1/xorrisofs

**Comment by AdamMajer** [comment]
SLE-15 has both cdrtools and libisoburn. It would be great to remove all dependency on wodim and have it finally removed.

    SUSE:SLE-15:GA                    libisoburn
    openSUSE:Factory                  libisoburn
    openSUSE:Leap:15.0                libisoburn

**Comment by Conan-Kudo** [comment]
`cdrtools` is a non-starter because only SUSE has it in the distribution (how or why? I don't know. I don't particularly care to rehash that argument, either) and KIWI code needs to be able to work on other distributions. `xorriso` is the common tool everyone has.

**Comment by Conan-Kudo** [comment]
`libisoburn` is also in openSUSE Leap 42.x as well, starting with Leap 42.2.

**Comment by AdamMajer** [comment]
KIWI already works with both, `cdrkit` and `cdrtools`. And only `cdrtools` has any upstream.

Of course, adding support for `libisoburn` is perfectly fine.

**Comment by schaefi** [comment]
I'll start refactoring the iso part to let us integrate xorriso

**Comment by davidcassany** [comment]
:+1: I bet using xorriso can't be worse than using mkisofs and genisoimage friends.

**Comment by schaefi** [comment]
guess so too :-)
