### ISSUE TITLE
EFI should be selectable with MBR

### ISSUE THREAD

**Issue by agraf** [SUSE/kiwi#638]
## Problem description
We have a few systems that support (U)EFI boot, but do not support running with GPT, such as the Raspberry Pi.

For those systems, I need to override the partition label with MBR. Currently I do that with an editbootinstall script and manual invocation of gdisk to convert the GPT. That means however that tools like grub then also see a gpt instead of mbr and potentially generate an incorrect grub.cfg.

## Expected behaviour
I would like to be able to manually specify the partition label type.

## OS and Software information
+ KIWI version: 
+ Operating system: 
+ OBS version:

**Comment by Conan-Kudo** [comment]
This boils down to producing hybrid EFI/MBR partition schemes...

**Comment by agraf** [comment]
We used to do hybrid GPT/MBR back in the day, but most tools (like parted) ceased to support them. Basically all UEFI implementations support native MBR though, so there is very little reason in doing hybrid ones.
