### ISSUE TITLE
kiwi-repart dracut module looks like it gets interrupted

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#645]
## Problem description

Installing kiwi-repart and kiwi-dump dracut modules causes Tumbleweed images to not boot and some erratic behavior in Leap 42.3 images (repartition is not done properly)

## Expected behaviour

Tumbleweed images should boot and Leap 42.3 should boot with the appropriate repartition done. Up to now I could trace that installing `dracut-kiwi-oem-repart` and `dracut-kiwi-oem-dump` together causes this issue, intalling only `dracut-kiwi-oem-repart` produces the expected behavior. Looks like there is some sort of wrong interaction with these two modules.

## Steps to reproduce the behaviour

Build the oem image from the kiwi-descriptions (Leap 42.3) or the Tumbleweed image from `build-tests/x86/test-image-oem/`

## OS and Software information
+ KIWI version: 9.13.1
+ Operating system: Leap 42.2
+ OBS version: None

**Comment by schaefi** [comment]
I can not reproduce a problem with Leap42.3 but I can see the drop into the emergency shell on TW. systemd says something strange about an ordering cycle and drops into the shell, but all tasks were done properly

very strange

**Comment by davidcassany** [comment]
Yes very strange I am puzzled, yesterday afternoon I got mad with it. In Leap 42.3 what I see is that the image apparently boots fine but the image is not resized, no partition expansion. Running a `df -h` shows different size of what is expected.

I am running kiwi in Leap 42.2.

**Comment by davidcassany** [comment]
> In Leap 42.3 what I see is that the image apparently boots fine but the image is not resized, no partition expansion. Running a df -h shows different size of what is expected.

Ok you are right, in Leap it works fine, I did a wrong test. I did not realize the it was trying to make a swap partition of 4G and my disk was not big enough to hold the system partition plus the swap partition. Making the image way bigger solved the problem.

**Comment by davidcassany** [comment]
@schaefi, I did great progress on analyzing this issue, however I do not have yet a satisfying solution :disappointed:. I got a point where it might make sense a little discussion or some fresh eyes. 

The root cause of this issue is the `multipath-tools` package (which is pulled by `dracut-kiwi-oem-dump`) and it's `multipathd.service.` This is service is currently incompatible with `dracut-kiwi-oem-repart` hook of `pre-mount.service`.

`multipath.service` is part of the basic.target and it runs before the root device is found, thus it is also part of the `initrd-root-device.target`. During early boot some services are generated on the fly systemd generators and also configured by dracut. This is the case for `systemd-fsck-root.service` and `sysroot.mount` which is generated using the tool `/usr/lib/systemd/system-generators/systemd-fstab-generator`. This tool creates a the filesystem check service binded (is uses _BindsTo=<root.device>_) to the root device discovered by `initrd-root-device.target`, which is the device mapper device pointing to the real device. 

The problem is that our `kiwi-repart-disk.sh` script deactivates all device maps (in `deactivate_device_mappings` function), thus the original `*.device` unit that `systemd-fsck-root.service` is binded to it doesn't exist anymore after the repartition, thus the dependencies of `systemd-fsck-root.service` fail which makes also fail `sysroot.mount` as it requires `systemd-fsck-root.service`. We did not see it before because the dependencies of binded devices were nor properly or strictly checked in previous systemd versions, but reading the systemd.unit docs, this looks like the expected behavior even in previous versions.

In order to solve this issue I have thought about four different approaches:

- after deactivating all device maps reactivate them all again before ending `kiwi-repart-disk.sh`. So far I got no success with this approach, I tried to include `multipath -r` and `systemdctl restart multipathd` and the end of `kiwi-repart-disk.sh` without success, the device mappings are recreated but systemd-fsck-root.service still fails due to the `BindsTo` requirement. Probably recreated devices cannot be considered as equivalent for some reason or probably some event telling systemd that the root device is not there was already sent and the <root.device> unit already finalized. Not sure about what is actually failing here, the "*.device" units are quite confusing and hard to trace.

- another  idea I had is to rearrage `pre-mount.service` and `multipathd.service` dependencies to ensure multipath runs after the pre-mount.service. A simple test I did worked fine, but I really dislike this idea, since we loose multipath features at pre-mount and I think it could cause unexpected issues in later stages, as I believe multipath daemon is clearly expected to run in early boot stages. Also this implies messing around with services provided by other packages... IMHO looks like a path of pain.

- another approach I have is trying to not remove the device mappings. The test I did it only failed because of the filesystem checks before resizing, apparently tools like `e2fsck` have the perception that the device is in use when device maps are active, thus it fails to do the filesystem check. However I believe the removal of device maps was not only included only to avoid `e2fsck` failures but also to simplify the code, make it more robust and not suffer from issues like #649 (which was also triggered by `multipathd.service`). This option implies touching sensitive parts of `kiwi-repart-disk.sh`, making it more complex and hard to test.

- last but not least, I also thought about recreating again the `systemd-fsck-root.service` after the `kiwi-repart-disk.sh` with the new context. So far no success, but this is what I am currently experimenting, I am digging if there is a clean way to do that. I still don't know which service or event triggers the systemd-fstab-generator.

@schaefi, sorry for long explanation, I thought that was a good time for sharing thoughts, probably some fresh eyes have a new perspective or you can give some insights about why device maps are removed.

Any thoughts?
