### ISSUE TITLE
get_free_disk_bytes method from kiwi-partitions-lib dracut module does wrong calculation

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#648]
## Problem description

Get_free_disk_bytes does a wrong calculation of the free bytes. In order to get the free available space it makes the difference between the disk size and the addition of all partitions size, this is correct bbut `lsblk` can list the devices twice (meaning space used by partitions is counted twice) due to some device mapper and/or multipath issue.

## Expected behaviour

`lsblk` output just list the partitions once or the output is filtered in some way.

## Steps to reproduce the behaviour

- Build `suse/x86_64/suse-leap-42.3-JeOS/` oem image from kiwi-descriptions repository. 
- Resize the resulting image with `kiwi image resize` to 8GB.
- Boot the image with qemu, `qemu-kvm -m 2048 -hda LimeJeOS-Leap-42.3.x86_64-1.42.3.raw`
- At grub stage edit the kernel command line in order to add a pre-mount break point (add `rd.break=pre-mount rd.shell`) and boot
- At the pre-mount shell run `lsblk -r -p -o NAME,TYPE  /dev/sda`

Then you'll see how the output includes `/dev/sda[1-3]` partitions and it includes also some `/dev/mapper/QEMU_HARDDISK_QM00001-part[1-3]` partitions which are linked to some `/dev/dm-[0-3]` devices. No idea why are those devices there since we do not have any LVM configuration and also they are just present at this boot stage, they disappear after (at switch-root stage they are not there anymore).

## OS and Software information
+ KIWI version: 9.13.1
+ Operating system: Leap 42.2
+ OBS version: None

**Comment by schaefi** [comment]
you are right the function should be smart enough to handle that. I'll prepare a patch
