### ISSUE TITLE
overlay support for oem image type

### ISSUE THREAD

**Issue by magist3r** [SUSE/kiwi#65]
## Problem description

I really want to see overlay fs support for oem image type.
Additionally I think that there is no reason to use kiwi initrd for it (as kiwi 7 does), because it is possible to write overlay config to fstab: https://wiki.archlinux.org/index.php/Overlay_filesystem
## Actual behaviour

No support for overlay.

Feel free to ask for help :)

**Comment by schaefi** [comment]
help :)

**Comment by magist3r** [comment]
Ok :) 
I need a point where to start.

**Comment by schaefi** [comment]
Just for my own reference:

https://github.com/openSUSE/kiwi/issues/565

**Comment by schaefi** [comment]
ok so this is about compressed oem disk based on overlayfs and using the dracut initrd instead of the kiwi initrd

Before you start I'd like to ask:

```xml
<type image="iso" boot="isoboot/suse-leap42.1" flags="overlay" hybrid="true" firmware="efi"  hybridpersistent_filesystem="ext4" hybridpersistent="true"/>
```

hybrid iso is not an option for you because ?

```xml
<type image="oem" filesystem="btrfs" fsmountoptions="compress=lzo" boot="oemboot/suse-leap42.1" bootloader="grub2" firmware="efi" initrd_system="dracut">
```

compressed btrfs is not an option for you because ?

I'd like to understand the use case so that we can aim for the appropriate image type and that I can point you better to the code

Thanks

**Comment by schaefi** [comment]
All projects I'm aware of which tried to go productive with an overlayfs based rootfs changed their mind mostly due to stability and performance reasons. I see it fit very well for live systems but I'm still concerned for the oem usage

**Comment by magist3r** [comment]
Hmm. I think that compressed btrfs will be better than overlayfs. But I need one more option - "restore to factory defaults". In case of overlayfs I can simply format rw partition, but for btrfs I need recovery archive/partition. Unfortunately I have only 1Gb on my system.

Anyway I'll try with brtfs.

**Comment by magist3r** [comment]
Unfortunately btrfs compressed image is very big for me. LZO compression is much weaker than xz in squashfs.

**Comment by schaefi** [comment]
ok so for a disk with compressed read-only root you need an extra read-write partition. You can take a look at kiwi/builder/disk.py and there in __build_and_map_disk_partitions

I think we should also add an additional attribute e.g overlay_write_filesystem="...". The disk will then be created with the write partition containing the configured filesystem

That should be all from an image builder perspective. The rest takes place at boot time. For the kiwi initrd that will be the common boot code in boot/kiwi/functions.sh and the oem specific boot code in boot/arch/*/oemboot/...

dracut has no support for recovery as you want to use this feature, I think we need the kiwi
boot code here at least for the first boot to setup the recovery setup

you should also test if the dracut initrd can reboot the disk with the overlay root structure

The complete chain consists of quite some tasks but we can do it in small steps

Hope that helps

**Comment by magist3r** [comment]
Ok.
First thing that is unclear to me: how to calculate ro partition size, i.e. xz compressed squashfs?
Second: size of loop device for raw image is calculated from plain rootdir size, not compressed one.

**Comment by schaefi** [comment]
I have started a branch which implements the basic disk setup. We are still missing

1. XML attribute e.g root_is_overlay="true|false"
2. kiwi boot code to boot such a disk
3. check if dracut can boot it (so far I think it can't) and best provide a dracut extension to support this setup which we could deliver with the package. This would allow us to use initrd_system="dracut" instead of the kiwi boot code

I will be able to work on 1. and 2., it would be totally great if you can double check on dracut

**Comment by schaefi** [comment]
Issues I have found so far which are not addressed:

1. grub2-mkconfig is in trouble if the underlaying root file system is overlayfs, it fails with
    cannot resolve canonical path of ...

2. dracut support for root on overlayfs, needs investigation and I think dracut can't do that

All the rest is done, I'll submit a pull request next

**Comment by magist3r** [comment]
Wow. Nice work!

I'll test it soon and try to find solutions/workarounds for current issues.

**Comment by magist3r** [comment]
Ok, I fixed grub2 and created patch and SR here: https://build.opensuse.org/request/show/419896
You can use package from my repo https://build.opensuse.org/package/show/home:magist3r:branches:Base:System/grub2 to test it. 

For now at least kiwi7 with patched grub2 creates config files with overlayfs normally. Will test kiwi8 soon.

**Comment by schaefi** [comment]
This is great thanks for looking into the grub2 issue

**Comment by Conan-Kudo** [comment]
@schaefi Just as a note, dracut 045 and newer supports OverlayFS for live boots: https://github.com/dracutdevs/dracut/blob/39c9b67f86145953aa30def9d77c68597a4ccfe8/NEWS

**Comment by schaefi** [comment]
I've built an image with this type setup:

```xml
<type image="vmx" filesystem="ext3" overlayroot="true" bootloader="grub2" kernelcmdline="splash" boot="vmxboot/suse-tumbleweed"/>
```

and that worked, when I moved to dracut via

```xml
initrd_system="dracut"
```

the result boots up but I land in a systemd rescue shell. I guess the image like we built it does not provide the expected structure to work with dracut and/or additional boot parameters are missing

So the only part left is

* dracut support for root on overlayfs disk images. The kiwi generated disk has a boot partition
  and a squashfs compressed root partition and a third partition to be used in an overlayfs mount
  to store the copy-on-write data

**Comment by schaefi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support kiwi overlay systems in dracut](https://trello.com/c/wzmKNzsS/144-support-kiwi-overlay-systems-in-dracut)
