### ISSUE TITLE
Quick info/feature request regarding the plabel=ROOT

### ISSUE THREAD

**Issue by andrey01** [SUSE/kiwi#66]
Dear @schaefi  ,
when kiwi builds the image, the rootfs has the `LABEL=ROOT` on blkid,
however our puppets want it to be `LABEL="/"`

Would it be possible to add some option so we can explicitly specify the `LABEL=` inside the `config.xml` ?
And what hook would be the best to use at this current stage ?
We are currently using the kiwi legacy (v7), where I leveraged the preCallInit.sh to enable the SELinux for RHEL6.

**Comment by schaefi** [comment]
yep custom root label makes sense, let's add that

**Comment by schaefi** [comment]
In v7 the root label setup is in

https://github.com/openSUSE/kiwi/blob/master/modules/KIWIBoot.pm#L2603

I have no plans for the moment to change that code. Maybe you can go with a custom patch for your use case in v7 ? Let me know what works for you

Thanks

**Comment by andrey01** [comment]
okay, instead of modifying the hardcoded ROOT label, the hook has solved our problem :-)

**/kiwi-hooks/preCallInit.sh**

```
#!/bin/sh

#======================================
# Set correct label to the rootfs device
#--------------------------------------
tune2fs -L "/" $(findmnt -n -o SOURCE /)
```

**Comment by schaefi** [comment]
right that works too, good catch

**Comment by schaefi** [comment]
I'm going to add the following attribute to set the label

```xml

<type ... rootfs_label="name"/>
```
