### ISSUE TITLE
Add "arch" attribute for repositories

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#671]
For `imageonly=true` repositories, the `arch` attribute would be useful, as the URLs might be different for each architecture.

This can be worked around by having a profile for each arch and enable the repo only for the matching profile.

**Comment by davidcassany** [comment]
I have some doubts this is the way to go, since repositories already have their architecture logic. The package manager only exposes to the system the packets with the matching architecture. I understand your use case, when we have arch specific repositories it doesn't have much sense to include them all for all architectures, but, IMHO, this is a kind of weakness of the repositories rather than a missing feature in KIWI.

Apart from that, as you noted, repositories can be profiled using arch specific profiles. I think this should be enough.

Any further thoughts?

**Comment by Vogtinator** [comment]
> I have some doubts this is the way to go, since repositories already have their architecture logic. The package manager only exposes to the system the packets with the matching architecture. I understand your use case, when we have arch specific repositories it doesn't have much sense to include them all for all architectures, but, IMHO, this is a kind of weakness of the repositories rather than a missing feature in KIWI.

This is unfortunately the case for every distro split into main project and ports. That means openSUSE Leap and Tumbleweed.

**Comment by Conan-Kudo** [comment]
It's also true for distributions that can't use the `$basearch` variable in the repo URLs for automatic substitution, such as Mageia.

Only Red Hat/Fedora repositories are okay with the current situation, since they use `$basearch` and have variable substitution done by the package manager.

**Comment by Vogtinator** [comment]
> Only Red Hat/Fedora repositories are okay with the current situation, since they use $basearch and have variable substitution done by the package manager.

libzypp does that as well, the issue here is that the projects don't include it.

`http://download.opensuse.org/aarch64/tumbleweed/repo/oss/` vs.
`http://download.opensuse.org/ports/aarch64/tumbleweed/repo/oss/`

**Comment by Conan-Kudo** [comment]
You guys also don't use `$releasever` for variable substitution to make upgrades easier either, even though Zypper supports it.

**Comment by Vogtinator** [comment]
> You guys also don't use $releasever for variable substitution to make upgrades easier either, even though Zypper supports it.

With Leap 15.0 we do.

**Comment by Conan-Kudo** [comment]
@Vogtinator, what, really? Does that mean you're shipping the repo files in a package rather than having something just do `zypper ar` all the time?

**Comment by Vogtinator** [comment]
> @Vogtinator, what, really? Does that mean you're shipping the repo files in a package rather than having something just do zypper ar all the time?

No, the repos are added by yast during installation.

**Comment by schaefi** [comment]
I agree to what David said. If the repo setup should be arch specific it can be done by arch specific profiles. For handling imageonly repo defintions you can also think of doing this completely outside of the image description in an extra script which handles this part arch specific. As yast already has code for it, that part probably can be re-used
