### ISSUE TITLE
Setup pypi deployment automation

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#678]
## Problem description

Update of the pypi archive is still a manual task. Done by calling ```make pypi```
I have tried to automate that via travis but it failed in the past. I think it's time to bring up this as an issue

* https://docs.travis-ci.com/user/deployment/pypi/

**Comment by schaefi** [comment]
Maybe an interesting read with regards to the problem here:

* https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html

**Comment by matwey** [comment]
Hi, I deploy to PyPi from Travis-CI for some my project. 
Fell free to grab an example from .travis.yml
https://github.com/matwey/pybeam

**Comment by davidcassany** [comment]
@matwey, we will have a look, thanks much
