### ISSUE TITLE
Multiple nics in machine settings file not possible

### ISSUE THREAD

**Issue by cybernard** [SUSE/kiwi#688]
## Problem description
I can only get 1 network card no matter what I do.
<machine ovftype="vmware" memory="2048" guestOS="other3xlinux-64" arch="x86_64" HWversion="10">

                        <vmdisk controller="lsilogic"  id="0"/>
                        <vmnic driver="e1000" interface="0" mac="00:0c:29:53:20:56"/>
                        <vmnic driver="vmxnet" interface="1" mac="00:0c:29:53:20:60"/>
                        <vmnic driver="vmxnet" interface="2" mac="00:0c:29:53:20:6a"/>
                        <vmnic driver="r8169" interface="3" mac="00:0c:29:53:20:74"/>
                        <vmnic driver="vmxnet" interface="4" mac="00:0c:29:53:20:7e"/>
</machine>

## Expected behaviour
I am expecting to see 5 network cards inside my virtual machine build.  The generated vmx file only has 1 network present

## Steps to reproduce the behaviour

This config with the build command.
[config.xml.txt](https://github.com/SUSE/kiwi/files/1880146/config.xml.txt)
sudo kiwi-ng  --logfile="kiwi-ova.log" --profile=ovf system build --description /kiwi/kiwi-descriptions/suse/x86_64/suse-tumbleweed-firewall     --target-dir /tmp/myimag2

## OS and Software information
+ KIWI version:  9.14
+ Operating system: opensuse-tumbleweed
+ OBS version:  using kiwi-ng from command line, and not using confusing OBS system.

**Comment by schaefi** [comment]
The information from the machine section are used by kiwi to create a vmware settings file with the extension .vmx At the moment only the first nic setup is added there which is a bug in kiwi

As workaround you can use the generic vmconfig entry

```xml
<vmconfig-entry>raw text</vmconfig-entry>
```

but that implies you know the format of the virtual machine settings file

**Comment by schaefi** [comment]
Will fix this bug next
