### ISSUE TITLE
If stripKernelModule is active and (efi or uefi) or fat or vfat please add vfat to the dependancies list

### ISSUE THREAD

**Issue by cybernard** [SUSE/kiwi#692]
## Problem description

If any part of the build uses a FAT16/32 file system please add vfat to the **dependencies** array.
In addition EFI or UEFI both need vfat module dependencies.

in addition 2 un-announced dependencies exist
     fs/nls/nls_cp437.ko
     fs/nls/nls_iso8859-1.ko

modinfo -F depends
modprobe --show-depends 
neither of these functions acknowledge these dependencies.

I filed a kernel.org bug for this, but since all previous kernels suffer from this it might be a good idea to add them to the dependencies array.  I have found forum entries from people with the same issue back to 2008.

The function baseFixupKernelModuleDependencies activated by stripKernelModule needs to know about these requirements.

The created system will fail to boot complaining vfat isn't supported file system.

## Expected behaviour
system boots normally.

## Steps to reproduce the behaviour
add stripKernelModules to config.sh
select any build with the efi or uefi firmware
delete the incorrect dracut check from stripKernelModules in the function.sh located in kiwi/config/ folder

## OS and Software information
+ KIWI version:  9.14.1
+ Operating system:  openSuse tumbleweed
+ OBS version: none

**Comment by davidcassany** [comment]
For iso images this is already solved in KIWI 9.14.2. 

The dracut check in stripKernelModules is not considered to be wrong and vmx and iso builds works fine without this hack. See https://github.com/SUSE/kiwi/issues/691#issuecomment-379749491 explanation about that topic.
