### ISSUE TITLE
problems with spec file in OBS in Virtualization:Appliances:Builder

### ISSUE THREAD

**Issue by dsamx** [SUSE/kiwi#703]
## Problem description
The spec file in OBS has a typo in a version check (missing question mark) in l160.
The kiwi-boot-requires is also required on rhel, the suse check should be removed.
l134 is overly complicated, the echo, cut and backticks should be removed, just use grep. Also a comment should be added that describes that line because distros not listed in the grepped file will get a build failure due to an empty requirement.

Solution: See the spec file in https://build.opensuse.org/package/show/Virtualization:Appliances:Builder/kiwi-boot-descriptions

I would have simply submitted the package change because the spec file is not included in the github sources but submitting is forbidden and a message appeared that I should report issues here.

**Comment by schaefi** [comment]
The github sources which builds the kiwi-boot-descriptions package can be found here:

* https://github.com/SUSE/kiwi-descriptions/

Would be great if you can make your adaptions to:

* https://github.com/SUSE/kiwi-descriptions/blob/master/custom_boot/package/kiwi-boot-descriptions.spec

and send us a pull request on github, it's all open :)

> and a message appeared that I should report issues here.

That should then be fixed. Could you tell which part in the kiwi-descriptions repo pointed you to the kiwi repo ?

Thanks much

**Comment by dsamx** [comment]
I tried to submit to Virtualization:Appliances:Builder and got the message

```
Unable to submit: The target project Virtualization:Appliances:Builder is not accepting requests because: The python-kiwi packages are developed at Github (https://github.com/SUSE/kiwi) and are submitted to OBS from there. Also see (http://suse.github.io/kiwi/development.html) for further information. You can contact kiwi developers at #kiwi irc.freenode.org or kiwi-images@googlegroups.com mailing list. 
```

**Comment by schaefi** [comment]
yes this is correct. The source code including the package files, spec, changes etc are all maintained in github repositories. This is why submissions to obs are disabled. The workflow is as follows:

* fork the git repo you plan to make changes for. In your case this would be https://github.com/SUSE/kiwi-descriptions/
* make your changes in the checked out fork, this would be the file ```custom_boot/package/kiwi-boot-descriptions.spec``` in your checked out copy
* commit the changes
* create a pull request for the origin of your fork

* we now see your work and will merge it
* in the next scheduled submission of the package all your changes will be applied and you can see them in obs too

Makes sense ?

**Comment by schaefi** [comment]
any news ?

**Comment by dsamx** [comment]
no, I am too busy at the moment to deal with it. Maybe CW18.

**Comment by schaefi** [comment]
I'm going to close this one here now as we can't do much with it and it's also an issue for the https://github.com/SUSE/kiwi-descriptions/ repo. Let us know when this needs further attention.
Thanks
