### ISSUE TITLE
KIWI requires xorriso on CentOS-7 and SLE-12

### ISSUE THREAD

**Issue by mmohring** [SUSE/kiwi#711]
## Problem description

The current git master KIWI .spec template makes KIWI require xorriso for CentOS 7 and SLE 12. This package does not exist for those distro versions.

## Expected behaviour

KIWI should work without xorriso on CentOS 7 and SLE 12 ?

## Steps to reproduce the behaviour

1. Build the KIWI package for those targets using the current git master .spec template
2. Build a package with the  KIWI 9.14.1 version installed into OBS
3. Change the used KIWI package to the current git master .spec file in OBS in your builds
4. After the build of the new KIWI package you get an expansion error "nothing provides xorriso"

## OS and Software information
+ KIWI version: later than 9.14.2
+ Operating system:  Any CentOS 7 or SLE 12
+ OBS version: 2.9 or later

**Comment by schaefi** [comment]
The master kiwi has moved to xorriso yes and we are very happy to get rid of all the cdrtools mess
I'm aware that sle12 is not shipped with xorriso which is the reason why the official sle12 version has not been ported to xorriso. The latest tree however did the move but with respect to xorriso available for all distros. SLE12 provides it in multimedia:libs and CentOS has it in the epel tree

* https://build.opensuse.org/package/binaries/multimedia:libs/libisoburn/SLE_12_SP3
* https://centos.pkgs.org/7/epel-x86_64/xorriso-1.4.8-1.el7.x86_64.rpm.html
