### ISSUE TITLE
Confusion with SUSE/kiwi and openSUSE/kiwi

### ISSUE THREAD

**Issue by sysrich** [SUSE/kiwi#712]
Shouldn't we rationalise these github repos so it's obvious between the differences between SUSE/kiwi and openSUSE/kiwi?

Which is the primary one for issues?

Which is the one under active development?

**Comment by schaefi** [comment]
I agree with you, it should be obvious, let's find a way to better outline it.

So openSUSE/kiwi is the legacy v7 kiwi version in maintenance mode and still in use on distributions <= SLES12 or <= Leap42.1. The readme on the toplevel project page says:

```This version of kiwi is in maintenance mode. Further development takes place in the following project: ...```

I thought this would answer the question on active development

Issues can be filed according to the version you used. If it's kiwi v7.x.x it's openSUSE/kiwi of it's anything newer it's SUSE/kiwi

In the documentation of the next generation project there is the article:

* http://suse.github.io/kiwi/overview/legacy_kiwi.html

where I tried to say some words about the move and its reasons. I guess it's not easy to find

It would be great if you can share your thoughts how to improve here from your perspective  

Thanks

**Comment by schaefi** [comment]
Also see #685 There is a similar problem with the documentation. The v7 documentation has been handed over to the doc department at suse whereas the next generation docs are handled in the same way like code and are part of the project itself based on sphinx.

Apart from the version which brings docs and code together I currently have no good idea how to avoid confusion

**Comment by Conan-Kudo** [comment]
It would probably be better if they were both under the same organization, and old kiwi was called something like "kiwi-legacy" and new kiwi was just "kiwi".

**Comment by schaefi** [comment]
Unfortunately a rename of the repo as suggested is not an option. The documentation which is already used in the enterprise product references openSUSE/kiwi at several places as well as many image descriptions. If we start a rename here I fear the confusion will become bigger.

The following has been done to make people aware of the role of both projects:

* http://opensuse.github.io/kiwi/ automatically redirects to https://suse.github.io/kiwi/overview/legacy_kiwi.html
* The topic of https://github.com/openSUSE/kiwi indicates reading the deprecation notice
* The README of https://github.com/openSUSE/kiwi explains the scope and deprecation plan
* The project https://github.com/openSUSE/kiwi  does not allow for issues anymore as we only fix if reported on bugzilla, see deprecation notice

If the time comes https://github.com/openSUSE/kiwi will be archived.

I think the initial questions has been answered:

* Which is the primary one for issues?
   only SUSE/kiwi has issue reporting activated now

* Which is the one under active development?
   should be clear by the deprecation information and the redirect

Hope this improves the situation
