### ISSUE TITLE
Kiwi errors out if the target's LVM name is a substring of the host's LVM name

### ISSUE THREAD

**Issue by kamakazikamikaze** [SUSE/kiwi#721]
## Problem description
When building an OEM system and specifying the `<systemdisk name=". . .">` option, Kiwi throws an error if the target's systemdisk LVM name is also a substring of the hosts's LVM name. For example, a host with an LVM of "SystemLVM" will cause an error in Kiwi if a description for an OEM build with a target LVM of "System" is specified. However, if the host has an LVM named "System" and the target LVM is named "SystemLVM", no such error is raised.

## Expected behaviour
Kiwi should not produce errors unless an LVM with the same exact name already exists on the host.

## Steps to reproduce the behaviour
1. Create a logical volume on the machine where Kiwi is installed. The name can be anything, ex. "SystemLVM"
2. Create a config.xml with a systemdisk option, ex. `<systemdisk name="System">`
3. Kick off the build process
4. After packages are unpacked, Kiwi will check for existing LVMs. At this point, an error that an LVM matching "System" will be raised.

## OS and Software information
+ KIWI version: 9.14.2
+ Operating system: SuSE Linux Enterprise Server 12 SP 3 (SLES 12 SP3)
+ OBS version: (What is OBS?)

**Comment by schaefi** [comment]
Thanks, yes you are right. So you know the code and the line and the proper fix :+1: now we only need a method to turn words into code :smile: 

I'll prepare a fix next

We are happy for any contributions, maybe next time feel free to send your thoughts in a pull request.
