### ISSUE TITLE
Don't compress docker tar balls anymore in bundler

### ISSUE THREAD

**Issue by adrianschroeter** [SUSE/kiwi#725]
## Problem description
Don't compress docker tar balls with xz anymore in bundler code.

The OBS is about to store them in a registry like storage, so our build script is uncompressing the
tar.xz (but keeps the tar ball). So this is just eating time and CPU cycles now, just skip xz compression
for files like

 my_container.x86_64-1.0.0-Build1.1.docker.tar

please

**Comment by schaefi** [comment]
ok

**Comment by schaefi** [comment]
Looking closer to the code I see that it's not the bundler which compresses the docker tarball it's the ContainerImageDocker class which does that on purpose.

Also we document to load a docker image via

```
docker load -i docker-image.tar.xz
```

Thus loading a docker image via the docker toolchain works with compressed images and that imho means it's good that we create compressed tarballs

Changing this has an impact on existing output results as it's not the bundler but the container builder itself. Therefore I think it wouldn't be a good move from that perspective

@davidcassany What do you think ?

I would say the default output should stay a compressed tarfile as this is expected by our users.
But we can offer a runtime config switch which makes this configurable. The buildservice could then make use of it

Thoughts ?

**Comment by adrianschroeter** [comment]
On Mittwoch, 9. Mai 2018, 15:27:49 CEST wrote Marcus Schäfer:
> Looking closer to the code I see that it's not the bundler which compresses the docker tarball it's the ContainerImageDocker class which does that on purpose.
> 
> Also we document to load a docker image via
> 
> ```
> docker load -i docker-image.tar.xz
> ```
> 
> Thus loading a docker image via the docker toolchain works with compressed images and that imho means it's good that we create compressed tarballs
> 
> Changing this has an impact on existing output results as it's not the bundler but the container builder itself. Therefore I think it wouldn't be a good move from that perspective
> 
> @davidcassany What do you think ?
> 
> I would say the default output should stay a compressed tarfile as this is expected by our users.
> But we can offer a runtime config switch which makes this configurable. The buildservice could then make use of it

so we would need to detect kiwi versions again to learn if we can use that option? 

Don't like that very much ... could you check for /.buildenv and skip compression
in this case (running in build script)?

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by davidcassany** [comment]
Damn, you all responded while I was writing XD

> Changing this has an impact on existing output results as it's not the bundler but the container builder itself. Therefore I think it wouldn't be a good move from that perspective

I fully agree with that idea. In general this would impact to any existing docker build, which is dangerous, also docker is already capable of consuming compressed images, the same as skopeo. However both docker and skopeo can't produce compressed images by themselves and both are also capable to read non compressed tarball images. So probably this could be considered an almost transparent change for the user, as docker loading wouldn't be effected.

In addition, KIWI uses `skopeo` which creates uncompressed tarballs that include compressed layer blobs (meaning the rootfs has already some compression). I did a quick test and the [opensuse image](https://github.com/SUSE/kiwi-descriptions/tree/master/suse/x86_64/suse-tumbleweed-docker) we have as an example compressed weights 39MB and it weights 40MB after uncompressing (while the loaded image weights 103MB according to docker).

So my opinion is that we could evaluate to not compress the image.

> could you check for /.buildenv and skip compression in this case (running in build script)?

I don't like this idea, neither I like some packages have installation scripts depending on that, this sort of black magic is hard to debug.

> you create a runtime config file ~/.config/kiwi/config.yml and put data in like it is already done

I am also fine with this idea. It allows us to keep the current behavior without having to include extra tags/attributes into the schema.

**Comment by schaefi** [comment]
ok, I'll come up with a pull request soon
