### ISSUE TITLE
Support files inclusion outside the compressed area in liveCDs

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#737]
Comes from the `Kiwi-NG: cdroot` thread in the mailing list

## Problem description

Former KIWI versions used to support `config-cdroot.tgz` and `config-cdroot.sh` files in order to handle files that are not included into _squashfs_ image.

According to the users in mailing list, this is specially handy when some very big files (probably already compressed) need to be included in to LiveCD and the compression/decompression related steps are so demanding in terms of CPU cycles.

Being capable to include files into the ISO apart of the compressed FS was possible with former KIWI and is causing issues to users migrating to KIWI-NG.

## Expected behaviour

KIWI-NG can include files out of the squashfs image is ISO's. Ideally it should be possible to include files without having to use a compressed tarball (unlike in former KIWI with `config-cdroot.tgz`).

## Steps to reproduce the behaviour

Kiwi-NG ignores `config-cdroot.tgz` file if present.

**Comment by schaefi** [comment]
True and one part I overlooked in feature migration from legacy kiwi to next generation kiwi.

I agree this feature should be available in kiwi-ng. If possible I'd like to avoid having another script entry in the processing with config-cdroot.sh. Adding static user data like licenses, documentation or similar to the iso is good, but no further custom script code if possible

**Comment by davidcassany** [comment]
Great, I also think it makes sense. I'd also prefer to not include any other additional script hook if possible. At least for the use case that raised this issue it looks like it might not be needed.

I also believe it is quite interesting the point noted in the mailing list, that would be nice to not force the source data files to be compressed. I believe allowing a simple uncompressed tarball should be enough, actually, I'd say that any format that can be handled by `kiwi/archive/tar.py` should be valid.

**Comment by schaefi** [comment]
yes I agree completely, let us do it that way :+1:

**Comment by schaefi** [comment]
back from vacation: I'll take this one
