### ISSUE TITLE
Add labels to partitions

### ISSUE THREAD

**Issue by kamakazikamikaze** [SUSE/kiwi#738]
Root, boot, efi, and swap partitions are created using labels. Is it possible to extend this to allow users to set their own custom labels for partitions?

For example:

```xml
<systemdisk name="System">
  <volume name="tmp" size="10G" label="tmp"/>
  <volume name="mysql" size="30G" mountpoint="/data/mysql" label="mysql"/>
  <volume name="home" size="5G" label="misleadinglabel"/>
</systemdisk>
```

**Comment by davidcassany** [comment]
I guess this is something that could be considered, at first sight I don't see any reason preventing it to be possible.

**Comment by davidcassany** [comment]
The root label is already possible to have a custom value, there is the `rootfs_label` attribute in `type` tag to set it.

**Comment by schaefi** [comment]
The label extension for volumes based on LVM would be no problem

The precedence for the volume feature is filesystem before LVM. In case of btrfs which has its
own volume management I checked if we can apply the label too. Fortunately this is possible
via 

```
 btrfs filesystem label  [<device>|<mount_point>] label_name
```

So yes I think this could be transparently set for any filesystem we support so far

**Comment by schaefi** [comment]
Will work on this one when done with Azure

**Comment by schaefi** [comment]
By reading the btrfs docs I found that applying a label to a subvolume is not possible. Thus the filesystem has only one label which is the one we already apply with the rootfs_label attribute. My implementation for volume labels will be effective on LVM volumes because in this case each volume is a device and on each device a filesystem needs to be created which allows for a label for each device.

**Comment by schaefi** [comment]
In btrfs the concept of subvolumes is tight together with the filesystem hierarchy and that forms the name of the subvolume as listed in ```btrfs subvol list /```. There is no concept of an alias or label name which can be used as alternative volume description. Thus my implementation will have no effect if btrfs is used, unless I misunderstood the concept of btrfs subvolume management
