### ISSUE TITLE
Provide zsync files for the generated images

### ISSUE THREAD

**Issue by probonopd** [SUSE/kiwi#754]
## Problem description

As described in https://github.com/SUSE/kiwi/issues/364, 

> In order to keep a big data blob like an image in sync it would be great to have the opportunity to update only the changed blocks of the image file instead of transferring the entire blob with every change.
> The zsync tool allows to do that. 

## Expected behaviour

Ubuntu uses zsync files to make it very efficient to go e.g., from daily Live ISO to the next daily Live ISO by downloading only a few MB. Whereas one has to download the entire openSUSE Live ISO each time. It would be nice if the openSUSE Live ISOs could be updated using zsync like the Ubuntu ones.

It seems that kiwi-ng already has the needed functionality, but the capability is currently wasted since the zsync files don't "land" in the download directories like https://download.opensuse.org/distribution/leap/15.0/live/.

_I am not sure whether this issue belongs into this project; if not please bear with me and kindly let me know where it belongs instead._

**Comment by schaefi** [comment]
commit 591963bb95b170b6ad98bab035f314ebea65c9b7 (origin/zsync_setup)
Author: Marcus Schäfer <ms@suse.de>
Date:   Tue Jun 20 18:22:25 2017 +0200

    Added creation of zsync control file in bundler
    
    If a --zsync_source url is provided to the bundler call a
    zsync control file is created for the compressed parts of
    the bundle. This Fixes #364

**Comment by schaefi** [comment]
However the buildservice team iirc did not (yet) jump on that feature, which means the kiwi bundler is not called with --zsync_source

**Comment by probonopd** [comment]
https://github.com/openSUSE/open-build-service/issues/3193 and https://github.com/openSUSE/obs-build/pull/367 both got closed. I am a bit at a loss since I don't know where and how to report this so that it finally gets implemented "all the way". Can you help @schaefi? Thanks.

**Comment by probonopd** [comment]
I am running `openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20180530-Media.iso` and I would like to "upgrade" to the latest one, `openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20180606-Media.iso`. If there was a `.zsync` file, I would have to download only a few MB. Since there is none, I need to re-download the full ISO image.

So, still

> It seems that kiwi-ng already has the needed functionality, but the capability is currently wasted since the zsync files don't "land" in the download directories like https://download.opensuse.org/distribution/leap/15.0/live/.
> 
> I am not sure whether this issue belongs into this project; if not please bear with me and kindly let me know where it belongs instead.
