### ISSUE TITLE
Kiwi issue when building image in private OBS

### ISSUE THREAD

**Issue by s0l4r** [SUSE/kiwi#76]
## Problem description

When building a kiwi image inside OBS, I get the following traceback:

`
[  187s] [ ERROR   ]: 15:59:00 | Unexpected error:
[  187s] Traceback (most recent call last):
[  187s]   File "/usr/bin/kiwi", line 9, in <module>
[  187s]     load_entry_point('kiwi==8.14.1', 'console_scripts', 'kiwi-ng')()
[  187s]   File "/usr/lib/python3.4/site-packages/kiwi/kiwi.py", line 55, in main
[  187s]     App()
[  187s]   File "/usr/lib/python3.4/site-packages/kiwi/app.py", line 35, in __init__
[  187s]     task_class().process()
[  187s]   File "/usr/lib/python3.4/site-packages/kiwi/tasks/system_create.py", line 90, in process
[  187s]     result = image_builder.create()
[  187s]   File "/usr/lib/python3.4/site-packages/kiwi/builder/disk.py", line 256, in create
[  187s]     self.boot_image.prepare()
[  187s]   File "/usr/lib/python3.4/site-packages/kiwi/boot/image/kiwi.py", line 62, in prepare
[  187s]     profile = Profile(self.boot_xml_state)
[  187s]   File "/usr/lib/python3.4/site-packages/kiwi/system/profile.py", line 46, in __init__
[  187s]     self.__packages_marked_for_deletion_to_profile()
[  187s]   File "/usr/lib/python3.4/site-packages/kiwi/system/profile.py", line 329, in __packages_marked_for_deletion_to_profile
[  187s]     self.xml_state.get_to_become_deleted_packages()
[  187s] TypeError: sequence item 6: expected str instance, NoneType found
[  187s] [ INFO    ]: 15:59:00 | Cleaning up SystemPrepare instance`

When inserting a print inside the profile.py (/usr/lib/python3.4/site-packages/kiwi/system/profile.py) inside the python3-kiwi.tar.bz2 package, it looks like an issue with the "make" package that is specified in the <packages type="delete"> section in the initrd config.xml (/usr/lib/python3.4/site-packages/kiwi/boot/arch/x86_64/oemboot/suse-SLES12/config.xml):
`    
<packages type="delete">
        <package name="dracut"/>
        <package name="cracklib-dict-full"/>
        <package name="fillup"/>
        <package name="gdbm"/>
        <package name="info"/>
        <package name="insserv"/>
        <package name="make"/>
        <package name="mingetty"/>
        <package name="Mesa"/>
        <package name="sles-release"/>
        <package name="pam"/>
        <package name="pam-modules"/>
        <package name="perl"/>
        <package name="perl-Bootloader"/>
        <package name="permissions"/>
        <package name="python"/>
        <package name="python-base"/>
    </packages>
`

The issue occurs in the following code:
`    
def __packages_marked_for_deletion_to_profile(self):
        # kiwi_delete
        self.dot_profile['kiwi_delete'] = ' '.join(
            self.xml_state.get_to_become_deleted_packages()
        )
`

This is the content of self.xml_state.get_to_become_deleted_packages() during build:
`[  187s] ['dracut', 'cracklib-dict-full', 'fillup', 'gdbm', 'info', 'insserv', None, 'mingetty', 'Mesa', 'sles-release', 'pam', 'pam-modules', 'perl', 'perl-Bootloader', 'permissions', 'python', 'python-base', 'make', 'module-init-tools', 'make']
`

Somehow the sixth value in the list has been replaced by 'None'. At the None positition is actually 'make' according to config.xml. It also looks like 'make' has been inserted inside the list multiple times (see above).

System info:
OBS: 2.7 beta (2.6.91.git20160511.e60af6b)
Kiwi: 8.14.1
Host OS: SLES12 SP1

Any ideas?

## Steps to reproduce the behaviour
Building any image in OBS.

**Comment by schaefi** [comment]
Could you send me your image XML description ?

You are right, the None type from the list returned by get_to_become_deleted_packages() is causing this. However I could not yet find how this can happen. Thus your image XML description would be helpful

Thanks

**Comment by schaefi** [comment]
I found the problem, will fix it

**Comment by s0l4r** [comment]
I was just about to post the config.kiwi, I guess you won't need it then! Thanks for quick reply!!

**Comment by schaefi** [comment]
yes I could reproduce it and will come up with a fix soon

**Comment by schaefi** [comment]
Thanks for reporting this, it was an important one

I'll submit new packages in a minute

**Comment by s0l4r** [comment]
Thank you. Have have tested and verified the fix!
