### ISSUE TITLE
Support creating container images using buildah + skopeo

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#764]
## Enhancement request description

kiwi currently has the ability to produce two types of container images: base images and layered images. The way this is currently done is by using [`umoci`](https://github.com/openSUSE/umoci) and [`skopeo`](https://github.com/projectatomic/skopeo).

However, there are a couple of issues with this:
* On Fedora, I don't have `umoci`. kiwi's ability to produce container images is basically broken because we only have half of the necessary tools (we have `skopeo`, but not `umoci`).
* Even if I have the ability to use `umoci` for image builds, I'd rather not use it because I'd like to leverage the same underlying tooling for producing images that is used for producing images in OpenShift to simplify the complexity of understanding the image creation process. Fedora uses OpenShift for producing our official container images, and I'd like to be able to leverage similar tooling for producing images using kiwi + OBS.

So, I'd like to see kiwi support [`buildah`](https://github.com/projectatomic/buildah) as an alternative to `umoci` for producing container images.

Today, `buildah` (along with [`podman`](https://github.com/projectatomic/libpod), the container runtime tool), is available in CentOS/RHEL 7, Fedora 26+, openSUSE Tumbleweed, openSUSE Kubic, and (soon) SUSE CaaSP.

## OS and Software information
+ KIWI version: 9.15.1
+ Operating system: Fedora 28
+ OBS version: N/A

**Comment by davidcassany** [comment]
You are right, buildah got into Tumbleweed 3 months ago at the time it did podman and other OCI tools. I understand your preference for buildah as it is already in the base distribution, however we need to keep umoci support and I am wondering what else we gain beyond facilitating container builds in other distros.

**Comment by Conan-Kudo** [comment]
My understanding is that `buildah` is going to be a cornerstone for doing container builds for the wider variety of Kubernetes-centric tools, especially for folks using the CRI-O runtime for Kubernetes/OpenShift.

Also, technically `buildah` doesn't require `skopeo` at all, as it can do its own container fetching for producing layered images, whereas when using `umoci`, you need `skopeo` to fetch the image first.

**Comment by davidcassany** [comment]
After digging a little more about `buildah` I think this out of scope for the time being. Several reasons for that:

* We are not using it in SUSE and there are not plans neither any specific technical motivation for using it as an alternative or substitution of `umoci`.
* It initially got in to openSUSE Tumbleweed as it was a requirement of `podman`. However apparently current `podman` does not require it anymore as it embeds buildah code in its own code. Thus for the time being is not clear it will end up in any upcoming SUSE product.
* `buildah` is a very recent tool, github presence of buildah is doesn't go longer than a year and half and, if I am not mistaken, first `1.0` release has been done recently. We'd like to avoid having to support yet another tool that is likely to evolve quite fast (like any tool within the containers hype).

So, for now, we do not plan to jump on providing support for `buildah`, which doesn't mean it could change in the future.

**Comment by Conan-Kudo** [comment]
I'd like to point out now that OBS is now gaining support for building containers using `buildah` as an alternative to docker itself: https://github.com/openSUSE/obs-build/commit/7773d78635c78e5b680ea20dc442f40bb84ad3b4

**Comment by davidcassany** [comment]
@Conan-Kudo , yes that makes sense for Dockerfile based builds, this way there is no need of Docker daemon in the buildenv. While I still do not see a need to include `buildah` support in KIWI (`umoci` is lighter in terms of dependencies) we definitely need to keep an eye to container related tools. At a glance, `buildah-mount` ->  `buildah-commit` -> `buildah-config` -> `buildah-umount` looks like something similar of what we are doing with `umoci`, but I do not have any experience with it yet.

**Comment by Conan-Kudo** [comment]
KIWI has now been refactored to support multiple options for creating OCI images, so it's now possible to do this.

**Comment by Conan-Kudo** [comment]
This is now slightly more important as RHEL 8 will not ship `docker` at all, only `podman`, `buildah`, and `skopeo`: https://www.redhat.com/en/blog/red-hat-enterprise-linux-8-beta-new-set-container-tools
