### ISSUE TITLE
Add a way to specify the disturl

### ISSUE THREAD

**Issue by mlschroe** [SUSE/kiwi#770]
Taking the disturl from the /.buildenv file is a horrible idea. Please add a sane way the build script can use to pass in the disturl.

**Comment by davidcassany** [comment]
@mlschroe, does the suggested approach solve your concerns?

**Comment by mlschroe** [comment]
Yes, a way to specify labels on the command line is exactly what I had in mind. Thank you. To stay compatible you may want to keep the buildenv parsing code but let the command line overwrite the label generated from the buildenv. We can then drop the code with the next release of kiwi, i.e. when we can check the kiwi version to test if the label options are understood.

**Comment by mlschroe** [comment]
(And yes, I should have payed more attention to bsc#1055542... my fault, sorry.)

**Comment by davidcassany** [comment]
Yes, compatibility should be kept. I'll go for that implementation. Thanks
