### ISSUE TITLE
libnss_* is being stripped from netboot

### ISSUE THREAD

**Issue by luizluca** [SUSE/kiwi#798]
## Problem description
I'm building a LEAP 15.0 PXE image from Tumbleweed that uses NBD root:

`    <type image="pxe" filesystem="squashfs" boot="netboot/suse-leap15.0"/>
`

After the initrd is created, it cannot mount root because DNS fails. The root cause is missing libnss_* libraries. There were stripped.

```
$ grep libnss_dns build/image-root.log 
DEBUG: --> kiwi_strip_libs='libdmraid-events-isw libfontenc libfreetype libgcc_s libnsl libnss_compat libnss_dns libnss_files libpng libresolv librt libsysfs libutempter libutil libkmod libselinux libsepol libdevmapper libply-boot-client libply-splash-graphics libsplashy libsplashycnf libjpeg libkms libaio libdrm'
DEBUG: Removing library: /lib64/libnss_dns-2.26.so
```

I copied the `<strip type="libs">` section from `/usr/lib/python3.6/site-packages/kiwi/config/strip.xml` into my kiwi configuration. However, it did not change the behavior.

## Expected behaviour
libnss_dns should not be removed, specially from a netboot initrd

## Steps to reproduce the behaviour
* Build a LEAP 15.0 pxe image using netboot/suse-leap15.0
* Configure KIWI to mount nbd. Use FQDN for kiwiserver and nbd-server, not ip address
* Boot will fail because it cannot resolve FQDN into an IP (BTW, host/dig does work)

## OS and Software information
+ KIWI version: 9.16.2
+ Operating system: OpenSUSE Tumbleweed
+ OBS version: none (local build)

**Comment by schaefi** [comment]
Hmm, that's bad. actually the libs listed in <strip type="libs"> should be protected from any removal, libnss_dns is part of it.

@davidcassany: could you take a look at this one ?

**Comment by davidcassany** [comment]
@schaefi, sure I'm having a look
