### ISSUE TITLE
SquashFS support?

### ISSUE THREAD

**Issue by randyesq** [SUSE/kiwi#808]
## Problem description
Was unable to find if `--type` could support an image export format of squashfs. Is this possible or would it be a feature request?

## Expected behaviour
N/A

## Steps to reproduce the behaviour
N/A

## OS and Software information
+ KIWI version: 
+ Operating system: 
+ OBS version:

**Comment by schaefi** [comment]
What exactly do you want to achieve ? We use squashfs in kiwi for live images and also for disk images configured with overlayroot="true" as implicit container for the read-only data.

If you just want to create a root tree as squashfs image you can do this with the following type setup

```xml
<type image="squashfs">
```
which you then can build as follows:

```
kiwi-ng --type squashfs system build --description ... --target-dir ...
```

Feel free to re-open if that does not satisfy your needs.

Thanks

**Comment by davidcassany** [comment]
@randyesq, I guess there is no specific documentation or examples regarding that. However this is somehow covered by the schema documentation [here](https://opensource.suse.com/kiwi/development/schema.html#id264). However I think it wouldn't hurt to include a new simple example in the docs for root tree filesystem builds in [Building Images](https://opensource.suse.com/kiwi/building.html)
