### ISSUE TITLE
Fedora Rawhide UEFI appliance image build fails

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#810]
## Problem description
When building an [appliance image based on Fedora Rawhide](https://build.opensuse.org/package/show/home:Pharaoh_Atem:Fedora_Pagure_Git/Pagure-Appliance-Rawhide), it fails on detecting and installing shim correctly and ultimately fails to build.

However, it works with [the Fedora 28 based one](https://build.opensuse.org/package/show/home:Pharaoh_Atem:Fedora_Pagure_Git/pagure-appliance).

## Expected behavior
An appliance image is successfully built with Secure Boot-enabled UEFI support.

## Reproducer
A reproducer is available here: https://build.opensuse.org/package/show/home:Pharaoh_Atem:Fedora_Pagure_Git/Pagure-Appliance-Rawhide

The Fedora 28 based one is here: https://build.opensuse.org/package/show/home:Pharaoh_Atem:Fedora_Pagure_Git/pagure-appliance

## OS and Software information
+ KIWI version: 9.16.0
+ Operating system: Fedora Rawhide
+ OBS version: `2.10~alpha.20180822T225340.7eae45254` (build.opensuse.org)

**Comment by Conan-Kudo** [comment]
It appears it fails because `/boot/efi/EFI/fedora/shim.efi` is considered 
"legacy" and only included in the `shim-signed-ia32` package, starting with Fedora 29.

I'm not entirely sure what this actually means, but @vathpela made this change as part of the refactoring of our shim packaging in Fedora, and perhaps he could shed some light here?

**Comment by schaefi** [comment]
yes in kiwi we have

```python
shim_file_patterns = [
    '/usr/lib64/efi/shim.efi',
    '/boot/efi/EFI/*/shim.efi'
]
```

if none of these matches shim.efi the build requesting it will fail. You mentioned a refactoring of shim in Fedora, if we know the details we could adapt.

**Comment by schaefi** [comment]
I'll set this on on blocked as it seems we need further information how the shim setup on Fedora gets refactored. Please let us know when the change has settled so we can take action and adapt. Thanks

**Comment by jburgess777** [comment]
The change to move `shim.efi` to `shim-ia32` was reverted prior to the release of F29 because it caused a boot regression for existing systems which referenced the old file in the EFI boot manager settings:

https://bugzilla.redhat.com/show_bug.cgi?id=1631989

**Comment by schaefi** [comment]
Thanks for the update, iirc this means we are back on green.

@Conan-Kudo please re-open if I'm mistaken. Thanks
