### ISSUE TITLE
Allow user defined installation media volume ID

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#811]
## Problem description

With former KIWI `volid` attribute could also be used for `oem` images having the `installiso` attribute. Current KIWI does not permit the use of `volid` attribute for `oem` images, moreover, the volume ID is fixed to `INSTALL` and the `kiwi-dump` dracut module is dependent to that value.

## Expected behaviour
The section as: 
`<type image="oem" installiso="true" volid="_LABEL_" ...>`
Results in a installation media labeled with the defined label

## Steps to reproduce the behaviour

Build an OEM image with the installation media. The installation media will be always labeled as `INSTALL`.

## OS and Software information
+ KIWI version: 9.16.12

**Comment by schaefi** [comment]
right for the install media the volid is a fixed value. Do you have a customer use case why this value should be configurable ?

**Comment by davidcassany** [comment]
There is user that noticed the behavior change when upgrading to current KIWI in this [post](https://groups.google.com/forum/#!topic/kiwi-images/7ZskB3N-tlw) (I'm not sure if the link works for all)

**Comment by schaefi** [comment]
ok I see the post, thanks for sharing it. Can you reach out to the customer and ask for the reason why the install media should have a custom label ? This question is not answered by the posting. The fact that the legacy kiwi version can apply a custom volid also for building the install iso is a side effect of the implementation here but was not directly intended :)

In the implementation here we intentionally wanted to control the label setup and give the install media build by kiwi a fixed name. Simply INSTALL is imho a bad name better would be something that identifies it as a kiwi installation image but that's a different topic.

So for the moment I'd like to understand where the benefit is for a custom label of the install media as kiwi builds it. For live images that makes sense as they are used as consumer systems and not only for one specific task

Thanks

**Comment by schaefi** [comment]
@davidcassany Thanks for getting back to the customer. The feedback we got sounds reasonable to me. So I think it would be a good change to allow custom volid for the install media as well. We need to make clear however that not all names are allowed in volume id's. In kiwi we have ```safe-posix-name``` in the schema which is 

```
safe-posix-name = xsd:token {pattern = "[a-zA-Z0-9_\-\.]+"}
```

We also should communicate that the ISO9660 Standard is 32 chars for VolID

Thoughts ?

**Comment by schaefi** [comment]
yes :+1: let's do it that way
