### ISSUE TITLE
fuse package causes build failure

### ISSUE THREAD

**Issue by magist3r** [SUSE/kiwi#813]
## Problem description
Fuse post script failed when i try to use it in my image. First time I think that this is package failure, but now I doubt.

See here for reference:
https://bugzilla.opensuse.org/show_bug.cgi?id=1105817

## Steps to reproduce the behaviour
add "fuse" package to image description

## OS and Software information
+ KIWI version: 9.12.6
+ Operating system: Leap 15.0
+ OBS version:

**Comment by schaefi** [comment]
Does it make a difference if you add fuse in

```xml
<packages type="bootstrap">
    <package name="fuse"/>
</packages>
```

or in:

```xml
<packages type="image">
    <package name="fuse"/>
</packages>
```

I'm not sure if we can solve this from a kiwi perspective

**Comment by magist3r** [comment]
This variant works. Thank you.
```xml
<packages type="bootstrap">
    <package name="fuse"/>
</packages>
```

**Comment by schaefi** [comment]
posting comment from @magist3r 

```
   This variant works. Thank you.

<packages type="bootstrap">
    <package name="fuse"/>
</packages>
```

I saw the mail but for some reason it did not made its way to this thread
