### ISSUE TITLE
Merge modifications to temporary files

### ISSUE THREAD

**Issue by rjschwei** [SUSE/kiwi#817]
## Problem description
When modifying temporary files such as /etc/hosts in config.sh the changes get lost.

## Expected behaviour
Changes should be retained

## Steps to reproduce the behaviour
Add "echo hi >> /etc/hosts" into conifg.sh the entry will not be in the /etc/hosts file in the image.

## OS and Software information
+ KIWI version: latest
+ Operating system: openSUSE & SLE
+ OBS version: latest

**Comment by davidcassany** [comment]
@rjschwei, @schaefi I don't think setting a merging strategy in KIWI is desirable. I don't think we can come up with robust enough solution, it can easily happen that changes applied to temporary copied from the host files (`.kiwi` files) are not applicable to the package provided files (`.rpmnew` files). I don't think we can relay on that, it could even happen that the merging strategy does not fail but the result is just useless.

IMHO we need to establish a simpler criteria. I'd say we have some options:

1. Do not modify KIWI behavior and document possible situations/workarounds
2. Consider any modified file in config.sh as it was provided like an overlay file. So check for modifications before cleaning and make any modified file become the final file by removing the symlink and renaming the file to the original name without the `.kiwi` extension.
3. Establish some mechanism similar to what we did with `fstab.append` (where any line present in `/etc/fstab.append` is appended to `/etc/fstab`) and apply it after the 'clean up'.

I'd vote for the first or second idea. With the third one I don't think we can easily get a simple and flexible enough solution.

Thoughts? Any other idea?

**Comment by schaefi** [comment]
@davidcassany hope you don't mind, I took this one because I was recently thinking about all this code when I implemented #807

**Comment by davidcassany** [comment]
Sure no problem :wink:

**Comment by schaefi** [comment]
@rjschwei @davidcassany 

One question we have to discuss is how to react if we found out that the temp copy has been modified and the changes will not have any effect. If we only warn about it the resulting image might behave unexpected. If we make this a fatal error we generate an exit condition which can be reached by any broken package and not only by code from scripts controlled by the author of the image description

As of today I would only warn.

Thoughts ?

**Comment by rjschwei** [comment]
I agree it should be a warning. It is reasonable to expect that an image would be tested at first and during that test the missing modification would be found. A review of the build log would then reveal the reason why.
