### ISSUE TITLE
Move travis process to be called in container

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#822]
## Problem description

Recently the creation of the kiwi documentation as PDF came to our attention.
Adding the target in the build process was not a big deal but now the travis checks
failed because the travis runtime environment did not contain the LaTeX distribution
which was a requirement to build the PDF through sphinx. Adding LaTeX would
meant the following change in travis 

```
before_install:
  - sudo apt-get install -y texlive-full
```

This change would have caused a big performance problem because all of LaTeX
gets pulled in with every travis call and significantly drops testing performance.

If there would be a pre-built environment which provides, in this case a LaTeX distribution
that can be just used and gets cached in some way on travis it would be a better
solution.

A potential candidate to solve this technically is to use containers as suggested by @Conan-Kudo 

> Have you considered just changing the Travis config to use containers to give
> you a useful environment?
> In rpmlint, I use a configuration that lets me build and test rpmlint on Fedora and openSUSE:
> https://github.com/rpm-software-management/rpmlint/blob/master/.travis.yml
> That way you can also validate that it works on Fedora and openSUSE in CI too. :)

This would open a bunch of questions which we might want to discuss:

1. Do distributions provide e.g LaTeX flavored containers in some registry, or would that something we have to create and maintain first ?
2. Do we want to connect the travis checks to a specific distribution delivered by the container ? Currently we use an ubuntu environment because that comes with travis.
3. Do we agree that if the container has to install LaTeX first, it does not make any difference to install texlive-full as suggested above ?

I'll open that for a discussion, everyone welcome :)

**Comment by Conan-Kudo** [comment]
> Do distributions provide e.g LaTeX flavored containers in some registry, or would that something we have to create and maintain first ?

At least in Fedora, we have a mechanism for offering container builds as part of the distribution. It's not a big thing yet, but it's certainly possible to have a TeXLive container offered by Fedora for this purpose. Just no one has done it yet!

(We could also have a kiwi container for building appliance images :P)

> Do we want to connect the travis checks to a specific distribution delivered by the container ? Currently we use an ubuntu environment because that comes with travis.

Well, obviously, I'd prefer to see Fedora being used in the CI. But reasonably, it makes sense to use at least openSUSE and Fedora, since checks failing in those distributions is actually a problem (openSUSE uses kiwi for its image creation tooling, and Fedora is what RHEL/CentOS will be, and that platform is important to support).

> Do we agree that if the container has to install LaTeX first, it does not make any difference to install texlive-full as suggested above ?

Yes. :)

**Comment by schaefi** [comment]
The gitlab CI pipeline is established now. As of now travis and gitlab-ci are both in place. Depending on what happens in travis in the future we might move the deploy stage from travis to the gitlab-ci pipeline too.

The pipeline is running based on the Fedora containers because that distro provides packages for different python releases (3.4, 3.5...) and allows for easy testing in this regard. If running on behalf of a different distribution is for some reason required (can't image one right now) we can extend the pipeline pretty easily now.

Thanks
