### ISSUE TITLE
lack of udev in choot environment causes lvcreate failures

### ISSUE THREAD

**Issue by rtamalin** [SUSE/kiwi#824]
## Problem description
If running kiwi in a chroot'd environment, such as when trying to use it to build LVM images in the Open Build Service, or locally with `osc build`, then `lvcreate` will fail because, by default, it attempts to zero out the first 4kib of the newly created LV device, and it assumes that the device will have been automatically created for it by udev.

And even if you workaround this issue, subsequent operations will fail because there will be node /dev node created for the newly created LV device.

This is similar to the previously reported #631 issue, but I have identified a workaround/fix for the problem as discussed in #631.

## Expected behaviour
The `lvcreate` command run as part of the kiwi LVM image creation process should succeed in creating the specified LVs, e.g. LVRoot.

## Steps to reproduce the behaviour
Try to create an LVM based image either in OBS or locally using `osc build`, with a systemdisk specification similar to either:

```xml
    <systemdisk name="system-vg" preferlvm="true"/>
```
or

```xml
    <systemdisk name="system-vg" preferlvm="true">
      <volume name="@root" size="3G"/>
    </systemdisk>
```

## Workaround/Fix
This issue can be worked around using the following steps:

- when running `lvcreate` include the `-Z|--zero n` option, which skips the device header zeroing
- after lvcreate has completed explicitly run `vgscan --mknodes` to create any missing /dev nodes for devices associated with your LVM VGs

### Note:
The `vgscan --mknodes` command appears to be safe to run in general as it will only create nodes for devices that don't already exist in one form or another.

## OS and Software information
+ KIWI version: 9.16.6
+ Operating system: openSYSE Leap 15.0 & Ubuntu Xenial (both running `osc build` locally)
+ OBS version: SUSE Internal OBS version as of 2018-09-27, SUSE public OBS as of 2018-09-27

**Comment by rtamalin** [comment]
Implementing fix in https://github.com/rtamalin/kiwi/tree/lvm_image_fixes and hope to generate a pull request with a fix later today or next week.

**Comment by schaefi** [comment]
Sounds great :+1: thanks for your time and effort
