### ISSUE TITLE
Crashes with repo URLs which have query keys without values

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#828]
Adding a URI such as `http://foo.bar/baz?asdf` crashes kiwi:

```
[ ERROR   ]: 22:54:23 | Unexpected error:
Traceback (most recent call last):
  File "/usr/bin/kiwi", line 9, in <module>
    load_entry_point('kiwi==9.16.6', 'console_scripts', 'kiwi-ng-2')()
  File "/usr/lib/python2.7/site-packages/kiwi/kiwi.py", line 64, in main
    App()
  File "/usr/lib/python2.7/site-packages/kiwi/app.py", line 35, in __init__
    task_class().process()
  File "/usr/lib/python2.7/site-packages/kiwi/tasks/system_build.py", line 201, in process
    self.command_args['--signing-key']
  File "/usr/lib/python2.7/site-packages/kiwi/system/prepare.py", line 149, in setup_repositories
    repo_user, repo_secret, uri.credentials_file_name(),
  File "/usr/lib/python2.7/site-packages/kiwi/system/uri.py", line 144, in credentials_file_name
    query = dict(params.split('=') for params in uri.query.split('&'))
ValueError: dictionary update sequence element #0 has length 1; 2 is required```

**Comment by schaefi** [comment]
@Vogtinator it would be very helpful for fixing this bug if there is kind of a test repo with credentials which we could use. Are you aware of any which we could use for this purpose ? (on-private-mail) Thanks

**Comment by Vogtinator** [comment]
> @Vogtinator it would be very helpful for fixing this bug if there is kind of a test repo with credentials which we could use. Are you aware of any which we could use for this purpose ? (on-private-mail) Thanks

You can just use `http://foo.bar/baz?asdf` to reproduce any of the issues I reported.

**Comment by schaefi** [comment]
sure but I'd like to test if it _really_ works with token repos. So is there a repo we can use for Ci testing or should we leave that in your hands ? Thanks

**Comment by schaefi** [comment]
I like to keep the turnaround cycles low, thus it would be helpful

**Comment by Vogtinator** [comment]
If `zypper` reports the full URL with query part in its error message, it'll most likely work.

This change in `Uri.translate` made it work for me.

```
        elif uri.scheme.startswith('http') or uri.scheme == 'ftp':
            return ''.join([uri.scheme, '://', uri.netloc, uri.path, '?', uri.query])
```

**Comment by Vogtinator** [comment]
That change is for issue #830, to workaround the crash I just commented out `Uri.credentials_file_name`.

**Comment by schaefi** [comment]
> If zypper reports the full URL with query part in its error message, it'll most likely work.

last famous words :) ok you are saying there is no test repo with credentials which we could use for a real Ci test. With regards to the conversation we have with the QA maintenance people I would have provided a simple test build using a repo with such a uri, installing a package from that repo and give the QA people a way to speedup their testing

...anyway we are far away from automation or making colleagues live easier

ok I'll look into this one next and prepare a pull request
