### ISSUE TITLE
Kiwi strips the query of repo URLs

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#830]
When invoking kiwi with `--add-repo https://foo.bar/baz?asdf=qwertz`, only `https://foo.bar/baz` is added to the repos used by zypper.

This means it's impossible to use KIWI to build SLE images as the query contains the credentials.

**Comment by schaefi** [comment]
I'd say it's related to #828

**Comment by Vogtinator** [comment]
A bit, yes. It's in entirely independent functions though.
