### ISSUE TITLE
wrong dependencies of kiwi dracut modules for Ubuntu

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#837]
## Problem description

`btrfs-progs` package does not exist in Ubuntu, thus `dracut-kiwi-oem-repart` package should not require it for Ubuntu/Debian builds. Instead there is a `btrfs-tools` package available.

Tested it for Xenial and Bionic

In addition `dracut-kiwi-live` and `dracut-kiwi-lib` should require `dracut-network`. Ubuntu has an extra package for dracut network modules. The network module is needed by `dracut-kiwi-live` and `dracut-kiwi-lib`, if this package is not present the dracut call to create the intird fails due to missing dependencies.

## Expected behaviour

`dracut-kiwi-oem-repart` is installable in Ubuntu and `dracut-kiwi-live` pulls `dracut-network`

## Steps to reproduce the behaviour

Include `dracut-kiwi-oem-repart` or `dracut-kiwi-live` in an Ubuntu build.

**Comment by schaefi** [comment]
Looking into this one
