### ISSUE TITLE
python2-kiwi deb package is broken

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#838]
## Problem description

`python2-kiwi` package is broken for ubuntu builds. It does not install, it fails including the pdf documentation.
The issue is related to https://github.com/SUSE/kiwi/blob/539cdd7172cc6a35a7438f9158261aff1315c5b7/Makefile#L32-L35

Here the docs path expansion is hardcoded however in spec macros are used https://github.com/SUSE/kiwi/blob/539cdd7172cc6a35a7438f9158261aff1315c5b7/package/python-kiwi-spec-template#L555

In case of Ubuntu build this leads to two different paths and fails during the installation. I am surprised this is not failing at package build time. Probably the tricks done here to reuse the spec for `deb` packages skips many sanity tests we are used to.

## Expected behaviour

`python2-kiwi` is installable in Ubuntu Xenial and Bionic.

## Steps to reproduce the behaviour

Include `python2-kiwi` in an Ubuntu build.

**Comment by schaefi** [comment]
looking into that one now

**Comment by davidcassany** [comment]
@schaefi you can see the failure [here](https://build.opensuse.org/package/show/home:dcassany:branches:Virtualization:Appliances:Images:Testing_x86/test-image-ubuntu)

I was trying to get an Ubuntu build in OBS but because of this it was failing even before calling kiwi.
