### ISSUE TITLE
Isolinux.bin binary not found

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#839]
## Problem description

Building Ubuntu ISO's there is a `KiwiIsoLoaderError: No isolinux loader %s found` failure. This is caused because the `isolinux.bin` binary is not found in root tree and, in consequence, not copied to the expected location, see https://github.com/SUSE/kiwi/blob/e9f715d82b446f069ec3788b475ead45ddd29ba4/kiwi/bootloader/config/isolinux.py#L243-L271

Ubuntu has `isolinux.bin` located at `/usr/lib/ISOLINUX/isolinux.bin`, thus it does not get copied to the  appropriate `/boot` location.

## Expected behaviour

`isolinux.bin` is found in `/boot` in the image root tree, so the ISO image creation does not fail.

## Steps to reproduce the behaviour

Try to build an Ubuntu ISO.

**Comment by schaefi** [comment]
looking into this one
