### ISSUE TITLE
Kiwi-ng should not cache local Repositories

### ISSUE THREAD

**Issue by BerndHarries** [SUSE/kiwi#847]
## Problem description
Unlike Kiwi 7.x, Kiwi-ng caches packages from local repos.

## Expected behaviour
Repositories begining with file: should not be cached. 

## Steps to reproduce the behaviour
Build an appliance with at least one local Repository and check 
/var/cache/kiwi/packages/*/

## OS and Software information
+ KIWI version: 9.16.12
+ Operating system: openSuse 42.3

**Comment by schaefi** [comment]
For the record, ```kiwi/kiwi/repository/zypper.py``` adds repos always with ```--keep-packages``` which doesn't make much sense if the repository is local.
