### ISSUE TITLE
Support custom boot menu entries

### ISSUE THREAD

**Issue by magist3r** [SUSE/kiwi#85]
Hi!

It would be great to add custom menu entries, but I don't know how exactly do this. Now I have some patches for kiwi7 to add some custom entries for iso image. But I think that add this functional to xml description would be easy.

**Comment by schaefi** [comment]
We don't see further demand on custom boot menu entries to be part of the XML description. Actually it opens a gate to the bootloader which we currently don't see much value. With the raw concept of running a script to modify the bootloader setup via ```editbootconfig``` there is an opportunity for advanced customers to update the config according to their needs.

If a less generic but more user friendly request for a more specific use case comes up in the future we are happy to rethink the idea.
