### ISSUE TITLE
Support arbitrary history entries

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#852]
Currently, any image built with kiwi has this (or similar) as output of `docker history`:

```
IMAGE               CREATED             CREATED BY          SIZE                COMMENT
693d2f77e3c6        24 hours ago        umoci config        0B                  
<missing>           24 hours ago        umoci config        104MB
```

It should only have one of those entries if possible and the comment should be specified in the kiwi description. Example:

```
IMAGE              CREATED             CREATED BY        SIZE         COMMENT
693d2f77e3c6       24 hours ago        kiwi              104MB        A container I built
```

**Comment by davidcassany** [comment]
I agree that a base image should not have this empty or strange entries in history. Would be nicer if there is only one history entry per build (or layer) with some meaningful data.
