### ISSUE TITLE
gpg keys of the repositories are not trusted even using '--signing-key' flag

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#855]
## Problem description

Since openSUSE Leap 15 `--signing-key <keyfile>` flag does not prevent `zypper` from failing when gpg checks are enabled, even the provided keyfile is verified to be valid.

This is an issue also reported to libzypp as a bugzilla issue [bsc#1112357](https://bugzilla.opensuse.org/show_bug.cgi?id=1112357)

## Expected behaviour

Adding `--siging-key <keyfile>` with correct keys should be enough to ensure KIWI is capable to build images when 'repository_gpgcheck' and 'package_gpgcheck' attributes are set to `true`.

## Steps to reproduce the behaviour

Enable `repository_gpgcheck` and/or `package_gpgcheck` for some repository and the installation of any package from that repo will cause a zypper install failure.

**Comment by davidcassany** [comment]
I do not consider it a KIWI issue, however we might code a work around, as the issue is pretty deep in the code of `libzypp` and `libsolv`, sensitive tools that might take a while to fix or update, see [bsc#1112357](https://bugzilla.opensuse.org/show_bug.cgi?id=1112357) for further details.

**Comment by Conan-Kudo** [comment]
Ahh, the joys of changing the rpmdb location... :/

**Comment by davidcassany** [comment]
Yeah... I tried to patch `libzypp` as all the code looked sane to me (it has all the utilities in place for custom rpmdb), but then when I started testing the patch and it caused issues in `libsolv` :/ and who knows what would have been next...
