### ISSUE TITLE
umoci vs. buildah two players one goal

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#859]
## Issue description

umoci is the tool to create oci containers (tar archive) from the kiwi prepared system root.
It does its job very well but it seems the scope is limited to suse distributions and there seems
to be not much effort to provide it beyond that distribution. As consequence there is another
tool called buildah (https://rhelblog.redhat.com/tag/buildah) which duplicates the work done
in umoci.

With kiwi we provide an appliance builder which should be able to build any major distribution
and therefore exists for those targets (http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder) This however implies the required toolchain to be available for the supported distributions. In the end this results in a preference to those tools considered standard or core.

With the current implementation of umoci vs. buildah I see a competitive situation which I'd like to start a discussion if it would be better to move to buildah or provide at least provide support for it like I did it with cdrtools vs. xorriso

buildah is currently being provided in RHEL, CentOS, Fedora, and openSUSE ￼with an ongoing effort to add it to Debian too.

**Comment by schaefi** [comment]
For reference:

https://github.com/containers/buildah/#example

**Comment by schaefi** [comment]
For reference:

https://github.com/opencontainers/image-spec/blob/master/annotations.md

**Comment by schaefi** [comment]
Decision here also impacts Issue #851

**Comment by cyphar** [comment]
:/ If it's necessary to package `umoci` for these other distributions I'd be happy to do it. buildah has some issues with how it handles OCI images which (while somewhat minor) make me concerned about it. But umoci is also used outside of KIWI (and SUSE) -- Cisco and LXC use it for instance.

Obviously I'm biased, but I don't like the idea of dropping umoci support. (And I have had discussions about umoci being part of the OCI -- so then it would theoretically be the "most" supported OCI tool.)

**Comment by schaefi** [comment]
> :/ If it's necessary to package umoci for these other distributions I'd be happy to do it.

I really don't want to make you unhappy and umoci works great the way we use it. I will for sure not drop the use of a successful tool. On the other hand during my years with suse I often realized that we create good tools but for some reason they stay as a suse only thing. At the time we realize it other tools doing the same exists and the one with the lowest hurdle to become installed is taken by users. Yes it would help if umoci is packaged and working on at least RHEL, CentOS, Fedora and openSUSE as these are the distributions you can already find buildah for. If we do this now we would be at the same level but I'm uncertain if it would be a game changer.

If you take a look at:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86/test-image-docker

you see a container build for suse, I can't do this in the same way for e.g Fedora without having umoci build for this target. It's not a big deal but a hurdle for users which might lead them to take a step back from building in obs, because requires preparation work, lead them away from kiwi, lead them to the already present global opinion suse cooks their own soup.

I like to strengthen the suse position here because I think we are really open and any customer could see this if our appliance builder can serve them all and we also demonstrate it. So far kiwi is aligned, I would say 95%, to the core tools as they are present on any major distros. Issues are:

* shim-install
* snapper
* umoci

For the first two kiwi has fallback code such that distributions which follows a different concept are
still supported and I hate my coding here because fallback code is always condemned to fail sooner or later. umoci is an issue we could solve more elegant if it would exist for other distros too I would expect it to just work as it is connected to the OCI spec. However it might happen buildah will persist or make the race on the other side, which imho means kiwi should have an interface to support both until the time solves the problem. I'm open to that as well

> And I have had discussions about umoci being part of the OCI 

I have read the announcements and specs(roughly) on shttps://www.opencontainers.org. I think OCI currently has no recommendation for the tools in any direction. If umoci would be listed as the reference implementation I'm sure it will be number one. If that happens I would say we have to package it up for all major distros to set a clear sign we care. So if you are already in discussions I also think having it available for all players strengthen our position.

I'm not part of that community though, it would be cool to have their support.

**Comment by davidcassany** [comment]
In addition to what have been already said and in a short term or mid term view, `buildah` is not yet present is several SUSE products. I believe the same would happen with `umoci` in other non SUSE distros, even it is properly packaged and well received, it takes time to get into place and into code base streams.

So, having a short/mid term view, I don't see any other option apart from supporting both. Even being just a transitory solution this doesn't look like it could cause terrible maintenance headaches over time. However I haven't yet had a close look each tool features and its parity.

**Comment by Conan-Kudo** [comment]
> :/ If it's necessary to package `umoci` for these other distributions I'd be happy to do it. buildah has some issues with how it handles OCI images which (while somewhat minor) make me concerned about it. But umoci is also used outside of KIWI (and SUSE) -- Cisco and LXC use it for instance.
> 

I requested that someone package `umoci` for Fedora and EPEL some time ago. I even made [a bit of a bet](https://twitter.com/Det_Conan_Kudo/status/965317454066003968) where I'd port OpenShift Origin over to run on openSUSE in exchange for it being packaged by @cyphar in Fedora (it was obviously a lopsided request since OpenShift is way more complex than `umoci`, but I figured that's what it would take...). So far, no `umoci` in Fedora and EPEL.

> Obviously I'm biased, but I don't like the idea of dropping umoci support. (And I have had discussions about umoci being part of the OCI -- so then it would theoretically be the "most" supported OCI tool. Now, this would all depend on how people vote but there is some interest.)

My original request in #764 was to have `buildah` supported as an alternative.

My request still stands: I'd like to use `buildah` as an alternative for `umoci`. Additionally, we should just gut usage of `docker build` and swap that for `buildah`, since `buildah build-using-dockerfile` will work in that case.

**Comment by schaefi** [comment]
I'll work on a code refactoring to allow using both tools, mainly creating an interface class first and will come up with a pull request for further discussion.

I agree to the suggestion of having an alternative. Switching between the tools will be done via the
kiwi runtime configuration file, whereas I will leave umoci as the default tool to not change the current behavior.

**Comment by schaefi** [comment]
After the refactor also adding annotations should be an easier task

**Comment by cyphar** [comment]
@Conan-Kudo Over the past week I've cleared enough off my plate to now actually go and submit umoci to Fedora (and then potentially Debian). There was some work to do this before but the main blocker was that the proposed package ran `go test` (which didn't like running inside `rpmbuild`). In theory this shouldn't be _too_ bad.

**Comment by schaefi** [comment]
@cyphar Sounds great :+1:

**Comment by schaefi** [comment]
Almost ready with the refactoring, will run some real live tests now
