### ISSUE TITLE
Need a way to have /var on a separate partition

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#872]
Due to kernel bugs (and this will be useful in other cases anyway), various container engines can not be used on btrfs with quotas enabled.

As the default location for containers is somewhere in `/var`, the best option is to have it on a separate partition with quotas disabled.

This is not possible to do without changes in kiwi.

**Comment by schaefi** [comment]
We support custom partitions/volumes with LVM+filesystem or by using the native capabilities of the filesystem itself. If btrfs is in trouble on heavily used volume when quotas are enabled it would be good to fix the kernel bugs causing it.

Regarding kiwi; we will not workaround a problem which should be fixed elsewhere. The very ground level partition layout in the msdos or GPT table defines the solid base for the image types we support and provides the setup such that all manipulations e.g disk resize can be done in a clean and stable way without gaps or alignment problems. We will not weaken this structure by a customization of those partitions. With LVM a great opportunity to handle partitions flexible and secure exists and is supported, with filesystems doing the same natively also a great opportunity exists but we expect it to work

We from the kiwi team also provided a solution to this problem which moves /var into an extra partition on boot of the appliance. This concept was implemented by @davidcassany in the caasp area if I remember correctly.

So we already did a lot to help people out of the problems identified with btrfs but we are not weaken the imaging concept to workaround bugs in btrfs

Sorry

**Comment by Vogtinator** [comment]
Please reopen this.

The data-partition-service approach will not work with /var - it does not copy over files. Even if it did, the files must not be duplicated.

**Comment by Conan-Kudo** [comment]
@Vogtinator Is this actually about having `/var` as a separate _partition_ or a separate _subvolume_ with quotas disabled?

**Comment by Vogtinator** [comment]
> @Vogtinator Is this actually about having `/var` as a separate _partition_ or a separate _subvolume_ with quotas disabled?

The former. The latter is unfortunately not possible with btrfs - quotas are enabled/disabled per filesystem.

**Comment by Conan-Kudo** [comment]
So then, we're talking about creating a disk layout that has multiple partitions/filesystems for data. This seems pretty reasonable to me, even beyond "working around bugs".

The major use-case I can think of is that you want to have a fixed size root filesystem, but have a variable size (i.e. partition that can grow) for data.

**Comment by Conan-Kudo** [comment]
@schaefi It sounds like what we need is a mode in which instead of the disk layout being created last, it's created first, then mounted, and then populated?

**Comment by schaefi** [comment]
> The major use-case I can think of is that you want to have a fixed size root filesystem, but have a
> variable size (i.e. partition that can grow) for data.

Setting this up is not a problem. See https://opensource.suse.com/kiwi/building/working_with_images/custom_partitions.html?highlight=partition for further details

The extra partition requested here would break core requirements on the partition table to allow e.g table resize and we are not open up the description to allow that kind of customization.

**Comment by sysrich** [comment]
@schaefi but your above link does not work for the problems described

How can you expect the system to set up /var on first boot?

/var is already going to include countless assets provided by the packages

If we follow the guide you link, then /var ends up empty, and the image is broken

We need partitioning as part of the image creation in kiwi.

Please do not close this bug, I consider this a blocker to Kubic's ability to use kiwi, and is so severe we are having to consider dropping the use of kiwi to work around this issue. This would be embarrassing for all.

I assume the impact on SUSE CaaS Platform is similarly severe, and the stakes there are higher than embarrassment.

**Comment by Conan-Kudo** [comment]
> The extra partition requested here would break core requirements on the partition table to allow e.g table resize and we are not open up the description to allow that kind of customization.

I'm not sure I understand this. Supporting this would be a matter of mandating that only one partition can be "growable" by ensuring it's at the end of the partition table. If you have multiple partitions, you should be forced to set that attribute on _one_ and only _one_ partition.
