### ISSUE TITLE
OEM deployment using iso installstick image broken

### ISSUE THREAD

**Issue by cdoss-lifesize** [SUSE/kiwi#877]
## Problem description
Using the configuration, 
```
<type image='oem' 
boot='oemboot/suse-leap15.0' 
filesystem='ext4' 
bootloader='grub2' 
boottimeout='0' 
firmware='uefi' 
initrd_system='dracut'
installstick='true' 
installboot='install' >
 <oemconfig>
    <oem-swap>true</oem-swap>
    <oem-swapsize>512</oem-swapsize>
    <oem-unattended>true</oem-unattended>
    <oem-skip-verify>true</oem-skip-verify> 
    <oem-silent-boot>true</oem-silent-boot>
  </oemconfig>
 </type>
```
The build creates the iso image but while using it to deploy the image onto the system, displays an error "No devices(s) for installation found". 

## Expected behaviour
Image should get deployed to the target system without any break.

##Note
This used to work till few days back but started showing this issue with image created since Nov 6th. Last working image was build on Oct 31st.

## OS and Software information
+ KIWI version: 9.17.0
+ Operating system: Leap15
+ OBS version: 

##CC @schaefi , @davidcassany

**Comment by schaefi** [comment]
damn I can reproduce it :( sorry for this one will check what happened and fix it

**Comment by cdoss-lifesize** [comment]
Thanks Marcus, tested it and issue is fixed now.
