### ISSUE TITLE
Some way to disable xz compression for vmdk

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#901]
## Problem description

Currently since #869 vmdk image formats, among other, are always compressed in OBS builds. This is causing issues in openQA where they used to grab directly and boot it without preprocessing it.

Apparently it is not simple to add some pre process steps on openQA. This is something they are already doing for raspberry pi images it is really slowing down and over killing the tests.

Now the compression started to happen on TW for x86_64 because of #869 and the issue is likely to spread to many images.

Probably we could think about a way to configure that with the runtime yaml config file. 

## OS and Software information
+ KIWI version: master or Tumbleweed version
+ Operating system: Tumbleweed

**Comment by davidcassany** [comment]
@Vogtinator probably you can add some additional stuff. I am curious to know which are the images facing this issue and I am wondering if there are tests for the formats that were not affected by #869.

**Comment by Vogtinator** [comment]
AFAICT all image formats are compressed now: VHDX, VMDK and QCOW2.

Currently JeOS is only tested for SLE and Leap 15.0, 15.1.

This now blocks adding JeOS testing for Tumbleweed.

**Comment by schaefi** [comment]
Compressing formats was a request from the obs people with regards to storage space and download speed. Thus this was intentionally done in #869. If this needs to change we should come to an agreement which we don't have to revert again. Added the discussion flag

**Comment by schaefi** [comment]
> QCOW2 images are compressed by qemu-img anyway, so this is really a massive antifeature.

This is not quite correct. qcow2 is a block compressed format like others too. But the point is in storage size of the disk image. If the image builds a raw disk and the disk contains effective real data the conversion into the qcow2 format will not compress that data: Here is an example

```
qemu-img create mydisk.raw 2g
fdisk mydisk.raw  ... create e.g an xfs partition
kpartx -a mydisk.raw
mount /dev/mapper/loop0p1 /mnt
dd if=/dev/urandom of=/mnt/fuzzy bs=1M count=1000
umount /mnt
kpartx -d /dev/loop0
qemu-img convert -f raw -O qcow2 mydisk.raw mydisk.qcow2
ls -l mydisk*
   2100363264 Jan 10 11:05 mydisk.qcow2
   2147483648 Jan 10 11:04 mydisk.raw

==> almost the same size

xz mydisk.qcow2

ls -lh *.xz

    1011M Jan 10 11:10 mydisk.qcow2.xz

==> significantly smaller. "Real" images not filled with /dev/urandom usually compresses even better
```

So this is not an antifeature as you name it because it can help to reduce storage space and the upload speed increases. As this was requested for a good reason I'm not reverting it

But I'll create a runtime config option such that you can turn the compression on or off in the bundler and will keep the default to off. People hosting images on obs can decided if they want to keep it compressed or not

**Comment by davidcassany** [comment]
I have been thinking about this issue to my eyes there some options to solve it, none of them perfect.

1. Add decompress feature in openQA: I am an absolute ignorant regarding openQA, thus I have no way to estimate if this is doable or not. IMHO this would be a nice feature for openQA. Anyway I agree that having to code in rush because of some other tool changed is something to avoid.

2. Add a runtime configuration to let user choose if the result is compressed or not, being the current behavior the default. The counter part of it is that any build that requires uncompressed images needs to provide the runtime configuration file.

3. Revert #869 default to uncompressed. We need to agree with OBS guys regarding that. As @schaefi said if we revert we need to agree first that this makes sense all, otherwise we will be again requested to compress at some point.

IMHO it would be feasible to code 1. and 2. in parallel, we could help packaging the runtime configuration file.

**Comment by davidcassany** [comment]
@schaefi ouch just posted before noticing your comment. Anyway I see we are in line

**Comment by Vogtinator** [comment]
I agree that openQA needs to learn to deal with compressed images, but the architecture makes this almost impossible. So this will take quite a while to implement.

I'm in favor of 2 for now, with the default behaviour being no compression at all.

Reason for that is that it needs to be possible to run a kiwi image directly after building, without any steps in betwee.

**Comment by schaefi** [comment]
I'll started to work on this and will come up with the appropriate solution next
