### ISSUE TITLE
Regex validation on volume size seems to be broken

### ISSUE THREAD

**Issue by sveldhuisen** [SUSE/kiwi#905]
## Problem description
I'm using the following LVM setup inside my config.xml for a VMX image based on SLES 12 SP4:

        <systemdisk name="systemVG">
            <volume name="swap" size="8G"/>
            <volume mountpoint="var" name="LVvar" size="115G"/>
            <volume mountpoint="var/opt" name="LVvar_opt" size="10G"/>
        </systemdisk>
        <size unit="G" additive="false">150</size>

I get the following warnings when building the VMX image:

  /usr/lib/python2.7/site-packages/kiwi/xml_parse.py:4258: UserWarning: Value "8G" does not match xsd pattern restrictions: [['^\\d+|\\d+M|\\d+G|all$']]
    warnings_.warn('Value "%s" does not match xsd pattern restrictions: %s' % (value.encode('utf-8'), self.validate_volume_size_type_patterns_, ))
  /usr/lib/python2.7/site-packages/kiwi/xml_parse.py:4258: UserWarning: Value "115G" does not match xsd pattern restrictions: [['^\\d+|\\d+M|\\d+G|all$']]
    warnings_.warn('Value "%s" does not match xsd pattern restrictions: %s' % (value.encode('utf-8'), self.validate_volume_size_type_patterns_, ))
  /usr/lib/python2.7/site-packages/kiwi/xml_parse.py:4258: UserWarning: Value "10G" does not match xsd pattern restrictions: [['^\\d+|\\d+M|\\d+G|all$']]
    warnings_.warn('Value "%s" does not match xsd pattern restrictions: %s' % (value.encode('utf-8'), self.validate_volume_size_type_patterns_, ))

## Expected behaviour
My volume sizes should be validated by Kiwi. The regular expressions seems to be correct, but somehow they do not match.

## OS and Software information
+ KIWI version: 9.15.3
+ Operating system: SLES 12 SP4
+ OBS version: none

**Comment by sveldhuisen** [comment]
The mentioned Kiwi version is not correct. I have this issue with 9.16.18.

**Comment by sveldhuisen** [comment]
Thanks for the explanation david! Looking forward to a fix.

**Comment by davidcassany** [comment]
The fix has been ported to relevant projects (SUSE/kiwi_sle12@80861f08574f84541d1643175158602f0fc7556e and SUSE/kiwi_sle15@1eed0a062d556d41e38ad13c24e86b48d9003ea3) and kick started the maintenance update procedure.

I guess the might take a while having the fix published to the repositories, specially having Christmas right around the corner and because of not being a security fix or a critical issue.
