### ISSUE TITLE
Transport protocol for exposed ports of Docker images can't be set

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#906]
## Problem description

Docker images have exposed ports in Dockerfiles using the following syntax:

```
EXPOSE <port> [<port>/<protocol>]
```

Where `<protocol>` can be `upd` or `tcp` and defautls to `tcp` when it is not specified, see [docs](https://docs.docker.com/engine/reference/builder/#expose).

In KIWI schema we can just apply a port number. So I believe we are always exposing TCP ports only.

In kiwi ports definition is mapping the `umoci config --config.exposedports` option. We need to verify how this tools is handling exposed ports transport protocol and, if possible, map that to KIWI schema and to related umoci classes.

**Comment by davidcassany** [comment]
@cyphar do you have any idea about how to deal with this using `umoci`? thanks

**Comment by cyphar** [comment]
The format is the same as `docker run -p` -- that is, you represent it with `--config.exposedports '80:80/tcp'`.

**Comment by cyphar** [comment]
Sorry, I was wrong about the `80:80/tcp` thing. It's just `<port>[/<protocol>]`.

> I guess OCI (umoci) uses the same default to TCP as Docker does right?

`umoci` just uses whatever string you give it -- it doesn't do any validation. But the OCI specifies the following:

> A set of ports to expose from a container running this image. Its keys can be in the format of: `port/tcp`, `port/udp`, `port` with the default protocol being tcp if not specified. 

So, `tcp` is the default.

**Comment by davidcassany** [comment]
@chyphar, thanks much now I have all information to proceed.
