### ISSUE TITLE
Cmd sets to '/bin/bash' if there's only entrypoint

### ISSUE THREAD

**Issue by drpaneas** [SUSE/kiwi#914]
## Problem description

In my .kiwi definition I have only `<entrypoint execute="/traefik"/>` and I've noticed that when I load the docker image and do inspect, there's a CMD argument that automatically sets itself to `/bin/bash`.

This is a major problem in my case, since the command that gets executed is: `traefik /bin/bash` which is obviously wrong.

You can find my kiwi file at [my home obs project](https://build.opensuse.org/package/view_file/home:pgeorgiadis:branches:devel:kubic:containers/kubic-traefik-image/kubic-traefik-image.kiwi?expand=1)

```
tux@ultron:~/compare$ diff -Nur ours upstream 
--- ours	2019-01-10 22:09:39.450430990 +0100
+++ upstream	2019-01-10 21:29:27.599141044 +0100
@@ -14,10 +14,8 @@
             "Env": [
                 "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
             ],
-            "Cmd": [
-                "/bin/bash"
-            ],
-            "Image": "",
+            "Cmd": null,
+            "Image": "sha256:5e69e9a0aa6b1eca85288812eebe00ad0d04db03ecdf978b73de24692df54f38",
             "Volumes": {
                 "/tmp": {}
             },
@@ -32,7 +30,6 @@
                 "org.label-schema.name": "Traefik",
                 "org.label-schema.url": "https://traefik.io",
                 "org.label-schema.vendor": "Containous",
-                "org.label-schema.version": "v1.7.7",
-                "org.openbuildservice.disturl": "obs://build.opensuse.org/openSUSE:Factory/images/4985c42063a1f194292ecb777d41923b-opensuse-tumbleweed-image:docker"
+                "org.label-schema.version": "v1.7.7"
             }
         },
```

## Expected behaviour

To not create any CMD and leave it at NULL

## Steps to reproduce the behaviour

See [my project](https://build.opensuse.org/package/view_file/home:pgeorgiadis:branches:devel:kubic:containers/kubic-traefik-image/kubic-traefik-image.kiwi?expand=1)

## OS and Software information
+ KIWI version: python3-kiwi-9.17.7-1.1.x86_64
+ Operating system: openSUSE TW
+ OBS version:

**Comment by davidcassany** [comment]
@drpaneas after having a closer look I realized this not a bug, but a feature :sweat_smile: Let me explain what is happening here.

By default KIWI sets the `CMD` to `/bin/bash` by default if no `ENTRYPOINT` or `CMD` are provided. In case of any of those is provided it **only** sets the provided one, leaving the other untouched. This behavior is simple and intuitive for base images, but not that much for derived ones. For the derived images the `CMD` and `ENTRYPOINT` are also inherited, thus if the base image has a `CMD` set it is inherited to the derived image **unless** it is is overwritten by the derived image definition. In your case happens the following:

Base image has:

```json
{
  "ENTRYPOINT": [],
  "CMD": ["/bin/bash"]
}
```

Thus the derived image inherits this data and overwrites only the `ENTRYPOINT` definition:

```json
{
  "ENTRYPOINT": ["traefik"],
  "CMD": ["/bin/bash"]
}
```

The good thing is that kiwi allows you to clear the command. Consider the following:

```xml
<containerconfig>
  <entrypoint execute="/traefik"/>
  <subcommand clear="true"/>
</containerconfig>
```

The more I think about it the more I am convinced I dislike the `CMD` and `ENTRYPOINT` distinction docker does... having dual commands leads to this confusing scenarios. I see very little gain on splitting the command if we consider the confusion and complexity it introduces. A single and explicit command field would have been way more simple without relevant feature loss, IMHO.
