### ISSUE TITLE
Docker containers have broken history

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#918]
It looks like the way #852 is implemented results in broken history entries inside of containers.

```
ID             CREATED      CREATED BY    SIZE   COMMENT
c8a6d5afa5f2   7 days ago   KIWI 9.17.7   0B
```

This breaks at least podman completely:

```
error copying layers and metadata for container "536665b70daae353a4a744977cfe7fccd32d342ed413dc7b3473ee81fe30393a": Error initializing source containers-storage:tw: internal error: history lists 1 non-empty layers, but we have 2 layers on disk
```

CC @cyphar

**Comment by cyphar** [comment]
Do you have a link to the generated image?

**Comment by Vogtinator** [comment]
Just `podman pull opensuse/tumbleweed` - the direct download from OBS is unfortunately broken.

**Comment by davidcassany** [comment]
@cyphar Just to add some details about KIWI procedure. We do something like:

```bash
umoci unpack
# do stuff
umoci repack --no-history
umoci config ....
skopeo copy oci:.... docker-archive:....
```

**Comment by cyphar** [comment]
Okay, so that issue is probably that you should be doing `umoci config --no-history`. You want a history entry for `umoci repack`.

**Comment by davidcassany** [comment]
All right, we did this way because from a scripting perspective having all configurations (whatever is included in `containerconfig` in kiwi file) as part of the `umoci config` call was easier to handle. Anyway I am working in a patch for that.
