### ISSUE TITLE
Request to add rpm cache location configurable

### ISSUE THREAD

**Issue by SantoshKumar4** [SUSE/kiwi#92]
## Problem description
Currently kiwi 8 creates a directory in /var/cache and puts downloaded rpms in there. We are wanting to contain all the files that gets created during the kiwi appliance creation process within the targetdir so that we manage them appropriately. Please provide an option to override the default behavior.

## Steps to reproduce the behaviour

verbatim from kiwi google groups:
==========================

Actually the package manager cache is to share data for all builds on 
the building host, thus I had planned to keep this as a fixed location. 
However it is possible to use another location for it, there is just 
no switch to change from the default place implemented 

If you need that please open an issue on the github issue page 

Regards, 
Marcus

**Comment by schaefi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [configurable cache location](https://trello.com/c/KwBsJfBU/195-configurable-cache-location)
