### ISSUE TITLE
Find EFI binaries under '/usr/share/efi'

### ISSUE THREAD

**Issue by rw4s** [SUSE/kiwi#924]
## Problem description
In SUSE products EFI binaries are historically located in `/usr/lib*/efi`, where `lib64` has always been questionable (to say the least).  In a recent move to package `grub2` as `noarch` (FATE#326960), a collision between `x86_64` and `aarch64` has been identified, as both place platform-specific files in
the same spot. To rectify this, a new location was devised: `/usr/share/efi/$(uname -m)`.  For a (as of yet undetermined) transition period symblic links should be available in the old location.

At the same time `/usr/lib/grub2` will move to `/usr/share/grub2`, so if KIWI tries to directly access grub2-modules...  (a symbolic link is unfortunately not available in this case)

## Expected behaviour
Prefer `/usr/share/efi/$(uname -m)` (for all EFI binaries, be it `grub2`, `shim`, `fwup*`, XEN)
and `/usr/share/grub2` (for `grub2` stuff) over the legacy locations.

**Comment by davidcassany** [comment]
@rw4s do you have any hint about how to test and experiment with this new grub2 package? I as far as I saw this SR#182647 is not yet approved. I am wondering which is the scope of the change, is this already in Factory?

**Comment by davidcassany** [comment]
> how about directly from Base:System/grub2?

Good thanks.

> And a Factory submission is in flight as well.

So we should keep an eye to  SR#182647 (for SLE15SP1) and to SR#668555 (for Factory).
