### ISSUE TITLE
Install into existing image root

### ISSUE THREAD

**Issue by randyesq** [SUSE/kiwi#929]
## Problem description
I have an existing image root, and I would like to use Kiwi to install more content and run scripts against that image root. I don't know if this can be done today or not based on what I found in the documentation.

## Expected behaviour
I expect that this should be possible, but maybe the details are messy.

## Steps to reproduce the behaviour
N/A

## OS and Software information
+ KIWI version: latest
+ Operating system: N/A
+ OBS version: N/A

**Comment by davidcassany** [comment]
@randyesq yes this is possible. Consider the following command call:

`kiwi-ng system build --description <yourprjfolder> --target-dir <yourdstfolder> --allow-existing-root`

Using this command KIWI places the root folder in `<yourdstfolder>/build/image-root/` and it just reuses whatever is already in there. So by copying all your root to  `<yourdstfolder>/build/image-root/` and using the `--allow-existing-root` flag you should be done.

May I ask about your use case? I am curious to know the motivation of doing that.

**Comment by schaefi** [comment]
As David said ```--allow-existing-root``` is what you need

Please be aware using an existing root tree content can lead to inconsistent image systems. For anything you plan to release to customers or you might want to certify you should not allow an image build like this. I regularly use that option because it speeds up the build but only for testing purposes

**Comment by randyesq** [comment]
Thanks for the responses. Perhaps a docs change is in order for this issue. I asked the question because of this sentence in the docs "KIWI will exit with an error if the target root tree already exists to avoid accidental deletion of an existing unpacked image." https://opensource.suse.com/kiwi/overview/workflow.html?highlight=exit%20with

My use case is allowing users to further customize an image root after the image has already been built. For instance they may have booted the image and realized that they want to change it slightly without taking the time to rebuild.
