### ISSUE TITLE
kiwi breaks with new zypper - needs to ignore 103 exit code

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#932]
zypper in TW now exits with 103 indicating that a reboot is necessary when installing a kernel package.
Currently kiwi understands this as a failure and aborts.

https://github.com/openSUSE/zypper/pull/237/files#diff-a79d0bc6ca61bc4205820dbe614997d0R37

**Comment by davidcassany** [comment]
Oh that's bad... why on earth are they returning a non zero value for that? We will end up filtering every single zypper's error code :disappointed:

**Comment by Vogtinator** [comment]
I'd also argue this is a bug in zypper, but there is no real difference between updating a kernel (= installing a newer version) and installing it...

**Comment by davidcassany** [comment]
@Vogtinator do you have any failing project to look at? I saw this zypper version is not yet in Factory if I am not mistaken, in TW there is v1.14.19 and it is included in v1.14.23. So probably we still have a chance to understand the motivations for the change and find a good solution for it before it hits us.

**Comment by Vogtinator** [comment]
@davidcassany It was in Tumbleweed and broke building, but I convinced the RM to revert the change in zypper until a solution is found. I don't currently have any project with the failure present, but it should be easy to reproduce it by building against zypp:Head.

**Comment by davidcassany** [comment]
I see, I was surprised not to see it in Factory and got confused.

**Comment by schaefi** [comment]
Unbelievable, I wrote Michael Andres an e-mail, they can't be serious on such a change. I'm not willing to add stupid hacks just to address this.

**Comment by davidcassany** [comment]
I am closing the issue, according to https://github.com/openSUSE/zypper/pull/237#issuecomment-460981928 this change will not be applied and zypper behavior will remain consistent.
