### ISSUE TITLE
KIWI does not allow creating images with current transactional-update mechanism

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#945]
transactional-update 1.12 moved from using `/etc/fstab.sys` to `/etc/fstab` - so that needs special modifications.

Those are done by the `read-only-root-fs` package during package installation, but at that time `/etc/fstab` is not populated yet.

So a workaround would be to add the necessary entry in `config.sh` - that's how it was done until now, but kiwi overwrites the `/etc/fstab` completely in a later stage.

This makes it impossible to create images using transactional-update currently.

**Comment by schaefi** [comment]
we support custom fstab additions via ```/etc/fstab.append``` if you create your modifications in config.sh writing out that file it will be taken into account when kiwi writes fstab. That should work for you, shouldn't it ? Also see: #694 

Let me know if that works for you. Thanks

**Comment by Vogtinator** [comment]
Unfortunately not - the `/var` entry needs to be edited, so appending is not enough.

**Comment by schaefi** [comment]
Hmm, ok. Would applying a patch work for you ? So if we allow ```/etc/fstab.patch``` could also be in combination with .append you should be able to maintain a patch file as overlay. If patching fails you also directly get notified something has changed and the fstab massage needs to be checked. Thoughts ?

**Comment by Vogtinator** [comment]
> Hmm, ok. Would applying a patch work for you ? So if we allow `/etc/fstab.patch` could also be in combination with .append you should be able to maintain a patch file as overlay. If patching fails you also directly get notified something has changed and the fstab massage needs to be checked. Thoughts ?

Sounds like an over-engineered hack to me, but it would technically work if I add another hack in `config.sh`.

It would be much nicer if `/etc/fstab` was written before packages get installed, that way everything just works without any hacks.

**Comment by schaefi** [comment]
The contents of fstab written by kiwi are the ones mandatory to the system because read by e.g systemd or dracut. If you take a look at what kiwi writes it looks like this:

```
cat /tmp/mytest/build/image-root/etc/fstab 
UUID=5b72249b-4d9c-495f-a539-2fc5d129852b / ext4 defaults 1 1
UUID=1B1A-42A5 /boot/efi vfat defaults 0 0
```

The information about UUID's or labels of filesystems partitions is not present before packages gets installed. All this can be done after the root tree has been installed and the real image creating steps starts. So what you are suggesting makes no sense.

> Sounds like an over-engineered hack to me, but it would technically work if I add another hack in
> config.sh.

Don't see why applying a patch is over-engineered to you. A one liner from a coding perspective and you also don't put that into config.sh but maintain it as a clear, visible, explicit and nicely readable file to the overlay tree of your image description.

**Comment by Vogtinator** [comment]
> The information about UUID's or labels of filesystems partitions is not present before packages gets installed. All this can be done after the root tree has been installed and the real image creating steps starts. So what you are suggesting makes no sense.

It makes a lot of sense - kiwi just does everything backwards.

YaST for instance creates partitions first and then writes into them, while kiwi prepares everything and then copies it over into the disk images. If you pregenerate the UUID's, `/etc/fstab` can be generated before installing packages.

> Don't see why applying a patch is over-engineered to you. A one liner from a coding perspective and you also don't put that into config.sh but maintain it as a clear, visible, explicit and nicely readable file to the overlay tree of your image description.

Yeah, but it's just a forked off and totally independent and different copy of `read-only-root-fs`' %post script.

**Comment by schaefi** [comment]
YaST works on the target and has full access to the underlaying hardware, which it can probe and prepare and then install. This is different from the approach to create an image from a root system where the target comes last not first.

You argue with me that kiwi does everything backwards when the image builder sees the hardware last and yast sees it first. Yes things are exactly the opposite here. That's why there is yast and kiwi.
yast base its decisions on the hardware and kiwi base its decisions on the root tree. yast requires the hardware kiwi requires the root_tree

In kiwi we install first into a new directory, we simply don't have more and that's our start. I'm really sorry but the process is different and that impacts the time at which system components show up.

Maybe the process you need would be better covered by an autoyast profile ?

**Comment by Vogtinator** [comment]
I'm not saying that the way kiwi does things is wrong - it's just different enough to break certain setups.

Generating fstab before installing packages should be perfectly doable and would allow proper support of `read-only-root-fs`.

**Comment by Vogtinator** [comment]
Please reopen - fstab.patch does not actually fix this.

**Comment by Vogtinator** [comment]
> Please reopen - fstab.patch does not actually fix this.

Let me provide a concrete example:

Kubic is built with different profiles using _multibuild for different architectures.
Depending on the profile and architecture, the list of subvolumes is different. As those are all mentioned in /etc/fstab, it's not possible to have a patch that applies to all archs.

Apart from that it's a hack - the modification to fstab done in the image build is independent from the modification done during proper installation of `read-only-root-fs`. This means it can get out of sync and result in either missing fixes or even a non-bootable image.

**Comment by schaefi** [comment]
> Kubic is built with different profiles using _multibuild for different architectures.

* package the fstab patch, append as needed for the profile
* install the package based on profile

   ```xml
   <packages type="image" profiles="A">
       <package name="fstab-extension-A"/>
   </packages>
   ```

> Apart from that it's a hack - the modification to fstab done in the image build is independent from the
> modification done during proper installation of read-only-root-fs. 

Don't understand that. The installation of the package read-only-root-fs and the package that provides the fstab adaptions happens in the same transaction during build time

**Comment by Vogtinator** [comment]
Apparently I missed the latest reply here for some reason.

> > Kubic is built with different profiles using _multibuild for different architectures.
> 
> * package the fstab patch, append as needed for the profile

I thought `fstab.patch` would be next to `config.sh` or the image description, this makes a bit more sense.
However, adding a package with just a patch inside used for building is even more of a hack IMO.

> * install the package based on profile
>   ```
>   <packages type="image" profiles="A">
>       <package name="fstab-extension-A"/>
>   </packages>
>   ```
> 
> > Apart from that it's a hack - the modification to fstab done in the image build is independent from the
> > modification done during proper installation of read-only-root-fs.
> 
> Don't understand that. The installation of the package read-only-root-fs and the package that provides the fstab adaptions happens in the same transaction during build time

Yes, but it's not the change implemented in `read-only-root-fs` which changes fstab, it's a manual recreation of those effects, which might not be identical.

Having the patch inside a package doesn't solve any of the issues I raised, in fact it makes it worse:
* fstab changes have to be maintained in separate packages instead of in the image
* There have to be *many* of those packages as not all flavors and not all architectures have the same resulting fstab
* It breaks at any point in time if the fstab changes for some reason
* It's a package which needs to be explicitly uninstalled again, otherwise the user might have a useless file in `/etc`

**Comment by schaefi** [comment]
sorry for the late reply.

> it's a manual recreation of those effects, which might not be identical.

if you setup your image description to use

```xml
<type ... devicepersistency="by-label" .../>
```

The entries in the fstab will always be the same and the patch apply will not break.
By default we use device names by uuid and those changes with a new build.

> It breaks at any point in time if the fstab changes for some reason

In case labels are used I think you want that it breaks if the patch would not apply anymore

> There have to be many of those packages...
> t's a package which needs to be explicitly uninstalled again..

So the package approach seems to be not good for your use case. You can go with profiled archives then. Please note the fstab.patch file itself will be deleted by kiwi when applied successfully. So the system will not be tainted by that file. With the archive approach you can create fstab.patch files in tar archives which you put as part of your image description. In your XML you can then write

```xml
<packages type="image" profiles="A">
    <archive name="fstab-extension-A.tgz"/>
</packages>
```

This will limit the maintenance to the image description only

**Comment by Vogtinator** [comment]
> sorry for the late reply.
> 
> > it's a manual recreation of those effects, which might not be identical.
> 
> if you setup your image description to use
> 
> ```
> <type ... devicepersistency="by-label" .../>
> ```
> 
> The entries in the fstab will always be the same and the patch apply will not break.
> By default we use device names by uuid and those changes with a new build.

What I meant by that was that what the patch does might not be identical to what the "official source" in  `read-only-root-fs` does, for instance after bugfixes.

The use of UUID vs. Label is a good point though, I'd like to avoid using LABEL anywhere. Except for the ability to patch fstab more reliably, there are no actual upsides. While mounting by UUID doesn't help if you have the same image attached to a system twice, it helps if you have different images attached.

> > It breaks at any point in time if the fstab changes for some reason
> 
> In case labels are used I think you want that it breaks if the patch would not apply anymore

Not really - the `read-only-root-fs` package's script for modifying the fstab is meant to work in every case, so that would be a maintainability regression.

> > There have to be many of those packages...
> > t's a package which needs to be explicitly uninstalled again..
> 
> So the package approach seems to be not good for your use case. You can go with profiled archives then. Please note the fstab.patch file itself will be deleted by kiwi when applied successfully. So the system will not be tainted by that file. With the archive approach you can create fstab.patch files in tar archives which you put as part of your image description. In your XML you can then write
> 
> ```
> <packages type="image" profiles="A">
>     <archive name="fstab-extension-A.tgz"/>
> </packages>
> ```
> 
> This will limit the maintenance to the image description only

Sounds better indeed, but this is still a huge maintenance effort compared to just running two commands to edit `/etc/fstab`.

**Comment by schaefi** [comment]
A better solution that also uses the read-only-root-fs script is now available:

* https://github.com/OSInside/kiwi/pull/1182
