### ISSUE TITLE
Additional bundler packages file

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#949]
## Problem description

The OBS team tracks package data from image builds and cannot assign them to the image type which has been built. Therefore the bundler should create a new metadata file named

```
image-name.<value_of_type_image_attribute>
```
The contents of that file should be the bundled files e.g the image files ```image-name.vmdk, image-name.vmx``` which belongs to the image build of type ```vmx``` with format set to ```vmdk```

**Comment by adrianschroeter** [comment]
we are looking into a possible solution for the problem without the extra file. So this may not be needed actually ... will tell you more next week.

**Comment by schaefi** [comment]
ok

**Comment by schaefi** [comment]
@adrianschroeter Any news on this one ?

**Comment by schaefi** [comment]
> So this may not be needed actually ... will tell you more next week.

I guess this is true due to no further information
