### ISSUE TITLE
Replace Path with py.path.local

### ISSUE THREAD

**Issue by tomschr** [SUSE/kiwi#95]
## Problem description

The `Path` class in `kiwi/path.py` uses `Command` to create and remove directories. The implementation uses shell commands which isn't very pythonic.

## Suggested Solution

This is just a crazy idea and I don't know if it is useful at all (read: more cons than pros).

To avoid calling shell commands in `Path` we could use the `py` module. This contains the `py.path.local` class which is an object oriented view on files and directories (see [documentation](http://pylib.readthedocs.io/en/latest/path.html) for more information.)

To get the functionality on openSUSE install the `python3-py` package. It comes also with some other nice features which could be beneficial for KIWI.

### Advantages

* OOP view on files and directories which simplifies some code
* No more `os.path.join`, just `path / file`
* It's pythonic! :grinning:

### Downsides

* Code needs to be rewritten at some places
* Test cases needs to be refactored
* Another dependency

@schaefi Do you think this is worth the effort?

**Comment by schaefi** [comment]
The only concern I have is to introduce yet another python module dependency

stuff like 'rmdir -p --ignore-fail-on-non-empty' should also be covered. If it can't be replaced completely I vote for not changing this part at the moment

**Comment by tomschr** [comment]
> stuff like 'rmdir -p --ignore-fail-on-non-empty' should also be covered.

The manpage of `rmdir` says:

```
--ignore-fail-on-non-empty
              ignore each failure that is solely because a directory is non-empty
```

the docstring of `py.path.local.remove` says this:

```python
def py.path.local.remove(self, rec=1, ignore_errors=False)
   """remove a file or directory (or a directory tree if rec=1).
      if ignore_errors is True, errors while removing directories will be ignored.
   """
```

Sounds like almost the same.

**Comment by isbm** [comment]
I am voting down this as "No", until someone explains me what is wrong with the `os.makedirs` and `shutil.rmtree` functions. The `rmdir -p --ignore-fail-on-non-empty` thing is right there.

Also bringing "It's pythonic!" calls _standard Python library_ as non-pythonic. Which I am not agree with.

**Comment by schaefi** [comment]
Let's go with the standard library, I also don't see an urgent reason to move at this time
