### ISSUE TITLE
CentOS 7 gdisk seems to always error out on relocating backup GPT

### ISSUE THREAD

**Issue by seife** [SUSE/kiwi#958]
## Problem description
A CentOS 7 kiwi oem image (PXE tested, but will also try ISO) fails during boot with
`Failed to write backup GPT at end of disk`
Investigating, I found that the gdisk command always exits with exit code 1 and then kiwi-partitions-lib.sh dies with:

```
    rm -f ${cmd_file} && for cmd in x e w y; do
        echo $cmd >> ${cmd_file}
    done
    if ! gdisk "$1" < ${cmd_file} &>/dev/null; then
        die "Failed to write backup GPT at end of disk"
    fi
```

## Steps to reproduce the behaviour
deploy the image from https://build.opensuse.org/package/show/home:seife:kiwitest-centos/centos7-pxe and see it fail

## OS and Software information
+ KIWI version: latest from obs://Virtualization:Appliances:Builder/CentOS_7
+ Operating system: CentOS 7 as available in build.opensuse.org
+ OBS version: build.opensuse.org

**Comment by seife** [comment]
I forgot: if I replace "die" with "warn", the image deploys just fine and lives happily ever after.

**Comment by seife** [comment]
this ISO https://build.opensuse.org/package/show/home:seife:kiwitest-centos/centos7-iso shows the same issue and is even easier to test in qemu :-)

**Comment by schaefi** [comment]
Thanks, I had a look on this one and so far I couldn't find a better solution than making the issue a warning. The distributed gdisk version on centos cannot easily be changed. There is an updated version but if the image is not build with it we can't do much.

**Comment by schaefi** [comment]
Also plan to run partprobe in case gdisk failed to re-read the partition table

**Comment by seife** [comment]
Marcus, I think the "could not read partition table" error I got is not the real problem. Actually the partition table does not get altered at all by gdisk, it's just the GPT that gets moved to the end of the disk.
Also, in the dracut initrd, I do not see this error, but still get exit code 1.

In fact, it looks like the CentOS gdisk *always* exits with 1, even for `gdisk -l /dev/sda`.
This, in turn, could be used to detect such a strange behaving gdisk version...

**Comment by seife** [comment]
Even better: we can replace the whole gdisk thing with `sgdisk -e /dev/sda`

**Comment by schaefi** [comment]
```
 -e, --move-second-header                  move second header to end of disk
```

That sounds really good :+1: let's do that. I'll send a PR tomorrow
