### ISSUE TITLE
Improve the KIWI documentation

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#981]
## Problem description

The current KIWI documentation is pretty good and very extensive. Nevertheless, it has some weak points and I (as a newcomer) found it relatively complicated to figure out how to get kiwi to do what I want. Without the great help from @schaefi and @davidcassany on the KIWI Riot channel, I wouldn't have been able to get this far.

Imho there are two major points that could be improved about the docs:
1. Working with Kiwi means that you tweak the two important files: `config.sh` and `distro.kiwi`. This should be stressed out as early as possible and backed up by examples. You have to read a lot until you get a general idea how to work with kiwi.
  Consider the average user that opens the documentation: they land on this page: https://opensource.suse.com/kiwi/index.html, where they won't really find a lot about how to work with kiwi. If they click on `Next` or `Overview` then they get presented with a lot of text about the concepts behind KIWI (which to be frankly honest, newcomers will skip as this ) and then a comparison to the old KIWI. If the new user is still browsing in the overview subcategory, they'll find the [Basic Workflow](https://opensource.suse.com/kiwi/overview/workflow.html). This is the part that the newcomer needs. Unfortunately I found it very confusing at first, as it contains a lot of details.

2. The `distro.kiwi` file is only documented as an XML schema documentation and via examples.
    I know that this is a manpower problem and cannot be easily fixed. Nevertheless, having a documentation of the xml file in text form (like the old kiwi did: https://doc.opensuse.org/projects/kiwi/doc/#sec.description.config.xml) would be highly beneficial.

### Suggestions for improvement

* Make the [Basic Workflow](https://opensource.suse.com/kiwi/overview/workflow.html) section more visible (= easier to find). Either simplify the text or create a separate tutorial or extend the quickstart section, which should stress out the following:
  - Working with Kiwi means that you create an OS image from at least two files: `config.xml` and `config.sh` with a very brief description what these do
  - Minimal examples for both files
  - Example command how to run these
  - Links to additional docs containing further details

* Steal the xml documentation from https://doc.opensuse.org/projects/kiwi/doc/#sec.description.config.xml and adapt it to the current kiwi.

* Consider adhering more to the "common Github style" of laying out the documentation: most github projects have a relatively extensive Readme that is often a mini-tutorial, a `Contributing.md`, maybe a `coding_style.md` etc. Most of these information are already present in the doc subdirectory, we could make them more visible by putting them into the root folder and including them in the actual sphinx documentation.

**Comment by tomschr** [comment]
@dcermak I absolutely agree to what you've wrote! Especially as you've wrote that from a beginners perspective. Well done! :+1:

One question to the "Steal the XML documentation from ... and adapt it to the current KIWI": what is your idea here? Adding the complete documentation would be probably too much for a beginner. But having some important tags (and a link to a reference) would IMHO be useful.

Thanks for all the valuable feedback! :+1:

**Comment by dcermak** [comment]
> @dcermak I absolutely agree to what you've wrote! Especially as you've wrote that from a beginners perspective. Well done! +1
> 
> One question to the "Steal the XML documentation from ... and adapt it to the current KIWI": what is your idea here? Adding the complete documentation would be probably too much for a beginner. But having some important tags (and a link to a reference) would IMHO be useful.

Copy + paste was my initial idea, but I think it would be better to create more of a step by step tutorial that walks the user through all the required elements, but not more, since that would require a lot of duplication with respect to the relax NG documentation.

> 
> Thanks for all the valuable feedback! +1

**Comment by tomschr** [comment]
> Copy + paste was my initial idea, but I think it would be better to create more of a step by step tutorial that walks the user through all the required elements, but not more, since that would require a lot of duplication with respect to the relax NG documentation.

I see. Yes, that would be probably more helpful as a reference is a quite dry and boring topic. :wink: 

By the way, I would like to pinpoint a bit what we currently have:

* A Quick Start
  For beginners. Same as for the "Basic Workflow"; maybe we can somehow merge them together (as you already rightfully suggested).
* A Howto Guide
  For users who already have some experience and want a specific solution to a specific problem.
* Development Guide
  Well, you guessed it already, for developers. Here you can find about the project itself (contributions), references for KIWI commands and KIWI elements/attributes for the RNG schema.

Each guide serves different target groups. Why? Because different groups have different needs. 
What we maybe need is to restructure here and there or group things in a more logical way. You already gave us some good feedback.

Coming back to your original sentence with the idea of a step-by-step tutorial, the questions we should solve are:

* What target group is it? Do we have that target group already? Or is it a new one?
* What example do we use?
  A tutorial is usually a guide where an expert ("the author") takes the hands of the reader and giving him step-by-step instructions. Therefor we need a good example which is easy to write and easy to follow.
* Is it a separate guide or something that can be added as another division?
* Anything else that I forgot? :wink:

**Comment by dcermak** [comment]
> I see. Yes, that would be probably more helpful as a reference is a quite dry and boring topic. wink
> 
> By the way, I would like to summarize a bit what we currently have:
> 
>     * A Quick Start
>       For beginners. Same as for the "Basic Workflow"; maybe we can somehow merge them together (as you already rightfully suggested).
> 

I'd keep the quick start around as it is, since it shows you how to create an image in as few steps as possible. Basic workflow on the other hand is very detailed in some regards, but completely lacks any documentation with respect to the XML schema. I wanted to build something on that document, by simplifying some parts and extending others.


>     * A Howto Guide
>       For users who already have some experience and want a specific solution to a specific problem.
> 

That's what I essentially plan to write.

>     * Development Guide
>       Well, you guessed it already, for developers. Here you can find about the project itself (contributions), references for KIWI commands and KIWI elements/attributes for the RNG schema.
> 
> 
> Each guide serves different target groups. Why? Because different groups have different needs.
> What we maybe need is to restructure here and there or group things in a more logical way. You already gave us some good feedback.
> 
> Coming back to your original sentence with the idea of a step-by-step tutorial, the questions we should solve are:
> 
>     * What target group is it? Do we have that target group already? Or is it a new one?
> 
>     * What example do we use?
>       A tutorial is usually a guide where an expert ("the author") takes the hands of the reader and giving him step-by-step instructions. Therefor we need a good example which is easy to write and easy to follow.
> 
>     * Is it a separate guide or something that can be added as another division?
> 
>     * Anything else that I forgot? wink

My target group is: newcomers that have read the quickstart and now want to know how to work with KIWI. I'd like to write it for someone that has little experience with appliances and never worked with KIWI or it's predecessor.

**Comment by tomschr** [comment]
> > [... Quick Start ...]
> 
> I'd keep the quick start around as it is, since it shows you how to create an image in as few steps as possible. Basic workflow on the other hand is very detailed in some regards, but completely lacks any documentation with respect to the XML schema. I wanted to build something on that document, by simplifying some parts and extending others.

Good idea. One idea---which I haven't looked into it yet---could be to "merge" these two building blocks (existing Quick Start and the "Basic Workflow") into one new Quick Start. I'm not sure if this is useful as I didn't dig deeper into them.


> > [... Howto Guide ...]
> >   For users who already have some experience and want a specific solution to a specific problem.
> 
> That's what I essentially plan to write.

I should have written it more carefully, sorry. We have that already, I think this covered under the [Building Images](https://opensource.suse.com/kiwi/building.html#) chapter. I usually refer to this topics as the "Howto Guides". :wink: 

Or does your thoughts go into a different direction?


> > Coming back to your original sentence with the idea of a step-by-step tutorial, the questions we should solve are:
> [...]
> My target group is: newcomers that have read the quickstart and now want to know how to work with KIWI. I'd like to write it for someone that has little experience with appliances and never worked with KIWI or it's predecessor.

Oh, that perfectly describes me! You found your target group. :laughing:  
Joking aside, it could be a bit difficult to really separate these two target groups. Naturally, they have some overlaps, so it might be a good idea to think what their needs are. That outcome will definitely influence the two documents.

---

So, if I understood it correctly, I summarize it what we found together (please correct me, if I'm wrong):

* Quick Start
  existing documentation; maybe merge it with "Basic Workflow" if possible.
* Howto Guides
  we already have that, probably they can be kept as it is. No need to change it as far as I can see.
* References
  Also not much to do here. Maybe introduce a new chapter title "Reference" and move "KIWI Commands", "Schema Documentation", and "API Documentation" under that new chapter.
* Development and Contributing
  Can also be kept as it is, right?
* Tutorial [new]
  That would be your new topic Dan, right?

Does that work? Any concerns?

**Comment by schaefi** [comment]
Thanks much many doc related changes applied as result of this issue:

* #1076 
* #1093
* #1089
* #1075
* #1079
* #1073
* #1072

I'm closing on behalf of that great work. For further doc topics please let us open new issues.

Thanks again, great job :)
