### ISSUE TITLE
KIWI calls config.sh via bash thereby ignoring the shebang

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#984]
## Problem description

KIWI calls the `config.sh` script during image creation explicitly via bash (see: [setup.py:869](https://github.com/SUSE/kiwi/blob/b20545897b0ef3422ffa197ce14fabb6646ab9f4/kiwi/system/setup.py#L869)):
``` Python
            config_script = Command.call(
                ['chroot', self.root_dir, 'bash', '/image/' + name]
            )
```

This has the downside, that scripts which specify a different shebang, like `#!/bin/bash -e` or `#!/bin/sh` will not work as expected.

## Expected behavior

Either, this should be explicitly stated in the docs with a big red warning or the script should be called directly. If this behavior should not change, then I'd suggest that we remove every shebang from all the examples, since that suggests that it actually does something.

## Steps to reproduce the behavior

Modify the shebang of `config.sh` to `#!/bin/bash -e` and add a command that returns a non-zero value to the script. It won't abort the build.

## OS and Software information
+ KIWI version: git master
+ Operating system: OpenSUSE Tumbleweed
+ OBS version: build.opensuse.org

**Comment by schaefi** [comment]
I think the reason why we run scripts through bash was that we wanted to be sure the code gets evaluated through bash and nothing else. If we change this, it will have some effects:

1. Every user has to make sure the x-bit is set on the script, such that it is executable
2. Every user has to set a shebang to create the interpreter reference

So this will impact all scripts already existing out there. This means we need a strategy to not break
it. I suggest if the script is not marked executable we run it through bash like before

Thoughts ?

**Comment by schaefi** [comment]
And I agree it deserves an entry in the docs

**Comment by dcermak** [comment]
> I suggest if the script is not marked executable we run it through bash like before.

I think this is a reasonable default:
1. Scripts without the +x bit are executed via bash
2. Scripts with the +x bit are executed via the OS itself

If you agree with this approach, I'll prepare a PR.

**Comment by schaefi** [comment]
Sounds good to me :+1:

**Comment by Vogtinator** [comment]
Note that on OBS, file permissions aren't preserved so this is not possible to use on OBS AFAIK

**Comment by dcermak** [comment]
> Note that on OBS, file permissions aren't preserved so this is not possible to use on OBS AFAIK

I'll add that to the docs.
