### ISSUE TITLE
repo url not using obs:/ scheme: 

### ISSUE THREAD

**Issue by Mexit** [SUSE/kiwi#991]
## Problem description
Repository not recognized
`repo url not using obs:/ scheme: http://download.videolan.org/SuSE/Tumbleweed/`

KIWI configuration:

`<repository alias="videolan" type="rpm-md">`
`<source path="http://download.videolan.org/SuSE/Tumbleweed/"/>`
`</repository>`

## OS and Software information
+ KIWI version: 
+ Operating system: openSUSE Tumbleweed
+ OBS version: build.opensuse.org

**Comment by schaefi** [comment]
Well you are building inside obs. As the error message says you can't use direct remote urls when building in obs. The open buildservice forbids direct outgoing connections. On a local machine with access to the internet and a direct kiwi call this is not a problem
